### ISSUE TITLE
Don't know how to build task 'parallel_spec'

### ISSUE THREAD

**Issue by nlegaillart-dri** [ruby-concurrency/concurrent-ruby#1033]
Hi,

```
* Operating system:                linux
* Ruby implementation:             Ruby
* `concurrent-ruby` version:       1.2.3
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used: no
```

We are getting a strange issue in our CIs since yesterday (latest release):

```
rake aborted!
Don't know how to build task 'parallel_spec' (See the list of available tasks with `rake --tasks`)
/builds/puppet/control-repo/vendor/bundle/ruby/2.7.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```
We use `concurrent-ruby` in our onceover tests for Puppet code:

```
bundle exec onceover run spec --strict_variables --fail_fast --force --parallel $(nproc)
```

All our CIs are failing because of this. Could it be related to the latest release? We had this issue in the past but could not figure what was going on then (so we just removed `--parallel` at that time). We tried to force version in the Gemfile but with no luck, so we opened this issue just in case.

Regards,

--
Nicolas

**Comment by eregon** [comment]
From what I can see it has nothing to do with concurrent-ruby.
You can try to pin to the previous concurrent-ruby release to be absolutely sure.

It sounds like the `parallel_spec` task is not defined in your Rakefile, or transiently not defined.

BTW `bundle exec onceover run spec --strict_variables --fail_fast --force --parallel $(nproc)` doesn't seem to call rake so not sure that's the relevant command. If it is then maybe a bug of `oncerover` or `run`.

**Comment by nlegaillart-dri** [comment]
Ok, thanks for your help, we'll keep investigating.
