### ISSUE TITLE
Ruby 3.5 to drop `win32ole`

### ISSUE THREAD

**Issue by Earlopain** [ruby-concurrency/concurrent-ruby#1048]
Ruby is continuing its path of requiring more gems to be specified. `win32ole` is next on the list (among others) and will start warning in Ruby 3.4: https://github.com/ruby/ruby/commit/f365bef0c78085b7db9b6736ae59c1657baa79a3

Usage is here, to get the number of cores on windows: https://github.com/ruby-concurrency/concurrent-ruby/blob/b5e090b9da95c63cd006721ae6a7e594ec78512b/lib/concurrent-ruby/concurrent/utility/processor_counter.rb#L71-L75

Something like the following may be a suitable replacement:
```rb
IO.popen("wmic cpu get NumberOfCores", &:read).scan(/\d+/).map(&:to_i).reduce(:+)
```

Output of that command:
`NumberOfCores  \n\n4              \n\n\n\n`

I have also openend the same report on `parallel` at https://github.com/grosser/parallel/issues/345 if you are interested. Both implementations for this are basically the same.

**Comment by eregon** [comment]
Thanks for the heads up. Could you make a PR with that?
Agreed it's better to stop needing win32ole than to add the dependency.

**Comment by Earlopain** [comment]
I'll try to do that tomorrow. I just read that this tool is actually deprecated (though I have no idea how aggressive microsoft would be here), so first check via powershell  `(Get-ComputerInfo).NumberOfCores` (currently untested) and fall back to wmic.
