### ISSUE TITLE
Remote Actors

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#147]
Starting issue for discussion, cc @jdantonio @lucasallan.

I am thinking about following:
-   to have an actor which would represent a bridge to other process
  -   as you've mentioned, with plug-able transport layer (usual adapter pattern I guess) 
-   `RemoteReference` implementation which would represent actors in different process, it would be created by bridge-actor and route the messages back there
-   any normal `Reference` going through bridge would be translated to `RemoteReference` so it would allow for transparent communication no matter in which process the actor actually is.

What are you thoughts?

**Comment by chrisseaton** [comment]
Closing due to extreme age.
