### ISSUE TITLE
Remove configuration of global pools

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#149]
-   keep them lazy initialized
-   rename: task -> short-non-blocking, operation -> long-blocking
-   add more global executors like an immediate executor
-   remove configuration object, move global pools to `Concurrent` space
-   possibly improve parsing of :executor option 
    -   to also handle agent two pools
    -   to understand :immediate too
    -   etc.
-   what to do with logging?

@chrisseaton @jdantonio, I've tried to capture the result of the discussion.

**Comment by jdantonio** [comment]
Addressed in PR #255.
