### ISSUE TITLE
TimerSet's priority queue has nil elements

### ISSUE THREAD

**Issue by gmalkas** [ruby-concurrency/concurrent-ruby#193]
Hey,

it seems TimerSet's priority queue has some nil elements:

```
NoMethodError: undefined method `time' for nil:NilClass
    /.bundle/jruby/1.9/bundler/gems/concurrent-ruby-48c74dee7152/lib/concurrent/executor/timer_set.rb:108 :in `<=>`
    /.bundle/jruby/1.9/bundler/gems/concurrent-ruby-48c74dee7152/lib/concurrent/collection/priority_queue.rb:276 :in `pop`
    /.bundle/jruby/1.9/bundler/gems/concurrent-ruby-48c74dee7152/lib/concurrent/executor/timer_set.rb:139 :in `process_tasks`
    /.bundle/jruby/1.9/bundler/gems/concurrent-ruby-48c74dee7152/lib/concurrent/executor/timer_set.rb:131 :in `process_tasks`
```

Here is the state of variables when the exception was raised:
```ruby
    {
      "self" => "#<struct Concurrent::TimerSet::Task time=1416912118.263, args=[#<Concurrent::Event:0x59a176fc @mutex=#<Mutex:0x38684d54>, @condition=#<Concurrent::Condition:0x47ace2ba @condition=#<ConditionVariable:0x27594619>>, @set=false>], op=#<Proc:0x5609277d@/.bundle/jruby/1.9/bundler/gems/concurrent-ruby-48c74dee7152/lib/concurrent/timer_task.rb:318 (lambda)>>",
      "other" => "nil"
    }
```

This seems a bit strange to me, as reading through `TimerSet` code I do not see how a `nil` element could be pushed onto the queue.

Any idea?

Version information:
concurrent-ruby 0.7.0
jruby 1.7.16.1 on Java 8

Thanks!

**Comment by jdantonio** [comment]
@obrok Have you been able test this fix?

**Comment by obrok** [comment]
Not yet, sorry :( We're battling some stability problems, and I don't want to potentially add to them before they are resolved.

**Comment by jdantonio** [comment]
@obrok No sweat. We'll keep it open for now.

**Comment by jdantonio** [comment]
I'm closing this issue because we believe it to be fixed by #217 and other updates, all of which were released in 0.7.2. If we discover that it hadn't been fixed we will open a new issue.

**Comment by obrok** [comment]
@jdantonio I restored the functionality where we encountered this problem and it seems it no longer happens.

**Comment by jdantonio** [comment]
@obrok Awesome! Thank you!
