### ISSUE TITLE
ThreadLocalVar fails tests on MRI 2.2 and Rbx 2.4.1

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#219]
The test `Concurrent::ThreadLocalVar GC does not leave values behind when bind is not used` fails consistently on MRI 2.2 and Rbx 2.4.1. This test manually triggers garbage collection then counts objects that still remain. The tests may be failing due to inconsistencies in GC or a bug in the code. Further investigation is required.

* [Failing MRI build](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/45622612)
* [Failing Rbx build](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/45622619)

**Comment by pitr-ch** [comment]
I'll update #215 to master and try again.

**Comment by chrisseaton** [comment]
I understand why it fails on Rubinius now - Rubinius by design totally ignores requests for GC.

I think we just need to say that this is a bad test and remove it. It tests for something that the language does not guarantee to do - it's simply broken.

**Comment by jdantonio** [comment]
I've removed the test and merged #215. As much as I'd like to have a working test I just don't know that we can accurately test this.

**Comment by pitr-ch** [comment]
@chrisseaton thanks for the info. Could you point me to a source. I would like to find out more.

**Comment by chrisseaton** [comment]
Sorry! I had it the wrong way around! It's JRuby that actively ignores any request for GC. Rbx does try to honour it, but it doesn't guarantee to.

Rbx GC primitive: https://github.com/rubinius/rubinius/blob/master/vm/object_memory.cpp#L506-L574
JRuby's GC rationale: https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyGC.java#L42-L52

**Comment by pitr-ch** [comment]
@chrisseaton my C++ knowledge is not strong but it looks like rbx runs the GC unless:
- GC disabled
- or GC is already running
In other cases `GC.run true` should force the GC to run. That does not sound too bad, I'll revisit the tests later for rbx. 

Looking at JRuby GC-forcing, I've found few hacks which none of them were good/reliable. Only sound thing I found is using `ForceGarbageCollection` function in JVMTI and triggered by JNI, see http://sleeplessinslc.blogspot.cz/2008/12/jvmti-jni-absolute-power.html. What do you think?

**Comment by chrisseaton** [comment]
That's probably not portable to other JVMs though. There are some GCs that are not designed to do a blocking collection (for example C4) and I'm not sure if it's possible to force them to do one.

I'll still say that I think it's just a broken test.
