### ISSUE TITLE
concurrent/atomics.rb does not require thread_local_var in 0.7.1

### ISSUE THREAD

**Issue by cmbaron** [ruby-concurrency/concurrent-ruby#220]
Just updated to 0.7.1, got a NameError trying to use Concurrent::ThreadLocalVar
worked around by adding :require => ['concurrent', 'concurrent/atomic/thread_local_var'] in my Gemfile

**Comment by jdantonio** [comment]
@cmbaron Thanks for the info. I apologize for the bug--that's a pretty serious oversight on our part. We're working on a 0.7.2 release so we'll make sure this gets fixed ASAP.

**Comment by jdantonio** [comment]
Fixed in PR #215
