### ISSUE TITLE
0.7.2 and 0.8.0 Releases

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#221]
I'd like to lock down the remaining work and release dates for the 0.7.2 and 0.8.0 releases. @pitr-ch, @chrisseaton, and @headius are all speaking at [FOSDEM](https://fosdem.org/2015/) so I would like to have these latest versions released before the event. As a reminder, 0.7.2 and 0.8.0 will [have equivalent features but will handle compiled C extensions differently](https://github.com/ruby-concurrency/concurrent-ruby/pull/205#issuecomment-66880218). As far as I know there are only two outstanding issues that need addressed:

- [x] The test for `Concurrent::Atomic inherits from JavaAtomic` is broken on the 0.8.0 branch due to project reconfiguration (although the built gem works correctly)
- [x] A `ThreadLocalVar` test that depends on manually triggering GC is [broken on MRI 2.2 and Rbx 2.4.1](https://github.com/ruby-concurrency/concurrent-ruby/issues/219)
- [x] Fix the broken Windows versions of the extension gem (broke in pre2)
- [x] @pitr-ch provide `ThreadLocalVariable` gc test at least for MRI #228

Are there any other outstanding features that need addressed in the next release?

I would like to release the weekend of January 24-25, if possible.

**Comment by pitr-ch** [comment]
- [ ] @pitr-ch provide tests at least for MRI
