### ISSUE TITLE
Remove brutal thread killing in tests

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#226]

**Comment by jdantonio** [comment]
Addressed in #296

**Comment by jdantonio** [comment]
![screen shot 2015-05-25 at 8 14 54 pm](https://cloud.githubusercontent.com/assets/173910/7803334/de95505a-031a-11e5-82d7-d0b584082d8e.png)

**Comment by jdantonio** [comment]
A thing of beauty...

**Comment by pitr-ch** [comment]
Nice :)
