### ISSUE TITLE
Document or improve global-pool's auto termination

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#227]
If `concurrent-ruby` is used in tests of other project, the thread pools are terminated before the tests are executed. Reason is the order of `at_exit` callbacks, termination runs before the test run is executed.

**Comment by rkday** [comment]
This was part of my motivation for https://github.com/ruby-concurrency/concurrent-ruby/pull/199 - I hit exactly this with minitest/autorun, and it's much easier to spot if you get an exception by default.

It's easy to work around by setting `Concurrent.configuration.auto_terminate = false` in a minitest_helper.rb file.

**Comment by pitr-ch** [comment]
the solution is partly also discussed in #248

**Comment by jdantonio** [comment]
Addressed in PR #255.
