### ISSUE TITLE
Document what "memory model" guarantees each Atomic method provides

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#232]

**Comment by pitr-ch** [comment]
Follow up of https://github.com/ruby-concurrency/atomic/issues/2

**Comment by pitr-ch** [comment]
It looks like the C code uses a full memory barrier, see https://github.com/ruby-concurrency/concurrent-ruby/blob/master/ext/concurrent/atomic_reference.c#L29-L38

**Comment by jdantonio** [comment]
@pitr-ch Has this been handled as part of the documentation of the synchronization layer?

**Comment by pitr-ch** [comment]
it was not. I'll add something quickly.

**Comment by chrisseaton** [comment]
I think the memory model is out of scope. It hasn't yet been adopted by Core.
