### ISSUE TITLE
`Condition` is using `Time.now`

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#245]
see https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/atomic/condition.rb#L42

It may cause performance issue and I am also not entirely sure if it is save to be used here.
We rely on this class a lot, we will have to find other way or give up the timeout detection.

**Comment by jdantonio** [comment]
@pitr-ch What's the concern with `Time.now`?

**Comment by pitr-ch** [comment]
Hm it turns out Time.now is actually much faster than I've expected. It was around 1.8601 µs  (microseconds), so about 10times slower than a method call (on MRI). The performance impact is not that big as I thought, still this should be as fast as possible so if we can we should consider removing it or using just `ConditionVariable` if the time-out detection is not needed.

Nevertheless there is another issue, when somebody changes time in the system this can start giving bad results.

**Comment by jdantonio** [comment]
On MRI this is being addressed in PR #253 by using Ruby's `Process::CLOCK_MONOTONIC` (see [here](http://ruby-doc.org//core-2.2.0/Process.html#method-c-clock_gettime)) which I didn't know existed. So I did some Googling to see if we could do something similar in Java and we can: `System.nanoTime()` (see [here](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/System.html#nanoTime())). Once we PR #253 merged I'll do a JRuby-specific update.

**Comment by tenderlove** [comment]
@jdantonio I *think* JRuby supports this monotonic API.  @headius is that true?

**Comment by jdantonio** [comment]
Confirmed that Rbx does *not* have this feature. https://twitter.com/rubinius/status/570336877250678786

**Comment by headius** [comment]
JRuby should support the monotonic clock already (based on nanoTime, unsurprisingly).

**Comment by jdantonio** [comment]
@headius Which versions of JRuby? It seems to me that it only supports this API in `jruby-head` but not the 1.7.x branch? Can you confirm? If so, we can easily use `System.nanoTime()` directly on versions of JRuby without `Process.clock_gettime`.

**Comment by headius** [comment]
Oh yes, sorry...my brain is already running on JRuby 9k :-D

Process::CLOCK_MONOTONIC is a Ruby 2.x feature, and JRuby 1.7 only implements 1.9.3. System.nanoTime should be pretty cheap, though.

**Comment by jdantonio** [comment]
Addressed in #253 and #254.
