### ISSUE TITLE
Reconsider Condition usage at some places

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#260]
There is lot of abstractions which are using `Condition` without using the added feature (ability to check if it timed out) which may be speeded up by using original `ConditionVariable`. It some cases the need for `Condition` could be eliminated by manually rechecking if the condition holds after a thread was signaled.

**Comment by jdantonio** [comment]
Once #287 is merged the only remaining use of `Condition` will be in `MVar`. I'll take a look at that sometime before the 1.0 release.

**Comment by jdantonio** [comment]
OK, I lied. I just updated `MVar` to use `ConditionVariable`. This Issue will be closed once we merge #287.

**Comment by jdantonio** [comment]
Addressed in #287.
