### ISSUE TITLE
how do I install with Jars? "deprecated. use instead jars/installer"

### ISSUE THREAD

**Issue by aplatypus** [ruby-concurrency/concurrent-ruby#265]
Hi,

I came here from the thread_safe gem project, both projects are emitting the message:

*  "deprecated. use instead jars/installer"

There's nothing fancy going on, apart from me using JRuby at this point.  The install commands:

* jruby -S gem  install  thread_safe
* jruby -S gem install concurrent-ruby

Produce this as output:

     jruby -S gem  install  thread_safe
     deprecated. use instead jars/installer
     Successfully installed thread_safe-0.3.5-java
     1 gem installed

and

     jruby -S gem  install  concurrent-ruby
     Fetching: concurrent-ruby-0.8.0-java.gem (100%)
     deprecated. use instead jars/installer
     Successfully installed concurrent-ruby-0.8.0-java
     1 gem installed

I'm unclear on where this message fits or how to 'resolve' this warning.  A search of thread_safe and concurrent-ruby haven't revealed any specific instruction or comments.  

What is the solution?

**Comment by jdantonio** [comment]
@aplatypus I've never seen that message so I don't have an answer for you right now, but I'll look into it ASAP. To do so I'll need to reproduce the warning locally. Can you answer a few questions about your environment, please?

* What version of JRuby are you using?
* What JDK/JRE are you using, and which version?
* What operating system and version are you using?
* How did you install JRuby (rvm, build from scratch, packaged installer)?

**Comment by aplatypus** [comment]
@jdantonio ... Hi there.  I had a response from the JRuby project:

*  https://github.com/jruby/jruby/issues/2726#event-259338624

Apparently it is a deprecated message -- so people can ignore it on JRuby 9.0.0.

You can consider this question '*resolved*'.

**Comment by jdantonio** [comment]
@aplatypus Awesome! I'm glad you were able to get the problem resolved. Since you are using our gems, please feel free to give us any suggestions or feedback. We love hearing from our growing community.
