### ISSUE TITLE
Migrate all remaining classes to Synchronization::Object

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#278]
Executors should be done asap.

**Comment by jdantonio** [comment]
I've spiked two different implementation of this, neither of which I am entirely happy with. Both feel like they would be completely refactored before a v2.0 release, but both could possibly work for the v1.0 release. I have performed no performance benchmarks.

* 62fe60cfc15e7da351c0a68805090e4576eee455 has the executors extend `Synchronization::Object` directly then inject themselves into the `Executor` module as the lock object.
* 490680cd3565ecbece54eed19ee989b0a17f2986 included a new `ExecutorService` class which extends `Synchronization::Object` and has Ruby/JRuby-optimized versions. The executors extend `ExecutorService`.

Thoughts? Have you been working on or thinking about a different implementation?

**Comment by pitr-ch** [comment]
I was thinking about following class structure:
`AbstractExecutor` < `Synchronization::Object`
`JavaExecutor` < `AbstractExecutor`
`RubyExecutor` < `AbstractExecutor`
`RubyThreadPoolExecutor` < `RubyExecutor`
`JavaThreadPoolExecutor` < `JavaExecutor`
relying only on the `Synchronization::Object` methods not creating any Mutex instances.

I was planning to take a look at it but you were faster :)

**Comment by jdantonio** [comment]
I should have some more time to work on this tomorrow night. I'll try it the way you suggested and see how it comes out.

**Comment by pitr-ch** [comment]
@jdantonio few comments on the commit.

**Comment by jdantonio** [comment]
See PR #283

**Comment by jdantonio** [comment]
Addressed in #287.
