### ISSUE TITLE
TVar transaction isolation possibly broken

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#282]
cc @chrisseaton 
I've noticed that there is a typo in `tvar_spec` see 
https://github.com/ruby-concurrency/concurrent-ruby/blob/master/spec/concurrent/tvar_spec.rb#L114. If fixed the test starts to fail. So far I did not look any deeper.

**Comment by chrisseaton** [comment]
Fixed in bd345ad250e1419ed7c71043c65d18f1fcce8941. It includes a pretty significant change so I will make sure I implement a stress test for it.

**Comment by pitr-ch** [comment]
@chrisseaton I've `got: 1, expected: 0` on https://github.com/ruby-concurrency/concurrent-ruby/blob/synchronization/spec/concurrent/tvar_spec.rb#L125-125 on `jruby-1.7.20`. Sorry I didn't have time to investigate further. It fails in about 35% of cases.

**Comment by chrisseaton** [comment]
Fixed in 674065c9c367bc5061fe39c2dda505a2995bee17
