### ISSUE TITLE
Update README and CHANGELOG

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#300]
The upcoming v0.9.0 release is fairly significant. The README and CHANGELOG need updated.

**Comment by pitr-ch** [comment]
Let me know when you have a skeleton of the changes, then I could go through my commits and fill in my part if you'd like.

**Comment by jdantonio** [comment]
I haven't started on this yet, but I'll push a branch as soon as I do. The changelog is up-to-date through Mar. 20. Since then it seems to be mostly internal refactoring, but there is still a lot. This could definitely benefit from both of us working on it.

**Comment by jdantonio** [comment]
Started in #323 

Everyone is welcome to add to the changelog. It's going to be very long...
