### ISSUE TITLE
bundle install failing on JRuby

### ISSUE THREAD

**Issue by ianks** [ruby-concurrency/concurrent-ruby#313]
Has anyone experienced this error when running `bundle install` inside of the dev repo? Things seem to work well on Travis (with Bundler being at version 1.7.12). 

```
Could not find gem 'concurrent-ruby (>= 0) ruby' in source at ..
Source contains 'concurrent-ruby' at: 0.9.0.pre1
```

#### Specs
- Arch Linux
- Bundler 1.7.12
- jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on OpenJDK 64-Bit Server VM 1.7.0_79-b14 [linux-amd64]
- rubygems 2.4.7

**Comment by jdantonio** [comment]
Delete Gemfile.lock

This started happening recently and I haven't had an opportunity to figure out why.

**Comment by ianks** [comment]
This solution works. This may be an issue we need to report to JRuby, but for this purpose I think its solved.
