### ISSUE TITLE
Async slowness on Jruby

### ISSUE THREAD

**Issue by Sdogruyol** [ruby-concurrency/concurrent-ruby#315]
Trying to process 1 million async calls.

I'm testing against JRuby-Head (9k) and after some time the process becomes unresponsive and stops processing.

When using CRuby it takes about 2G of Ram but completes without any slowing down.

```ruby echo.rb  28.85s user 0.90s system 99% cpu 29.779 total```

Here's the code snippet

```ruby
require 'concurrent'

class Echo
  include Concurrent::Async

  def initialize
    init_mutex # initialize the internal synchronization objects
  end

  def echo(msg)
    print "#{msg}\n"
    nil
  end
end

horn = Echo.new
numbers = 1_000_000.times.collect { rand }

numbers.each do |number|
  horn.async.echo number
end
```

Is this related to GC on JVM because the memory consumption increases rapidly and then stays nearly the same after some time.

**Comment by obrok** [comment]
I'm guessing you are running out of heap - the default maximum heap size for a java VM is I think on the order of half a gigabyte and when you start approaching that the VM is spending more and more time trying to reclaim memory and failing (because the data is still in use). You can change this limit by passing an option to jruby (-J-Xmx2G for 2 gigabytes for example).

**Comment by Sdogruyol** [comment]
@obrok thanks for the response. Here's the command that i used

```jruby echo.rb -J-Xmx2G```

Unfortunately I'm still getting the same result. It's like as if the GC pause is increasing rapidly till it nearly blocks the process.

**Comment by obrok** [comment]
1. It's possible there is indeed a memory leak of some sort
2. The memory usage might be different than on cruby - try a radically larger heap size, for example 4 or 8 gigabytes

**Comment by jdantonio** [comment]
@obrok Thanks for the quick response. I was in the process of running some tests when you responded.

@Sdogruyol There has been significant internal refactoring in the v0.9.0.pre1 release which should help with this. Unfortunately, some of my changes broke your example in that pre-release. I need to fix that before you can run your test on the latest release. I'll fix that tonight and get back to you.

**Comment by Sdogruyol** [comment]
Guess the heap size is and young/eden gc limit parameters are not being applied.

```jruby echo.rb -J-Xmx2G -J-Xmn512m```

Here's the error i'm getting

Error: Your application used more memory than the safety cap of 500M.0.987747284149765

**Comment by headius** [comment]
Put the -J parameters before the script you want to run; in this case you're just passing them as arguments to the script.

**Comment by Sdogruyol** [comment]
Confirmed putting the options before the script worked.

```jruby -J-Xmx2G -J-Xmn512m -w echo.rb```

Thanks @headius

**Comment by jdantonio** [comment]
@Sdogruyol This no longer appears to be an issue on the latest master branch (we've done significant internal refactoring). Can you please test against the latest? I can create a pre-release build of the gem if you would like.

Here is the Gist I used for testing: https://gist.github.com/jdantonio/1dddc74f090b904b3332
