### ISSUE TITLE
Buggy Tests

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#318]
- [x] [Concurrent::Promise fulfillment sets the promise state to :fulfilled if the block completes](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/65106242)
- [x] [Concurrent::Edge futures .schedule scheduled execution in graph](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/65112803)
- [x] [Concurrent::Edge futures .schedule scheduled execution](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/74747159)
- [x] [Concurrent::Promise rejection passes the reason to all its children](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/65822390)
- [x] [Concurrent::CyclicBarrier#wait without timeout should release all threads when their number matches the desired one](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/65833846)
- [x] [Concurrent::TimerTask dereferenceable it should behave like dereferenceable defaults :freeze_on_deref to false](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/66419811)
- [x] [Concurrent::ScheduledTask behavior it should behave like obligation #reason is set to error object of the exception when :rejected](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/66483570)
- [x] [Concurrent::Synchronization Concurrent::Synchronization::Object#wait waiting thread is sleeping](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/67094686)
- [x] [Concurrent::Edge futures .schedule scheduled execution](https://ci.appveyor.com/project/rubyconcurrency/concurrent-ruby/build/job/dpfr052yof8lxn89)
- ~~[ ] [Concurrent::Condition with one waiting thread timeout #wait should return 0 or negative number if timed out](https://ci.appveyor.com/project/rubyconcurrency/concurrent-ruby/build/28-master/job/gftyqvkg2qdt21r7)~~ *removed in 1.0*
- ~~[ ] [Executor.executor_from_options returns the global io executor when :operation is false](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/70941053)~~ *removed in 1.0*
- [x] [Concurrent::PureCountDownLatch spurious wake ups should resist to spurious wake ups with timeout](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/72460798)
- [x] [Concurrent::Channel::UnbufferedChannel with one thread without timeout #push should block
     Failure/Error: expect(t.status).to eq 'sleep'](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/72460797)
- ~~[ ] [Executor.executor_from_options returns the global io executor when :operation is false](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/73385177)~~ *removed in 1.0*
- [x] [Concurrent::ReentrantReadWriteLock write lock wakes up waiting readers when the write lock is released](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/73385180)
- [x] [Concurrent::TimerSet execution does not execute tasks early](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/74737213)
- [x] [Concurrent::PureCountDownLatch spurious wake ups should resist to spurious wake ups with timeout](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/74737212)
- [x] [Concurrent::Async#async sets the reason when giving too many optional arguments](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/74750235)
- [x] [Concurrent::Channel::UnbufferedChannel with one thread without timeout #pop should block](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/74750235)
- [x] [Concurrent::Edge::LockFreeLinkedSet#remove in a multi-threaded environment adds the items to the set](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/74755611)
- [x] [Concurrent::TimerSet execution executes all tasks scheduled for the same time](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/75426197)
- [x] [Concurrent::TimerSet execution passes all arguments to the task on execution](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/76307025)
- [x] [Executor.executor_from_options returns the global io executor when :executor is :io](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/76300876)
- [x] [Concurrent::TimerSet termination rejects tasks once shutdown](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/77262267)
- [x] [Concurrent::Future#initialize uses the global io executor by default](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/80627932)
- [x] [Concurrent::Agent#restart when #failed? does not clear the action queue when :clear_actions is false](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/80627931)
- [x] [Concurrent::TimerSet termination cancels all pending tasks on #kill](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/81948220)
- [x] [Concurrent::Agent#restart when #failed? does not clear the action queue when :clear_actions is not given](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/82073872)
- [x] [Concurrent::Edge::LockFreeLinkedSet#remove in a multi-threaded environment does not recognize the existence of the item when removed](https://ci.appveyor.com/project/rubyconcurrency/concurrent-ruby/build/472-master/job/8a9gyt64vl9gr21x)
- [ ] [Concurrent::Actor termination terminates with all its children](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/75376417)
- [ ] [Concurrent::Actor pool supports asks](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/82105848)

**Comment by jdantonio** [comment]
@pitr-ch The test `Concurrent::Edge futures .schedule scheduled execution` fails on at least one Windows version on almost every CI build. It's not a high priority, but can you please look into this when you get a chance?

**Comment by pitr-ch** [comment]
Sure, I'll look.

**Comment by jdantonio** [comment]
@ianks When you have some time, can you please look at [this failing test](https://ci.appveyor.com/project/rubyconcurrency/concurrent-ruby/build/266-thread_safe/job/97x9f313tiwad6t5) for `LockFreeLinkedSet`? It pops up occasionally.
