### ISSUE TITLE
Private APIs exposed in documentation

### ISSUE THREAD

**Issue by ianks** [ruby-concurrency/concurrent-ruby#327]
Looking throught the docs I have noticed that a lot of implementation specific APIs show up in the docs. I think this is rather confusing to the end user. There is too much information to consume in it, and will cause users much pain and suffering. We should fix this by 1.0. Thoughts?

**Comment by jdantonio** [comment]
Perhaps something like PR #322?

**Comment by ianks** [comment]
:smile:

**Comment by jdantonio** [comment]
:-)
