### ISSUE TITLE
Cancelable jobs

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#329]
> We'll be exploring and most likely using some wrapper CancellableJob which will use http://ruby-doc.org/core-2.2.0/Thread.html#method-c-handle_interrupt and http://ruby-doc.org/core-2.2.0/Thread.html#method-c-pending_interrupt-3F to get around the dangers of using `Thread#kill` and `Thread#raise`.

It's too late for 0.9 but this is rather critical problem. So could we add it to 1.0, provided we'll find a good solution?

**Comment by jdantonio** [comment]
Several people have asked about this so I think it's a reasonable addition to 1.0 if we can find a good solution. But I think that we should take as much time as necessary to find a good solution, even if we have to add it after 1.0 is released.

**Comment by pitr-ch** [comment]
Cooperative Cancellation is part of edge.
