### ISSUE TITLE
Moving new Future implementation to core

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#331]
Placeholder for a discussion we need to have.

**Comment by jdantonio** [comment]
I think the path should be this:

* Next release with Rails-supporting stuff (next week or two)
* Immediately create 1.0.0.pre1 where we remove all deprecated code
* Bug fixes, stress tests, etc. on 1.0.0.pre1
* Release 1.0 ASAP (30 days?)
* Immediately create 2.0.0.pre1 with Actor, new Future, etc.
* Bug fixes only on 1.x line
* Release 2.0 ASAP

Thoughts?

**Comment by pitr-ch** [comment]
:+1:

1.0 might be delayed though because of the Synchronisation layer (and Memory model) verification. We should also migrate all our classes to the layer.

**Comment by jdantonio** [comment]
In PR #391 all classes except MVar use Synchronization::Object. MVar uses two condition variables so it isn't compatible with the synchronization layer as it now exists.

**Comment by pitr-ch** [comment]
Great. Regarding MVar, would this https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/synchronization/condition.rb#L48-48 help?

**Comment by jdantonio** [comment]
That looks like it should work, but it didn't. The tests on 32e75b981d369262cd34ce7e674295f8aa95c59f hang. I didn't spend a lot of time on it so there may be something I'm missing.

**Comment by pitr-ch** [comment]
Doesn't `MVar` still have the race issues?

**Comment by jdantonio** [comment]
No. MVar is fine. It's the Exchanger implementation that uses MVar that has issues.

**Comment by jdantonio** [comment]
Now that we are beginning larger discussions about 2.0 I'm going to close out some of these issues. We don't need specific issues for each part of Edge yet. We can make new issues once we have a roadmap.
