### ISSUE TITLE
Possible indeterministic read/writes in AtomicFixnum.c

### ISSUE THREAD

**Issue by ianks** [ruby-concurrency/concurrent-ruby#338]
Auditing the code in `atomic_fixnum.c`, I noticed a possible source for error in the code.

```c
VALUE method_atomic_fixnum_value_set(VALUE self, VALUE value) {
  Check_Type(value, T_FIXNUM);
  DATA_PTR(self) = (void *) value;
  return(value);
}
```

The code for set direct sets the value of `DATA_PTR(self). Most of the time, users will be a a machine in which Fixnum less than or equal to the native word size, meaning that this assignment will be atomic. However, this behavior is not guanteed, and in a sense is logically flawed. This assignment, on some platfroms, will be nondeterministic.

The question I have is should be address this issue? Is it big enough to worry about? What are your thoughts on this?

**Comment by jdantonio** [comment]
If the behavior we want is not guaranteed then we need to fix it. Our philosophy is that our users are probably working in edge-case scenarios than the average Rubyist so we need to be *more* concerned about edge cases than other gems may be.

Is this related to #337?

**Comment by ianks** [comment]
Yes it is relate to #337. I was playing around with the code, but did not mean to PR it though. 

The reason I don't necessarily want to jump into prematurely fixing is two-fold:

1. I would like to demonstrate some live example of this, and attempt to know more about the system conditions which it would happen. Identifying a logical descrepancy is one thing, but if it's not possible for the bug to manifest IRL then is it really a bug? (puts on philosophers hat)

2. It's will necessarily create a significant performance hit for much of the other code.

I will attempt to recreate it though. On another note, this is the type of thing we can hope to uncover more of with the "stress tests."

**Comment by jdantonio** [comment]
@ianks I appreciate your help with this. Let me know if you need anything from me.

**Comment by ianks** [comment]
So after thinking about it for a bit yesterday, I have come to realize that we _cannot_ guarantee visibility on an AtomicFixnum variable with the current code. Whenever a thread looks up the current `value`, there is no guarantee that the is the most current up to date value. It may just be reading the variable from one processors cache. This means we cannot ensure consensus on the current AtomicFixnum. I think, at least for theoretical reasons, we should ensure synchronization for the `set` and `value` methods here.

**Comment by pitr-ch** [comment]
Since this is only a CRuby extension we can include CRuby's GVL into consideration. There is a mutex in  GVL, so acquiring thread always sees everything done by releasing thread. Regarding visibility it should be safe.

**Comment by jdantonio** [comment]
@ianks @pitr-ch So what is the verdict? Is this a safe operation or is it a bug?

**Comment by ianks** [comment]
I think that it is safe, but only due to MRI implementation details. The
real question is whether or not we rely on MRI internals to guarantee
thread-safety or not.
Also, if we consider this to be safe, wouldn't we also need to consider the
ir_set method in AtomicReference to be superfluous?

**Comment by jdantonio** [comment]
The C extension is only intended for MRI Ruby. Rubinius uses a different API for C extensions (and recommends not to use them anyway). So we can safely depend on the internals of MRI Ruby.

The `ir_set` method was part of the original `ruby-atomic` gem. I didn't change any of the implementation details when I merged it in. Honestly, I don't know enough about these low-level details to know if it's superfluous.

**Comment by ianks** [comment]
I ran the rest suite without synchronizing during `ir_set` and `ir_get` and nothing failed. Obviously, this should be taken with a large grain of salt as we arent stress-testing it yet, but it does make sense given the GVL.

**Comment by ianks** [comment]
Also, I believe that we can drop the synchronization in `MutexAtomic` as well if we are relying on the GVL. 

https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/atomic_reference/mutex_atomic.rb#L29

From my benchmarks, we are getting about a 165% speed boost by doing this.

**Comment by jdantonio** [comment]
We can depend on the behavior of the GIL in the C extensions, but we cannot necessarily do the same in the pure-Ruby code. Although the *vast* majority of Ruby users are likely running MRI, JRuby, or Rubinius, we can't guarantee that they are. Other Ruby interpreters exist. From the very beginning I've always taken the approach that this gem should be truly and completely interpreter agnostic. Which means we cannot write any code that only works on MRI, even when we've written optimizations for but Rbx and JRuby. This was an idealistic but intentional decision because I believe that Ruby should "just work" on any interpreter that follows the (strictly speaking, non-existent) spec.

I'd certainly be open to discussing a change in philosophy in which we explicitly support only MRI, JRuby, and Rbx. But that would be a separate discussion.

**Comment by ianks** [comment]
To be clear, I would propose to *only* remove synchronization given that we are on MRI and that the CExtension is not loaded. To me, this interpreter specific optimization is more or less equivalent to what we have already been doing with native extensions; meaning that we are optimizing depending on the platform, but maintaining the exact same behavior wrt API and functionality.

**Comment by pitr-ch** [comment]
I agree with @jdantonio. We have to have an implementation of AtomicReference which is Ruby implementation independent. In this case it's MutexAtomic so this class should keep synchronisation. We could add another implementation written in pure ruby just for MRI and compare the performance with the C extension, but I am not sure what would be the benefit of that. There are probably not many users on MRI witch cannot use concurrent-ruby-ext. Wes could explore the the synchronisation removal in C extension though, assuming that we make sure that it'll only ever run on MRI.

**Comment by ianks** [comment]
I am starting to think that relying on the GIL is not a wise move. Reasons:

- It makes it harder for us as contributors to ensure correctness of the program. Essentially, we are relying on the fact that MRI ensures synchronization. 
- Matz recently mentioned his intentions of [deprecating the GIL in upcoming Ruby versions](https://www.youtube.com/watch?v=bqWBB8-iEac). 

Obviously now this is a theoretical concern, but perhaps we should take pre-emptive steps to ensure safety, given that it doesnt have a large perforance hit.

**Comment by jdantonio** [comment]
I apologize, but I've lost track of everything we've discussed. To summarize: When writing pure-Ruby code we're going to continue assuming that the GIL does not exist. In C extensions we're going to assume that we're running under MRI and program with the GIL in mind. Is that everyone else's opinion?

Do we need to make any changes or can I close this issue?

**Comment by pitr-ch** [comment]
@jdantonio I agree. One exception being the new synchronisation layer. There is Ruby code which depends on MRI's GVL. I think the best approach is: All Ruby code is implementation independent and using the synchronisation layer which provides required tools for this library. Extensions may depend on internal details of their targeted implementations to gain more performance (they should still try to avoid it if possible). If there is new breaking change in any of the Ruby implementations we can drop the particular extension (if it's too difficult to update) and go to Pure Ruby using synchronisation layer (easy to fix for any changes because it's very small).

@ianks I know that it's not the best but I think such big change will be communicated and we'll have time to update.

**Comment by pitr-ch** [comment]
@ianks the original issue with native word size, what was the result there?

**Comment by thedarkone** [comment]
> There is Ruby code which depends on MRI's GVL. I think the best approach is: All Ruby code is implementation independent and using the synchronisation layer which provides required tools for this library.

I'm late to the party, but I would like to add that IMHO it is also correct to have pure Ruby code that depends on MRI's GVL if it guaranteed to be only used on MRI (with a more generic Ruby code as a backup for other Ruby VMs).

> Most of the time, users will be a a machine in which Fixnum less than or equal to the native word size, meaning that this assignment will be atomic. 

> the original issue with native word size, what was the result there? I assume: It's ok since CRuby is not switching threads in C methods.

@ianks additionally aren't `Fixnum`s always tagged pointers on MRI? Therefore by definition they always fit into native word size and not tearing is possible. This also means that on x64 the max value of `Fixnum` is higher than on x86 (`(2**62)-1` vs `(2**30)-1`).

**Comment by ianks** [comment]
@thedarkone I agree. It seems contradictory to not rely GVL in the C extension yet not in pure Ruby version.

WRT Fixnum: yes, since Fixnum wil fit in the native word size I believe the assignment will not cause tearing. The assignment itself will be atomic, but there is nothing preventing the processor from reordering the instructions, which can cause visibility concerns amongst the other threads.
