### ISSUE TITLE
Edge future wait with timeout risks memory-leaking

### ISSUE THREAD

**Issue by iNecas** [ruby-concurrency/concurrent-ruby#347]
In the `wait_until_complete`, we push the thread into `@Waiters` stack. The problem is, we don't remove that from the stack and we keep pushing it there. Therefore, if you do something like this:

``` ruby
f = Concurrent.future
while true
  f.wait(0.001)
end
```

While it's needed to have long-running futures and perioadic checks with timeouts to reproduce, we should still be more cautious about this

**Comment by pitr-ch** [comment]
This one is tricky, if I try to prevent this it will require Set data-structure or something like that, which will be more expensive then the simple stack. It'll definitely require a warning there though. The assumption is that threads are:
- either waiting as long as they can then they abandon the waiting and fail or deal with the missing result in another manner,
- or if they check periodically they will use `completed?` which does not contain any slow synchronization around putting the thread to sleep (it has just one volatile read).

All Futures has to be completed (success or fail) which will clear the references. 

It all boils down to if the assumption is correct or too dangerous.

**Comment by pitr-ch** [comment]
warning added in https://github.com/ruby-concurrency/concurrent-ruby/pull/349

**Comment by iNecas** [comment]
The question is, why do we need the `@Waiters` structure anyway?

**Comment by pitr-ch** [comment]
To be able to eliminate synchronized block from completion path when there is no thread waiting. It will do just one CAS then. See https://github.com/pitr-ch/concurrent-ruby/blob/futures/lib/concurrent/edge/future.rb#L291-L292

**Comment by iNecas** [comment]
My point is, couldn't we hande that by just some sequential number, rather than storing the actual threads. In this case, it could even be a boolean flag

**Comment by pitr-ch** [comment]
That's not a bad idea at all :+1: I wanted to have an option to inspect blocked threads, but the leak doesn't worth it.

**Comment by pitr-ch** [comment]
Hm, with `AtomicFixnum` there is an [aba](https://en.wikipedia.org/wiki/ABA_problem) problem :/ There is a way around it but I'll look into it later.

**Comment by pitr-ch** [comment]
Already done.
