### ISSUE TITLE
MutexAtomic#compare_and_set broken contract

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#350]
It may also return false if another thread is just reading the value, there should be lock not just try_lock:
https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/atomic_reference/mutex_atomic.rb#L45

**Comment by jdantonio** [comment]
I think it has to be `#synchronize` and not `#lock`. The `#lock` method will raise an exception if the lock cannot be acquired. Neither the C nor the Java implementation will ever raise an exception. In order to keep the behavior of the method consistent across all platforms the pure-Ruby code cannot raise an exception.

PS: Thank you @pitr-ch for creating this issue. I saw the comment from @SebastianEdwards in Gitter and was going to create an issue myself. You beat me to it! :-)

**Comment by iNecas** [comment]
I just want to confirm that this seems to cause unexpected issues even when not using the atomic reference directy (we use actors heavily): for example it seems to lead to

```
Concurrent::MultipleAssignmentError: multiple assignment
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:602:in `complete'
    /home/travis/build/Dynflow/dynflow/test/test_helper.rb:249:in `call'
    /home/travis/build/Dynflow/dynflow/test/test_helper.rb:249:in `block (3 levels) in <top (required)>'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:714:in `complete'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:797:in `complete'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:831:in `success'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:720:in `success'
``` 

or deadlocks:

```
fatal: No live threads left. Deadlock?
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/synchronization/mutex_object.rb:33:in `sleep'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/synchronization/mutex_object.rb:33:in `wait'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/synchronization/mutex_object.rb:33:in `ns_wait'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/synchronization/abstract_object.rb:72:in `ns_wait_until'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:347:in `block in wait_until_complete'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/synchronization/mutex_object.rb:18:in `block in synchronize'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/synchronization/mutex_object.rb:18:in `synchronize'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/synchronization/mutex_object.rb:18:in `synchronize'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:344:in `wait_until_complete'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:630:in `wait_until_complete!'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/edge/future.rb:522:in `value!'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/actor.rb:71:in `spawn'
    /home/travis/.rvm/gems/ruby-2.1.5/bundler/gems/concurrent-ruby-7b78cf2eec5f/lib/concurrent/actor/context.rb:117:in `spawn'
```

Both appeared in travis https://travis-ci.org/Dynflow/dynflow/jobs/66854036, when not using the c extension. When adding the C extension, this problem doesn't seem to occur: I will keep monitoring that though.

**Comment by jdantonio** [comment]
Fixed in #355.

@iNecas Can you please run your tests against the latest master using only the core gem (no C extensions) and let me know if the fix worked?

**Comment by iNecas** [comment]
I've added into our testing matrix to run both the ext and no-ext variant (Travis-CI is probably not very happy about it https://travis-ci.org/Dynflow/dynflow/builds/67221941 :), but I can keep them running side by side for a while to see if both work the same: will let you know after iterating few times with the tests: the failures are quite hard to reproduce, so it can take a while to appear even if they were still there

**Comment by iNecas** [comment]
So far so good, at least the deadlock issues and mutli-assignment seemed to disappear (I've hit some failing test on non-ext version, but couldn't not reproduce locally: still a chance it would be something with my test suite: will monitor that, especially the comparison to the ext variant. Thanks @jdantonio

**Comment by jdantonio** [comment]
@iNecas Thanks for taking the time to help us debug this. I'm going to close the issue for now. We can open it again if the bug resurfaces.

**Comment by iNecas** [comment]
@jdantonio would you mind releasing 0.9.0.pre3: I would like to get this tested in production-like environments, where we need the code to be released as a gem

**Comment by jdantonio** [comment]
[Done](https://github.com/ruby-concurrency/concurrent-ruby/releases/tag/v0.9.0.pre3)

**Comment by iNecas** [comment]
Thanks @jdantonio !
