### ISSUE TITLE
`Concurrent.zip().then {}` should follow the logic of an empty set and immediately call the then part

### ISSUE THREAD

**Issue by iNecas** [ruby-concurrency/concurrent-ruby#351]
In current behavior, it doesn't proceed to the dependent future. I would expect, that the empty set of futures is completed immediately: all the futures are completed.

I have a use-case here https://github.com/iNecas/dynflow/blob/multi-executor-refactor/lib/dynflow/dispatcher/executor_dispatcher.rb#L55-L59, I had to solve that with conditinal check on the emptyness, which I don't like that much

**Comment by jdantonio** [comment]
:+1: The suggested behavior sounds more intuitive.
