### ISSUE TITLE
Actor Pool Graceful shutdown

### ISSUE THREAD

**Issue by sschepens** [ruby-concurrency/concurrent-ruby#362]
Is there a way to do a graceful shutdown of a pool?
Asking the pool to terminate doesn't wait for all workers to terminate

**Comment by pitr-ch** [comment]
Sorry about that there was none, I waited to have the new Futures in place so I could fix it easily. Please Try #363 PR and let me know.

**Comment by pitr-ch** [comment]
Fixed in #363
