### ISSUE TITLE
README link to v1.0 Roadmap is Broken

### ISSUE THREAD

**Issue by rfdonnelly** [ruby-concurrency/concurrent-ruby#378]
README.md has the following: 

    [v1.0.0 release](https://github.com/ruby-concurrency/concurrent-ruby/wiki/v1.0-Roadmap)

The link is broken.  Should it be https://github.com/ruby-concurrency/concurrent-ruby/issues/257 instead?

**Comment by jdantonio** [comment]
You are correct. Nice catch! I've fixed the link here: a1e777f5728c9d67ad590283eeaccde25e404e82. Thanks for the help!
