### ISSUE TITLE
Questions about Concurrent Ruby

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#379]
With the [Riding Rails announcement](http://weblog.rubyonrails.org/2015/7/17/this-week-in-rails-goodbye-rack-lock-concurrent-ruby-better-ac-parameters-and-more/) last week and [this discussion](https://github.com/rails/actioncable/issues/16) over at ActionCable, there are a lot of people talking about concurrent-ruby. Please use this thread for general questions about who we are, what we do, and what we provide.

**Comment by Asmod4n** [comment]
When you want to run, say, 500 blocking operations at once (I/O Server), do you still need 500 actors?

**Comment by jdantonio** [comment]
@Asmod4n The best person to answer your question is @pitr-ch since he built our actor implementation, but the short answer is Yes. But this also raises the question, is actor the best abstraction for your problem?

Like all our high-level abstractions, our actors run on one of the global thread pools. (You can also use dependency injection to provide a custom thread pool if you like.) Internally, however, each actor uses a class called `SerializedExecution` to ensure that each actor performs all its assigned tasks in the order they were received--one at a time. This behavior is *identical* to both Akka's actor and Erlang's  `gen_server`. A single actor does one thing at a time, it just does so concurrently with respect to everything else in the system.

If you want to run many I/O tasks simultaneously, we have other high-level abstractions that may be suitable for the task. A set of `Future`s  is very common. Consider this code:

```ruby
require 'concurrent'

stock_symbols = [...] # provide a list of stock symbols here

futures = symbols.collect do |stock_symbol|
  Future.execute { FinanciApi.get_stock_price(stock_symbol) } # do the I/O operation here
end

stock_prices = futures.collect {|future| future.value } # iterate over all futures and get the values
```

The above code will run all the futures on the `GLOBAL_IO_EXECUTOR` which is a thread pool with an unbound size and unbound queue length. It will add as many threads as it needs (until the OS won't let it create any more--around 2000 on OS X, more on Linux). In the above example, all the I/O operations should run concurrently.

This highlights one of the biggest advantages of `concurrent-ruby` over other Ruby concurrency libraries. We are intentionally "unopinionated." We don't try to sell our users on the fallacy that there's a "one size fits all" concurrency solution. We provide a broad and deep toolkit that allows you to choose the best tool for the job.

**Comment by jdantonio** [comment]
@Asmod4n On point of clarification, it's probably not a good idea to run 500 I/O operations concurrently. There are performance costs associated with creating and managing a large number of threads. This is a situation where our ability to inject a custom executor is very handy:

```ruby
pool = Concurrent::FixedThreadPool.new(10)

futures = symbols.collect do |stock_symbol|
  Concurrent::Future.execute(executor: pool) { FinanciApi.get_stock_price(stock_symbol) }
end
```

**Comment by Asmod4n** [comment]
@jdantonio thats what i was looking for :)

**Comment by pitr-ch** [comment]
Another approach (it would be interesting to compare the performance) could be to use some event loop lib (e.g. EventMachine) to deal with the IO, doing only necessary work in callbacks, distributing rest of the work to actors, futures, etc.

**Comment by Asmod4n** [comment]
Call be uninformed, but doesn't all I/O have to be handled by EventMachine for the current Process then?

**Comment by pitr-ch** [comment]
It might be better to do it all uniformly on EventMachine but it's not required. E.g. all http requests could go through EM where translated to messages and then to actors for processing, but other parts of the code can use IO blocking operations to access files or other stuff without EM.

**Comment by jdantonio** [comment]
EventMachine suggests that all concurrency be handled by EM, but that's not a requirement. EM just uses Ruby threads under-the-hood so you can mix-and-match. You just have to know what you are doing. The flow @pitr-ch suggests should work fine. The basic application flow would be:

1. General initialization/configuration
1. Start actors for processing received messages
1. Start the EM reactor
  - Create I/O listeners
  - When a message is received, pass to appropriate actor for handling
1. Stop the EM reactor when shutdown signal is received
1. Stop all actors
1. Final cleanup and exit
