### ISSUE TITLE
2.0: Align APIs of AtomicReference, AtomicFixnum, and AtomicBoolean

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#383]
`AtomicReference` originated in a different gem. `AtomicBoolean` and `AtomicFixnum` were created simultaneously, but have since diverged. In the 2.0 release we need to give all three classes a common API.

**Comment by sschepens** [comment]
I want to take advantage of this to propose allowing `increment` and `decrement` methods of `AtomicFixnum` to receive a number that indicates the amount should be incremented or decremented.

**Comment by jdantonio** [comment]
@sschepens I think that's an excellent idea, and very easy to implement.

**Comment by lucasallan** [comment]
Could you explain how is this common api? @jdantonio

**Comment by ianks** [comment]
On this note, let's make sure AtomicMarkableReference is in line too.

**Comment by jdantonio** [comment]
Soon I will begin posting new issues which propose consistent APIs for concurrent-ruby v2. Consistent APIs for the atomics will be included.We will continue this discussion over there. Certain methods (like `#increment` and `#decrement`) won't work for all of our atomics, but every proposed method should exist on every class where it makes sense.

If anyone would like to propose an API for the atomics please feel free. I'd love to get the feedback from others.
