### ISSUE TITLE
2.0: Drop support for Ruby 1.9.x?

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#392]
I doubt this will be very controversial, but it's good to have public discussion on such things. In the 2.0 release I would like to drop support for Ruby 1.9.x. The Ruby core team [stopped supporting 1.9.3](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/) in February of this year. Rails 5 [will only run on Ruby 2.2+](http://www.sitepoint.com/whats-new-rails-5/). JRuby 9000 was [released last month](http://jruby.org/2015/07/22/jruby-9-0-0-0.html). Since 1.0 supports MRI 1.9.3 and JRuby 1.7.x, I don't see any reason our 2.0 release should support those older versions of Ruby.

**Comment by ianks** [comment]
I agree we should drop 1.9.x support. What do you think our policy should
be for supporting Ruby versions in the future?

**Comment by pitr-ch** [comment]
cc @iNecas

**Comment by iNecas** [comment]
As long as 1.0 keeps running 1.9, and the 2.0 will still run on Ruby 2.0 I'm ok with it.

In general, in the "enterprise" point of view (I know many people don't like the word, but we don't make that disappear just by not looking that way:), the upstream end of support is not the end of real support (for example, Red Hat keeps backporting imporant, especially security, fixes after that date).
On the other hand, the developer in me always welcomes new versions over the old ones (keyword arguments, I'm really looking forward to start using you!:)

Therefore, I would suggest to use the common sense: each drop of some version has a risk of preventing some people (and traditionally, this might be quite big infrastructures with big potential for testing the library in extreme environments and loads, as well spend time to fix the code upstream). If supporting the old version starts causing too many troubles (many conditional statements just for the release or preventing us moving forward), we should drop it. On the other hand, if the motivation is just to use some new syntax sugar, we would be IMO better with scarifying the little developer L&F enhancements for more users running the code.

**Comment by pitr-ch** [comment]
From my side: we should be vocal about this to collect objections (Including a deprecation warning when running on ruby 1.9 ?), otherwise I am inclined to dropping support.

**Comment by jdantonio** [comment]
When 2.0 is released it will support whatever version(s) of Ruby is supported by the latest versions of Rails and JRuby. Rails 5 will drop support for Ruby 1.9 so we'll look mainly at JRuby. If the latest version of JRuby only supports Ruby 2.x at that time then we'll drop support for 1.9. Otherwise we'll retain that support.
