### ISSUE TITLE
2.0: Remove the `Dereferenceable` module?

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#393]
The [Dereferenceable](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/concern/dereferenceable.rb) is something I created in the early days of this gem. I was working with Erlang (and some Clojure) and became enamored of immutable variables. The `Dereferenceable` module was my attempt to allow the programmer to (somewhat) enforce safety by copying, duplicating, and/or freezing objects before returning them. Over time I've begun to question the value of this module. Ultimately, Ruby is a highly dynamic and mutable language. Without language-level support it's very difficult to enforce immutability. The `Dereferenceable` module adds complexity and overhead with questionable benefit.

Is anyone actually using the deref options (`dup_on_deref `, `freeze_on_deref `, and `copy_on_deref `)? Does anyone have any objection to removing this module in 2.0?

**Comment by pitr-ch** [comment]
:+1: for removing.

If there are users we could improve it. Replacing current module implementation (which pollutes object space) by 4 singleton implementations of Dereferenceable. One of them would be injected to the object at construction time.

**Comment by lucasallan** [comment]
Should we add a deprecation-warn before actually remove it? @jdantonio

**Comment by jdantonio** [comment]
The `Dereferenceable` module will be removed in 2.0. It was in interesting idea but ultimately misguided.
