### ISSUE TITLE
Synchronisation layer improvments

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#407]
- [x] Prefer composition over inheritance of the `Synchronisation::Object`. Keep it internally though for our classes to avoid indirections, forbidding subclassing.
- [x] Add abstraction for CAS on fields (currently AtomicReference in a final field - with indirection) to be able to swap to better in place implementation where they become available.
- [x] break down the supported tools to avoid cost of instantiating mutex/condition when not needed (e.g. when only final fields are used)

**Comment by ianks** [comment]
Is it possible to have a way of creating final fields without the @Uppercase syntax?

**Comment by pitr-ch** [comment]
Yeah it is possible, but since I use regular syntax to accessing instance variables I wanted to distinguish which one are final and which are not. There is nothing which would prevent changing value of the "final" variable.

**Comment by jdantonio** [comment]
@ianks The uppercase name is just a convention that @pitr-ch uses. It has no special meaning or behavior.

**Comment by pitr-ch** [comment]
I would like to do this for 1.0. Functionally it does not change anything, just the API to promote better usage and to allow replace CAS with better implementation when available.

**Comment by jdantonio** [comment]
If this is going to be in 1.0 then it needs to happen fairly soon. I apologize for being pushy, but we need to release 1.0 *before* Rails 5 is released. That has been plan ever since the Rails team approached us.

This weekend I am going to release `pre2` and submit a PR to Rails in which I replace `ThreadSafe::Cache` with `Concurrent::Map`. At that point we'll be committed to a 1.0 timeline aligns with Rails 5.

**Comment by pitr-ch** [comment]
Yeah I know, I've already started working on this. it'll be ready in a week for `pre3`. What's the Rails 5 schedule?

**Comment by jdantonio** [comment]
I don't know the Rails 5 schedule. All they have announced is "fall" 2015. If you think this will be done in a week I'm happy to hold off pre 2.
