### ISSUE TITLE
Concurrent::Array not packaged with gem?

### ISSUE THREAD

**Issue by andrewvc** [ruby-concurrency/concurrent-ruby#414]
Concurrent::Array / Map are not packaged with the gem though they are in the source code and the docs.

Why is this?

**Comment by jdantonio** [comment]
`Concurrent::Array/Map/Hash` were released in v1.0.0.pre1, a prerelease. By default, rubygems and bundler will not install prerelease gems. To install pre-release gems you must use the `--pre` argument when running the `gem` command (a good SO article [here](http://stackoverflow.com/questions/4041902/what-does-pre-do-in-gem-install-rails-pre)).

The formal API documentation ([here](http://ruby-concurrency.github.io/concurrent-ruby/frames.html), linked in the README) is still for the 0.9.1 version and will not updated until the full release of 1.0.0.

We are planning a second prerelease within the next week or two. We anticipate that 1.0.0.pre2 will be the last prerelease and the full 1.0.0 release will be within the next month or two (certainly before the release of Rails 5 and before RubyConf).

**Comment by andrewvc** [comment]
Thanks @jdantonio !
