### ISSUE TITLE
AtomicFixnum is broken (not atomic)

### ISSUE THREAD

**Issue by t3hk0d3** [ruby-concurrency/concurrent-ruby#420]
AtomicFixnum does not gurantee fixnum incremented atomically.

It reproducing both on MRI (2.1.5) and JRuby (1.7.20-1)

Here is reproduce code:

```ruby
require 'concurrent'
require 'concurrent/executor/thread_pool_executor'
require 'concurrent/atomic/atomic_fixnum'

pool = Concurrent::ThreadPoolExecutor.new(
   min_threads: Concurrent.processor_count,
   max_threads: Concurrent.processor_count
)

number = Concurrent::AtomicFixnum.new(0)

maximum = 1000.freeze

maximum.times do |i|
  pool.post do |arg|
    number.increment
  end
end

puts "Result: #{number.value}/#{maximum}"
```

Expected result:  ``Result: 1000/1000``
Actual result: ``Result: 993/1000`` (n -> 1000, n < 1000)

**Comment by t3hk0d3** [comment]
Oopps, my bad. Forgot about

```ruby
pool.shutdown
pool.wait_for_termination
```
to gurantee all taska are actually executed

**Comment by jdantonio** [comment]
I'm glad you were able to resolve this. If you have any more questions please don't hesitate to ask. We love feedback from users!
