### ISSUE TITLE
Concurrent::Future does work with Time.use_zone

### ISSUE THREAD

**Issue by leomao10** [ruby-concurrency/concurrent-ruby#425]
Hi There, I found that this bit of code doesn't work, the concurrent-ruby we are using at the moment is: 0.9.0

```
#set timezone to UTC
Time.use_zone("Sydney") do
  puts Time.zone.now.zone  # AEST
  Concurrent::Future.execute{ puts Time.zone.now.zone} # UTC
end
```

**Comment by jdantonio** [comment]
The code above works as expected. It's important to understand that the block passed to the `Future` does not actually run within the outer block created by `Time.use_zone`. The block passed to the Future is passed to the global thread pool where it is executed in a different context at a nondeterministic time. Even if, by chance, the Future executes before the outer block ends it still isn't running inside that block. This is the nature of concurrency. The following code example uses sleep statements to change the timing and illustrate this:

```ruby
Time.use_zone("Sydney") do
  puts "Outer start #{Thread.current.object_id} at UTC #{Time.now.utc}"

  Concurrent::Future.execute do
    puts "Future start #{Thread.current.object_id} at UTC #{Time.now.utc}"
    sleep(3)
    puts "Future finish #{Thread.current.object_id} at UTC #{Time.now.utc}"
  end

  puts "Outer finish #{Thread.current.object_id} at UTC #{Time.now.utc}"
end

puts "After start #{Thread.current.object_id} at UTC #{Time.now.utc}"
sleep(5)
puts "After finish #{Thread.current.object_id} at UTC #{Time.now.utc}"
```

The output from this code is:

```
Outer start 70366542561800 at UTC 2015-09-26 02:19:58 UTC
Future start 70366547048480 at UTC 2015-09-26 02:19:58 UTC
Outer finish 70366542561800 at UTC 2015-09-26 02:19:58 UTC
After start 70366542561800 at UTC 2015-09-26 02:19:58 UTC
Future finish 70366547048480 at UTC 2015-09-26 02:20:01 UTC
After finish 70366542561800 at UTC 2015-09-26 02:20:03 UTC
```

Please also note that this isn't a side effect of our Future implementation, it's the intrinsic nature of threads and blocks in Ruby. If you replace the Future in the above example with a simple Ruby thread you get the same result:

```ruby
Time.use_zone("Sydney") do
  puts "Outer start #{Thread.current.object_id} at UTC #{Time.now.utc}"

  Thread.new do
    puts "Future start #{Thread.current.object_id} at UTC #{Time.now.utc}"
    sleep(3)
    puts "Future finish #{Thread.current.object_id} at UTC #{Time.now.utc}"
  end

  puts "Outer finish #{Thread.current.object_id} at UTC #{Time.now.utc}"
end

puts "After start #{Thread.current.object_id} at UTC #{Time.now.utc}"
sleep(5)
puts "After finish #{Thread.current.object_id} at UTC #{Time.now.utc}"
```

results in:

```
Outer start 70197965095420 at UTC 2015-09-26 02:21:57 UTC
Outer finish 70197965095420 at UTC 2015-09-26 02:21:57 UTC
After start 70197965095420 at UTC 2015-09-26 02:21:57 UTC
Future start 70197969131980 at UTC 2015-09-26 02:21:57 UTC
Future finish 70197969131980 at UTC 2015-09-26 02:22:00 UTC
After finish 70197965095420 at UTC 2015-09-26 02:22:02 UTC
```

Also notice that the order of operations in these two examples is slightly different when I ran them on my machine. The Ruby runtime and the underlying operating system are responsible for schedule and context switching between threads. We, the programmer, have no control over this.

**Comment by eregon** [comment]
One solution here would be to move or replicate the Time.use_zone inside the future block I guess

**Comment by leomao10** [comment]
Thanks for your detailed reply @jdantonio 

You are correct, this is same behavior happened for Thread as well.

```
Time.use_zone("Sydney") do
  puts "Outer start #{Thread.current.object_id} with Timezone #{Time.zone.now.zone}"

  Thread.new do
    puts "Future start #{Thread.current.object_id} with Timezone #{Time.zone.now.zone}"
    sleep(3)
    puts "Future finish #{Thread.current.object_id} with Timezone #{Time.zone.now.zone}"
  end

  puts "Outer finish #{Thread.current.object_id} with Timezone #{Time.zone.now.zone}"
end

# Outer start 70154751181320 with Timezone AEST
# Future start 70154777535080 with Timezone UTC
# Outer finish 70154751181320 with Timezone AEST
# Future finish 70154777535080 with Timezone UTC

Time.use_zone("Sydney") do
  puts "Outer start #{Thread.current.object_id} with Timezone #{Time.zone.now.zone}"

  Concurrent::Future.execute do
    puts "Future start #{Thread.current.object_id} with Timezone #{Time.zone.now.zone}"
    sleep(3)
    puts "Future finish #{Thread.current.object_id} with Timezone #{Time.zone.now.zone}"
  end

  puts "Outer finish #{Thread.current.object_id} with Timezone #{Time.zone.now.zone}"
end

Time.use_zone("Sydney") do
  puts Time.zone.now.zone  # AEST
  Concurrent::Future.execute{ puts Time.zone.now.zone} # UTC
end

# Outer start 70154751181320 with Timezone AEST
# Future start 70154776135140 with Timezone UTC
# Outer finish 70154751181320 with Timezone AEST
# Future finish 70154776135140 with Timezone UTC
```

Although I still think that since `Time.use_zone` wrapped outside `Thread.new` or `Concurrent::Future.execute`, this `Thread` instance should use time_zone setted in outer scope. But this should be ruby's issue, not concurrent-ruby's issue, I will submit a ticket in MRI and see what they said.

Thanks again for your help :)

@eregon , yes, that is exactly what I use at the moment. Thanks for your suggestion

**Comment by eregon** [comment]
@leomao10 It seems due to the implementation in ActiveSupport
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/time/zones.rb
Changing the `default zone` would be an easier workaround if you only need one time zone globally.
But otherwise, threads do not inherit thread local-variables by design (actually it's even fiber-local variables here).
Essentially, it's a shortcoming of the implementation in ActiveSupport (but there is no easy fix to support the block form).
Something that does not rely on some form of global state would work better, like
```ruby
zone = Time. find_zone!("Sydney")
Thread.new {
  puts zone.now
}
```
