### ISSUE TITLE
Inconsistent `zip` return types

### ISSUE THREAD

**Issue by mikeknep** [ruby-concurrency/concurrent-ruby#438]
The inconsistent return types of `Concurrent#zip` (Edge) has led to some annoying boilerplate code in our codebase. To demonstrate the inconsistency:

```ruby
foo = []
bar = [Concurrent.succeeded_future(1)]
baz = [Concurrent.succeeded_future(1), Concurrent.succeeded_future(2)]

zip_foo = Concurrent.zip(*foo) # => Concurrent::Edge::Event
zip_bar = Concurrent.zip(*bar) # => Concurrent::Edge::Future
zip_baz = Concurrent.zip(*baz) # => Concurrent::Edge::Future

zip_foo.value! # => raises undefined method `value!` for Concurrent::Edge::Event
zip_bar.value! # => 1
zip_baz.value! # => [1, 2]
```

`zip_baz` feels correct to me, while I think `zip_bar.value!` should return a collection, i.e. `[1]`. And I don't understand if there's a valid reason for `zip_foo.value!` to return a different type (an `Event` instead of a `Future`).

As it stands now, I find myself writing a lot of code that looks like this:

```ruby
futures = widget.parts.map do |part|
  Concurrent.future { do_something_with(part) }
end

x = futures.present? ? Concurrent.zip(*futures) : Concurrent.succeeded_future([])

x.then do |*futures|
  Array(futures).map(&:some_other_task)
end
```

If `zip` always returned a collection, I could just write:

```ruby
futures = widget.parts.map do |part|
  Concurrent.future { do_something_with_part(part) }
end

Concurrent.zip(*futures).then do |*futures|
  futures.map(&:some_other_task)
end
```

**Comment by jdantonio** [comment]
@mikeknep You make a very compelling argument. I'm generally a fan of always returning a collection, even when empty. That feature is something @pitr-ch has been working on and he may have a specific reason for implementing it this way. I'd like to get his thoughts before we decide to make a change.

**Comment by pitr-ch** [comment]
I see your point, that's ugly. The reason was that zip is also able to zip over events which do not have a value, then it makes sense to return single value or just an even for cases like: `zip(event, event) => event`, `zip(event, future) => future-with-1-value`, `zip(event, future, future) => future-with-2-values`.

I look at it after 1.0 and I try to come with some solution, this definitely needs to be fixed.

**Comment by pitr-ch** [comment]
@mikeknep Thanks for letting us know, I appreciate the feedback!

**Comment by pitr-ch** [comment]
please @mikeknep see #496.

**Comment by mikeknep** [comment]
Can't comment much on the implementation as I haven't dug too deep into the internals, but the specs look solid; much more intuitive and consistent, no gotchas. Nice work, and thanks!

**Comment by hobodave** [comment]
PR looks good to me. Looking forward to the changes.
