### ISSUE TITLE
Agent#await causes validation errror

### ISSUE THREAD

**Issue by asppsa** [ruby-concurrency/concurrent-ruby#442]
Hi there,

Perhaps I'm doing it wrong, but it seems that calling `await` on an Agent will cause it to fail, even though the call seems to work.  See the following code:

~~~ ruby
require 'rubygems'
require 'bundler/setup'
require 'concurrent'

x = Concurrent::Agent.new(10)

x.send{ |x| sleep 1; x + 1 }
x.await

puts x.value
puts x.failed?
puts x.error
~~~

For me this will output the following:

~~~
11
true
Concurrent::Agent::ValidationError
~~~

So, the thread pauses on the await as expected, but in the meantime the agent is marked as failed.  This doesn't seem to have anything to do with the (lack of) validator, as changing the validator to something else does not change things.  I think perhaps the issue is to do with https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/agent.rb#L548

**Comment by jdantonio** [comment]
Nice catch! That is a bug. Fixed ib PR #443.
