### ISSUE TITLE
Uninitialized constants

### ISSUE THREAD

**Issue by Zapotek** [ruby-concurrency/concurrent-ruby#444]
I'm following the [examples](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Map.html) but getting `uninitialized constant` errors, for example:

```
2.2.3 :001 > require 'concurrent'
 => true 
2.2.3 :002 > Concurrent::Map
NameError: uninitialized constant Concurrent::Map
        from (irb):2
        from /home/zapotek/.rvm/rubies/ruby-2.2.3/bin/irb:11:in `<main>'
2.2.3 :003 > Concurrent::Hash
NameError: uninitialized constant Concurrent::Hash
        from (irb):3
        from /home/zapotek/.rvm/rubies/ruby-2.2.3/bin/irb:11:in `<main>'
```

I'm using concurrent-ruby 0.9.1.

Am I missing something?

**Comment by jdantonio** [comment]
`Concurrent::Map` was added in the 1.0 pre-releases. It is not in 0.9.x. Please install the latest pre-release.

**Comment by Zapotek** [comment]
That did it. :)
The project looks great btw, thank you.

**Comment by jdantonio** [comment]
Thank you! Let me know if I can help in any other way.
