### ISSUE TITLE
Custom transactions for Value Objects, Structures, and Collections

### ISSUE THREAD

**Issue by Zapotek** [ruby-concurrency/concurrent-ruby#445]
I couldn't find something relevant in the docs but is there a way to perform custom actions on, say, a `Concurrent::Hash` that share the same lock/sync procedures as the object itself?

Sometimes custom handling may be required prior to pushing or removing items and it'd be nice if those actions could be synchronized too.

**Comment by jdantonio** [comment]
Not on `Concurrent::Hash` and `Concurrent::Array`. Those classes are specifically intended to be functional, thread-safe replacements for Ruby's standard library `Array` and `Hash`.

`Concurrent::Map` has several methods which perform a variety of actions within the lock and some, such as `fetch_or_store`, take a block. We could potentially extend the API in the future, but probably not before the 1.0 release. That class is a direct import from the `thread_safe` gem (formerly `ThreadSafe::Cache`) and we want to keep the prior API at initial release.

**Comment by Zapotek** [comment]
That's fair enough, although `Map` is missing `#include?`, is that on purpose?

**Comment by jdantonio** [comment]
Interesting. I was not aware of that. @thedarkone, thoughts?

**Comment by jdantonio** [comment]
@Zapotek On a completely different topic: I notice you are the creator of Arachni. I :green_heart: those tools. I used arachni-rpc at my last job. It was awesome. Thank you for your work on that!

**Comment by Zapotek** [comment]
@jdantonio Thanks man. I've been keeping an eye on concurrent-ruby for a while too, so right back at you. :) In Arachni I'm mostly IO bound and run on MRI, so I've gone the non-blocking IO route rather than multi-threaded, but there are places where I can remove my own code and delegate to concurrent-ruby to make things cleaner so I decided to start the cleanup.

**Comment by thedarkone** [comment]
> That's fair enough, although `Map` is missing `#include?`, is that on purpose?

@Zapotek there is a `Map#key?` method that does what you want (careful not to confuse with `Map#key`). For Ruby's `Hash`, methods like `include?`, `key?` and `has_key?` are all just aliases of each other.

You can add `Map#include?` to [`lib/concurrent/map.rb`](https://github.com/ruby-concurrency/concurrent-ruby/blob/7a6cb23fad620ccf74079c51780c62a6ee4a8372/lib/concurrent/map.rb) like this:

```ruby
# somewhere in lib/concurrent/map.rb
class Map < Collection::MapImplementation
  alias_method :include?, :key?
end
```

Want to contribute to `concurrent-ruby`? I'm not against adding all the usual `Hash` aliases, you can create a PR for `Map#include?` :) (just copy `Map#key?` specs for tests).

**Comment by thedarkone** [comment]
@Zapotek As a side-note, don't count on `Concurrent::Hash`, `Array`, `Map` and any other general purpose concurrent data structures ever exposing their internal synchronization primitives. They are Ruby VM specific and even if they weren't, exposing them is not something we want to do (we want to be able to change them in the future for example).

**Comment by Zapotek** [comment]
@thedarkone Thanks for the info, is `#key?` new? It's not listed in the [docs](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Map.html).

**Comment by jdantonio** [comment]
It's probably a yardoc setup problem. We engage in a lot of shenanigans to load platform-specific internals and that often confuses Yard. So I write a lot of Yard marcos and liberally apply them to various class files. I haven't invested much time with the docs for the classes we imported from `thread_safe` so the generated docs are probably lacking. I'll create a to-do for myself.

**Comment by Zapotek** [comment]
Cool, thanks guys.
