### ISSUE TITLE
Completed pool stats incrementing

### ISSUE THREAD

**Issue by brandonhilkert** [ruby-concurrency/concurrent-ruby#450]
I'm looking to get stats from the `RubyThreadPoolExecutor`. I've created the following script:

```ruby
DEFAULT_EXECUTOR_OPTIONS = {
  min_threads:     2,
  max_threads:     4,
  auto_terminate:  true,
  idletime:        60, # 1 minute
  max_queue:       0, # unlimited
}.freeze

QUEUES = Concurrent::Map.new do |hash, queue_name| #:nodoc:
  hash.compute_if_absent(queue_name) { Concurrent::ThreadPoolExecutor.new(DEFAULT_EXECUTOR_OPTIONS) }
end

class Foo
  def perform(i)
    sleep 2
    puts i
  end
end

def print_stats(queue)
  puts "==========================================="
  puts "Length: #{queue.length}"
  puts "Queue Length: #{queue.queue_length}"
  puts "Completed: #{queue.completed_task_count}"
  puts "Scheduled: #{queue.scheduled_task_count}"
  puts "==========================================="
end

queue = QUEUES["foo"]

puts "Before enqueueing...\n"
print_stats(queue)

16.times do |i|
  queue.post(i) { |args| Foo.new.perform(*args) }
end

puts "After enqueueing...\n"
print_stats(queue)

sleep 10

puts "After processing...\n"
print_stats(queue)
```

The output is:

```
Before enqueueing...
===========================================
Length: 0
Queue Length: 0
Completed: 0
Scheduled: 0
===========================================
After enqueueing...
===========================================
Length: 4
Queue Length: 12
Completed: 4
Scheduled: 16
===========================================
0
2
1
3
6
4
7
5
8
9
10
11
12
14
15
13
After processing...
===========================================
Length: 4
Queue Length: 0
Completed: 4
Scheduled: 16
===========================================
```

Length, queue length, and scheduled make sense, but the `completed_task_count` seems to increment only up to the max number of workers. I was under the impression it would [increment as jobs are posted to the pool over time](http://www.rubydoc.info/github/ruby-concurrency/concurrent-ruby/Concurrent/RubyThreadPoolExecutor#completed_task_count-instance_method). Maybe I'm misunderstanding the metric, but I'd love to be able to deliver a web UI for [Sucker Punch](https://github.com/brandonhilkert/sucker_punch) and that would be a key metric to stream through a graph.

Thanks!

**Comment by jdantonio** [comment]
https://github.com/ruby-concurrency/concurrent-ruby/commit/dde0c618d52c2f25f40404dbfa387802bb671215

**Comment by brandonhilkert** [comment]
Awesome thanks! I'll be sure to work from master.

**Comment by jdantonio** [comment]
Sorry for the short response earlier today. I'll plan to publish another pre-release next week. Both @pitr-ch and I are speaking at RubyConf so we plan to release the final 1.0 just before.

Will it be attending RubyConf this year? If so I'd love to buy you a coffee/beer/other and chat.

**Comment by brandonhilkert** [comment]
@jdantonio No problem. You shouldn't feel obligated to respond on vacation :)

Rubyconf sounds exciting. Sadly, I won't make it this year. Looking forward to hearing about the release though. Perhaps, we can find another opportunity to chat.

From what I've played with so far, the project seems like a great fit for Sucker Punch. I'd love to plan to migrate to Sucker Punch to CR for `v2`. I've been interested in adding a mountable Web UI to the project for awhile, and Celluloid's API made it difficult to do so. Seems like may of the stats I would need to build something helpful are already readers in CR. If you're not opposed, I might send some PRs your way in attempts to build out the last few. 

As mentioned in the Google group post, there are a few things I would need to keep functionality on par with what's currently implemented in SP. I've love to help sort that out if you're open to it.

re: this particular issue, I pulled in master and am getting the same results:

```
# Gemfile
source 'https://rubygems.org'

# Specify your gem's dependencies in sucker_punch.gemspec
gem 'concurrent-ruby', path: "../concurrent-ruby", require: "concurrent"
gem 'pry'
```

```
Before enqueueing...
===========================================
Length: 0
Queue Length: 0
Completed: 0
Scheduled: 0
===========================================
After enqueueing...
===========================================
Length: 4
Queue Length: 12
Completed: 4
Scheduled: 16
===========================================
0
2
1
3
4
5
7
6
9
10
11
8
13
15
14
12
After processing...
===========================================
Length: 4
Queue Length: 0
Completed: 4
Scheduled: 16
===========================================
```

Maybe I'm doing something wrong. Thoughts on this and the above?
