### ISSUE TITLE
1.0 Feature Freeze

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#454]
I should have done this a little while ago, but it's time to freeze the current features in preparation for the 1.0 release. I'll crrate another pre-release build in the next day or two. After that it will be bug fixes and synchronization layer updates only.

**Comment by jdantonio** [comment]
I've released 1.0.0.pre5 and 0.9.2. I've also submit a PR to Rails updating it to the pre5 release. That PR was merged. AFAIK that's everything (except possibly some documentation) that we need to do before 1.0.0.

@pitr-ch Is there anything else you are still working on?

**Comment by pitr-ch** [comment]
Only, the documentation for atomicReference and I'll also rename `attr_volatile_with_cas` to `attr_atomic` and that should be all.

**Comment by pitr-ch** [comment]
see #467

**Comment by jdantonio** [comment]
I think we're good-to-go for the full 1.0.0 release. RubyConf starts this Sunday. How does everyone feel about releasing this Saturday, 11/14/2015? Any objections?

@pitr-ch @mighe @chrisseaton @ianks @rkday @obrok @lucasallan @alexdowad @iNecas @headius @thedarkone

**Comment by lucasallan** [comment]
:+1:

**Comment by mighe** [comment]
Fine by me. I'm using our gem in production and everything is OK :+1:

**Comment by thedarkone** [comment]
:+1:

**Comment by pitr-ch** [comment]
:+1:

**Comment by iNecas** [comment]
:+1: no incompatibilities or other issues observed in Dynflow
