### ISSUE TITLE
Spike Streem in pure Ruby

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#468]
Matz is prototyping a new stream processing system for concurrent applications. He's doing so by creating a new language called Streem. It seems to me that we can spike a reasonable prototype in pure Ruby using concurrent-ruby. I think that might be fun.

https://github.com/matz/streem

**Comment by klebervirgilio** [comment]
:+1:

**Comment by Ch4s3** [comment]
:+1:

**Comment by jdantonio** [comment]
I started spiking this the other day and it ended up being remarkably easy. I plan to work on this more next week and I expect I'll have something to share by the end of the week. I'll post something here and on Matz's Streem once I do.

**Comment by jdantonio** [comment]
I have a *long* way to go, but I've started a spike [here](https://github.com/jdantonio/ruby-streem).
