### ISSUE TITLE
Document project "no-go" rules

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#470]
We've long had a few "don't ever do this" rules for this gem. Specifically, no downstream dependencies and no monkey-patching Ruby. We need to document these clearly for potential contributors.

**Comment by pitr-ch** [comment]
:+1: and if possible we should write automated tests for them.

**Comment by jdantonio** [comment]
Documented in the [CONTRIBUTING](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/CONTRIBUTING.md#follow-the-guidelines) doc.
