### ISSUE TITLE
uninitialized constant Concurrent::ReentrantReadWriteLock

### ISSUE THREAD

**Issue by reidmorrison** [ruby-concurrency/concurrent-ruby#471]
In order to use `Concurrent::ReentrantReadWriteLock` is it expected that we need to perform the following require first before it is available?

```ruby
require 'concurrent/atomic/reentrant_read_write_lock'
```

IRB Example:
```ruby
2.2.3 :001 > require 'concurrent'
true
2.2.3 :002 > Concurrent::ReentrantReadWriteLock
NameError: uninitialized constant Concurrent::ReentrantReadWriteLock
	from (irb):2
	from /Users/rmorrison/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'
2.2.3 :003 > require 'concurrent/atomic/reentrant_read_write_lock'
true
2.2.3 :004 > Concurrent::ReentrantReadWriteLock
Concurrent::ReentrantReadWriteLock < Concurrent::Synchronization::Object
2.2.3 :005 > Concurrent::VERSION
"1.0.0"
```

Should I submit a PR if the intention is to make `Concurrent::ReentrantReadWriteLock` available after requiring `concurrent`?

**Comment by jdantonio** [comment]
Nice catch. `Concurrent::ReentrantReadWriteLock` should be loaded by `require "concurrent"`. The appropriate place for the `require` statement is `lib/concurrent/atomics.rb` (our directory structure is not idiomatic right now). I'd love a PR if you don't mind submitting one.

Thank you!

**Comment by reidmorrison** [comment]
@jdantonio Great talk at RubyConf about the GIL, it corrected many of our incorrect assumptions on how MRI works.
