### ISSUE TITLE
Include examples and documentation in the gem

### ISSUE THREAD

**Issue by voxik** [ruby-concurrency/concurrent-ruby#490]
Shouldn't the documentation and examples be included in resulting gem?

**Comment by jdantonio** [comment]
Ta this time there isn't much value in including either of those in the published gem. Our examples aren't really user-facing examples, they are mostly benchmarks and comparisons (see #476). Our documentation is still being regularly updated so the web is the best source for the most up-to-date documentation.

**Comment by pitr-ch** [comment]
@voxik hi, is there any issue with packaging?

**Comment by voxik** [comment]
@pitr-ch not really. I just thought that it could be useful to ship some documentation with the packaged gem. Thx
