### ISSUE TITLE
concurrent-edge: reading from a closed channel (timing issue)

### ISSUE THREAD

**Issue by kylewolfe** [ruby-concurrency/concurrent-ruby#494]
While writing a simple concurrent client for a RESTful service, I ran in to this scenario. The current code hangs on the last take on the channel, because take is performed before the channel is closed. Uncomment the sleep and the take operation returns a nil (as it should in both cases, IMO to avoid having to always use a 'done' channel. FYI, Golang does not block on reading of a closed channel, see: http://play.golang.org/p/WZelemy9Up)

```ruby
require 'concurrent-edge'

resp_chan = Concurrent::Channel.new
row_chan = Concurrent::Channel.new

# create caller worker
Concurrent::Channel.go {
  resp_chan << "1"
  resp_chan << "2"

  resp_chan.close
}

# create response worker
Concurrent::Channel.go {
  resp_chan.each{ |resp|
    row_chan << resp + "-1"
    row_chan << resp + "-2"
    row_chan << resp + "-3"
  }
  row_chan.close
}

p row_chan.take
p row_chan.take
p row_chan.take
p row_chan.take
p row_chan.take
p row_chan.take
#sleep(1)
p row_chan.take
```

**Comment by jdantonio** [comment]
Thanks for pointing this out and for the detailed explanation. I haven't had an opportunity to do more work on channels recently. I hope to get back on this soon. Right now I'm the only person working on channels and they are still very experimental. I'd love some help if you're interested hacking at the implementation.

**Comment by kylewolfe** [comment]
I can have a look at fixing this issue, but I am fairly new to Ruby.

A little more info: The issue may be isolated to Unbuffered channel implementation (https://github.com/ruby-concurrency/concurrent-ruby/blob/9c5b03af8661d74b37b371542a693f2bc6774dfc/lib/concurrent/channel/buffer/unbuffered.rb#L89). Flipping both channels in the example above to a capacity of 2 removes the deadlock.

Speaking of which, have you given thought to potentially adding in deadlock detection?

**Comment by kylewolfe** [comment]
Another issue which is probably related. Iterating over a channel that has nothing sent through it before being closed results in a deadlock.

```ruby
require 'concurrent-edge'
resp_chan = Concurrent::Channel.new
Concurrent::Channel.go {resp_chan.close}
resp_chan.each{|resp|}
puts "out of iteration"
```

**Comment by jdantonio** [comment]
Thank you! That's a huge help--now I know exactly where to look.

That's an excellent suggestion regarding deadlock detection. This channel implementation is very raw. I started working on it as I was learning Go for fun. It's a long way from being production ready. Please keep the feedback and suggestions coming! It's much appreciated.

**Comment by kylewolfe** [comment]
After trying to use https://github.com/igrigorik/agent (I believe they have proper deadlock detection, straight from the standard thread package?) and finding that it also does not satisfy correct behavior, I gave a little more thought to this issue.

Keep in mind that I have no experience developing a library that enables concurrency, only experience in building concurrent applications, so take with a grain of salt:

The features above are themselves concurrent. Given the following:

```ruby
def take
    synchronize do
        # return if closed
        # rest of magic...
    end
end
```

~~A deadlock will occur if a channel is closed after a go routine that called take has passed the 'return if closed' line. This can be solved by using a concurrent switch.~~

Actually, the problem is that the first 'take' operation already has exclusive access to the resource, preventing the other go routine from closing it.

```ruby
def take # new public take
    Channel.select do |s|
        # use private and primitive take for communication of closed channel
        s.take(closed) { |c| return nil } # return on closed channel
        s.take() { |v|
           synchronize {
              // get next item from queue
              return v
           }
    end
end
```

So, in closing. A primitive support for channels and switching is needed that is guaranteed to never close through he life of the Channel class existence. A public facing Channel class will implement this primitive channel in order to provide concurrent reads, preventing a deadlock.

Please let me know if my idea needs cleared up / more explanation.

**Comment by jdantonio** [comment]
Thanks for the clarification. What you say makes sense. I'll work on this later in the week. I think we can solve this.

**Comment by jdantonio** [comment]
See #501. We may adopt a new channel implementation soon.

**Comment by jdantonio** [comment]
Channels need to be re-built from the ground up, if we even want to have them at all. Since there doesn't seem to be a strong desire from the community at this time I'm going to close this issue. We'll revisit if necessary.
