### ISSUE TITLE
check-then-set race condition in Concurrent::Map#fetch_or_store

### ISSUE THREAD

**Issue by tenderlove** [ruby-concurrency/concurrent-ruby#512]
I couldn't find any documentation about the safety expectations for this method, but I assumed it would be thread safe so I'm filing this ticket.  It seems that `fetch_or_store` [doesn't take out a lock in the case of a miss](https://github.com/ruby-concurrency/concurrent-ruby/blob/01911e899c05ca3d68f65ef4496f3e29b3a20f4d/lib/concurrent/map.rb#L88).  As a client of the library, am I expected to lock and recked the map inside the block?  I don't mind adding a lock, but I think the expectations should be documented (if that's the case).

Here's a demo script to show what I mean:

```ruby
require 'concurrent/map'
require 'concurrent/atomic/cyclic_barrier'

map     = Concurrent::Map.new
barrier = Concurrent::CyclicBarrier.new 20
pool    = 20.times.map {
  Thread.new {
    barrier.wait
    map.fetch_or_store("test") do
      puts "OMGOMG"
      10
    end
  }
}.each(&:join)
```

The block will get yielded to a random number of times.

Thanks!

**Comment by Ch4s3** [comment]
The map implementation takes out a lock if I'm not mistaken. If that's the case it seems like `fetch_or_store` should as well. Or, is there a case where it's better to handle that yourself?

**Comment by tenderlove** [comment]
> Or, is there a case where it's better to handle that yourself?

I don't think so, and I'd rather not! ;)

**Comment by jdantonio** [comment]
Pinging original implementer @thedarkone, but it seems to me that the method should set the lock itself.

**Comment by jdantonio** [comment]
It appears that the original implementation in `thread_safe` [does not lock the method call](https://github.com/ruby-concurrency/thread_safe/blob/master/lib/thread_safe/cache.rb#L64) either.

**Comment by ianks** [comment]
Yes it seems `yield(key) ...` is being evaluated before the `@write_lock` is acquired in the `MapBackend`. The actually writing to the map though (in this case, writing `10`) is completely safe. 

## Pros

- Writes to the map have no sequential bottleneck besides writing the final evaluated output of the block.
- Less locking

## Cons

- Confusing API -- if you consider a block to be an atomic computation, much like you would treat a normal object, you will get unexpected race conditions like @tenderlove.
- The problem with locking the entire block is that it becomes incredibly easy to create sequential bottlenecks in the code
- It potentially becomes easier to deadlock the code

**Comment by ianks** [comment]
IMO, I think `Map` is better suited for low-level interaction of writing values, and not as a concurrency pattern for ensuring thread-safety of computations.

**Comment by thedarkone** [comment]
@tenderlove sorry about the docs, `fetch_or_store` is not meant to be an atomic check-then-set` method, neither is `fetch`.

History of `fetch_or_store` https://github.com/headius/thread_safe/issues/45, then https://github.com/ruby-concurrency/thread_safe/issues/1.

**Comment by thedarkone** [comment]
I now realize I messed up really badly with a `fetch_or_store` as it does read as a check-then-set method :disappointed:.

**Comment by jdantonio** [comment]
@thedarkone What's the resolution? Should we call this a bug and change the method or should be update the docs?

**Comment by thedarkone** [comment]
@Ch4s3 @ianks `TS::Map` does provide a complex set of check-then-set methods:
 * `put_if_absent`, `replace_pair`, `replace_if_exists`, `delete_pair`,
 * and a block taking methods, where an atomic execution for the block (for a given key) is guaranteed: `compute_if_absent`, `compute_if_present`, `compute`, `merge_pair`
 * these methods also provide certain check-then-set guarantees: `get_and_set`, `delete` (ie if multiple threads are attempting to delete a key, only one will succeed - the return value tells that particular thread whether it won or lost the race).

All of the methods mentioned above allow `TS::Map` to be use as a concurrency primitive with strong happens-before guarantees, [this is also extensively tested and verified](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/spec/concurrent/thread_safe/map_loops_spec.rb), it is also a use case that I had in mind.

@jdantonio I think the naming is unfortunate, however the fact that a method is not atomic is also a part of an API, that some users might be relying on. The absolutely most correct course of action is to update the docs and leave the implementation intact, however it is very unlikely that anybody is relying on the non-atomicity, so this might give us a chance to fix it (the fix might introduce an inconsistency: `fetch` is not atomic, however `fetch_or_store` is)?

**Comment by tenderlove** [comment]
> sorry about the docs, fetch_or_store is not meant to be an atomic check-then-set method, neither is fetch

No problem!  I wouldn't expect the block to `fetch` to be atomic since you're doing a read operation, but I would expect `fetch_or_store` to be atomic.  Or, I could reword this ticket to be a feature request that we have an atomic `fetch_or_store` method :smile: 

> Easier to create sequential bottlenecks in the code

I think this is true, but if you only lock on write, it *should* be fine, I think.  I think you could have something like this:

```ruby
class MyMap
  def initialize
    super
    @hash = {}
    @write_lock = Mutex.new
  end

  def fetch_or_store(key)
    @hash.fetch(key) do
      @write_lock.synchronize do
        @hash.fetch(key) do
          @hash[key] = yield
        end
      end
    end
  end
end
```



> Should we call this a bug and change the method or should be update the docs?

I'm fine calling this a bug, but I'd turn it in to a feature request.  :wink:  [Here is a real use case](https://github.com/rails/rails/blob/ac317e778a959468ef07779a4959ad49e8e9bbd6/actionview/lib/action_view/digestor.rb#L32-L36) where we have to do our own locking.  I thought "surely `Concurrent::Map` already has a method to handle this" (note that this method is recursive so a Mutex would result in a dead lock which is why it has the monitor, but I am removing the recursion)

**Comment by tenderlove** [comment]
> The absolutely most correct course of action is to update the docs and leave the implementation intact

I'd be perfectly happy with leaving this alone and getting a new method.

**Comment by thedarkone** [comment]
@tenderlove re your code snippet, it is not so simple. `TS::Map` on rbx and jruby uses multiple locks (for different internal hash buckets/bins, sometimes locks are not used, instead we rely on native CAS). The objective being that the atomic check-then-act methods/blocks are atomic, while at the same time mostly fully concurrent (for different keys that is, or for different hash buckets if we are to be completely honest :smiling_imp:).

However :exclamation:, none of the block taking check-then-act ops support recursion! This is due to internal constraints, that are very unlikely to change in the near future[1], otherwise you could simply replace `fetch_or_store(key) { compute_value }` with `compute_if_absent(key) { compute_value }`.

What I'm trying to say is, I don't think we can add a method you want, a global write lock is antithetical to the spirit of `TS::Map`...

PS: as the author of some of the parts of that `ActionView::Digestor` code, I don't see why would you want to change it!? It is beatiful :bowtie:. On a serious note, for concurrency code, it does look pretty normal to me.

------

[1] even if check-the-act methods were to become recurse-able, user could still trivially deadlock herself/himself:
 * thread a) `map.compute_if_absent(:foo) { map.compute_if_absent(:bar) {} }`
 * thread b) `map.compute_if_absent(:bar) { map.compute_if_absent(:foo) {} }`

**Comment by tenderlove** [comment]
Understood. Your arguments make sense to me. I'll write some docs for the
method for the next person who comes along and we can call this a day.
Thank you so much! :-D

**Comment by jdantonio** [comment]
So if I follow the conversation correctly we've decided to:

1. Keep the method as-is
1. Update the docs to better describe the current behavior.

Is this correct?

**Comment by tenderlove** [comment]
@jdantonio that's correct.  I'll send a PR with updated docs and close this
out.

**Comment by jdantonio** [comment]
I went through all the links post through the history of this issue and updated the yardoc to reflect atomicity and recursion. I'm happy to make further updates to the docs if anyone has better suggestions for the verbiage. The new docs are [here](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Map.html).
