### ISSUE TITLE
Cascaded promises evaluation

### ISSUE THREAD

**Issue by shaggyone** [ruby-concurrency/concurrent-ruby#517]
`Concurrent::Promise.execute { Concurrent::Promise.execute { 42 } }.value`
returns Promise object

i believe it should return 42

**Comment by jdantonio** [comment]
A `Promise` object is the correct return value for your code snippet. The internal promise has had not its value retrieved. In order to return 42 you must explicitly retrieve the return value of the inner promise:

```
Concurrent::Promise.execute { Concurrent::Promise.execute { 42 }.value }.value
```

**Comment by ianks** [comment]
Unless I am missing something, I believe the issue should be reopened. In ES6 JS, when returning a promise from inside a parent promise, the child promise should become the new promise which is evaluated. This is one of the main benefits of promises as it allows you to flatten out nested promises callbacks.

**Comment by jdantonio** [comment]
That's ES6. Our promises were *inspired* by JavaScript's Promises/A and Promises/A+ specification, as well as promises in other languages, but we've never intended or committed to implementing any particular specification (especially ES6 which wasn't finalized when we created our promises). One of the main issues is that JavaScript is a *very* different language with a *very* different runtime and *very* different asynchronous characteristics. Everything in this library is intended to reflect the Ruby language. Thus nothing in this library is exactly like the features of other languages which inspired us. The behavior of `Promise` is consistent with the other tools in this library and makes sense for Ruby.

**Comment by shaggyone** [comment]
There is still a need to get everything finished. Common case:

```
download_all_chunks_promise = download_playlist_promise.then do |chunks|
   Promise.zip(*chunks.map do |chunk|
      download_chunk_promise
   end)
end
```

My common need here is to get every chunk downloaded in `both` then and `value`.

Currently I have to use `value` right after `zip` which is ugly and easy to miss.

Maybe you could add some kind of deep_value and deep_then methods, to provide this functionality.

**Comment by jdantonio** [comment]
It's important to remember that `#value` isn't the only method that can be called on a completing promise. There is also `#wait` and `#reason`. Plus, these methods all take optional timeout arguments which will prevent a promise from potentially blocking forever. If we start providing special case variations of one then we have to create special case variations of the others and the API, which is huge already, will just get larger and messier. Requiring the user to call `#value` is consistent and [explicit](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/CONTRIBUTING.md#follow-the-guidelines).

**Comment by pitr-ch** [comment]
Just a side note: Edge api looks as follows: `Concurrent.future { Concurrent.future { 42 } }.flat.value` with an advantage of not blocking an extra thread for the inner value call, since `flat` has non-blocking implementation.
