### ISSUE TITLE
Concurrent::Promise.all? always returns nil

### ISSUE THREAD

**Issue by shaggyone** [ruby-concurrency/concurrent-ruby#518]
```
Concurrent::Promise.all?(
 Concurrent::Promise.execute { 2 },
 Concurrent::Promise.execute { 3 }
).execute.value
=> nil
```

Expected value is true

**Comment by jdantonio** [comment]
That's not how the `#all?` method works. The aggregation methods don't return a value, they [execute a chained handler method](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Promise.html#any%3F-class_method) based on the aggregate success or failure.

This success case:

```ruby
Concurrent::Promise.all?(
 Concurrent::Promise.new { 2 },
 Concurrent::Promise.new { 3 }
).then{ puts "Succeeded" }.
  rescue{ |reason| puts "Failed with #{reason}" }.execute
```

will output "Succeeded" to the console.

This failure case:

```ruby
Concurrent::Promise.all?(
 Concurrent::Promise.new { raise StandardError },
 Concurrent::Promise.new { 3 }
).then{ puts "Succeeded" }.
  rescue{ |reason| puts "Failed with #{reason}" }.execute
```

will output "Failed with Concurrent::PromiseExecutionError" to the console.

The original conversations about this API and why they work this way can be found [here](https://github.com/ruby-concurrency/concurrent-ruby/issues/80) and [here](https://github.com/ruby-concurrency/concurrent-ruby/pull/198).

**Comment by tomascharad** [comment]
HI @jdantonio ,

The javascript implementation of Promise.all does actually return an array with the results of each fulfilled promise, if you provide this array, the promise.all function is almost useless IMHO.

**Comment by pitr-ch** [comment]
Yeah i've missed that completely in the old discussions about this API. I assumed it passes the values to the block. I agree it limits the usability. New implementation of promises which is almost ready, just API renaming in progress, passes the values as expected.

**Comment by tomascharad** [comment]
Thanks @pitr-ch ,

Is there any way how to try that alpha version?

**Comment by pitr-ch** [comment]
it is available in concurrent-ruby-edge see http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Edge/FutureShortcuts.html for documentation. But please be warned that even though the internals will stay the same, the names and namespace will be changing in the next release. If you have feedback about the new implementation we will appreciate it.

If you wish to live beyond edge you can try https://github.com/ruby-concurrency/concurrent-ruby/pull/522 :)

**Comment by tomascharad** [comment]
Many thanks @pitr-ch , I'll try that tomorrow and will let you know.

**Comment by tomascharad** [comment]
Hi @pitr-ch ,

I just updated to: 
```ruby
# TCT: Concurrency
gem 'concurrent-ruby', '~> 1.0.3.pre3'
gem 'concurrent-ruby-edge', '~> 0.2.3.pre3'
```

But it doesn't ```Concurrent::Promise.all?```still doesn't seem to return the responses.
I'm doing:
```ruby
promises = attachments_with_content.map do |attachment|
  promise = Concurrent::Promise.new{
    pdf = foliator.foliate(attachment.content.url, attachment.initial_folio, Date.new.to_s, false, false, 0)
    pdf
  }.execute
  promise
end

all_promises = Concurrent::Promise.all?(*promises)
all_promises.then{ |reponses|
  puts 'Here!'
  puts 'Hereaaaa!'
  puts responses
  ...
end
sleep(15)
puts puts all_promises.state
```
And my console just prints 
```bash
Here!
Hereaaaa!
fulfilled
```

**Comment by tomascharad** [comment]
Hi @pitr-ch ,

I just updated to: 
```ruby
# TCT: Concurrency
gem 'concurrent-ruby', '~> 1.0.3.pre3'
gem 'concurrent-ruby-edge', '~> 0.2.3.pre3'
```

But ```Concurrent::Promise.all?```still doesn't seem to return the responses.
I'm doing:
```ruby
promises = attachments_with_content.map do |attachment|
  promise = Concurrent::Promise.new{
    pdf = foliator.foliate(attachment.content.url, attachment.initial_folio, Date.new.to_s, false, false, 0)
    pdf
  }.execute
  promise
end

all_promises = Concurrent::Promise.all?(*promises)
all_promises.then{ |responses|
  puts 'Here!'
  puts 'Hereaaaa!'
  puts responses
  ...
end
sleep(15)
puts puts all_promises.state
```
And my console just prints 
```bash
Here!
Hereaaaa!

fulfilled
```

**Comment by tomascharad** [comment]
Hi @pitr-ch ,

I also tried using:
```ruby
gem 'concurrent-ruby', :git => "git@github.com:pitr-ch/concurrent-ruby.git", :branch => "futures"
```
Without the edge gem and requiring
```ruby
require 'concurrent'
```
But I the responses object still seem to be null:
```bash
Here!
Hereaaaa!

fulfilled
```

**Comment by tomascharad** [comment]
HI @pitr-ch ,

Just if it worths for something, I wrote the following implementation of Promise.all, based on concurrency-ruby promises:

```ruby
def self.all_promises? promises
  results = [];
  merged = promises.inject do |acc, p|
    prom = acc.then{p}.then{|r| results.append(r)}
    prom
  end
  merged.then{results}
  return merged
end
```

**Comment by pitr-ch** [comment]
Ah, the old Promise implementation. is still used in your example. The new promises are created differently, please have look at the documentation which was linked earlier. Requiring the edge does not change the old API.
