### ISSUE TITLE
TimerTask timeout_interval unused

### ISSUE THREAD

**Issue by lmarburger** [ruby-concurrency/concurrent-ruby#525]
`#timeout_task` is [executed using `execution_interval`](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/timer_task.rb#L308). Should it use `timeout_interval`?

``` ruby
def execute_task(completion)
  return nil unless @running.true?
  ScheduledTask.execute(execution_interval, args: [completion], &method(:timeout_task))
  _success, value, reason = @executor.execute(self)
```

I'm exploring the specs to see if I can expose this feature. In the mean time I thought it wise to confirm that it is, in fact, a bug.

**Comment by jdantonio** [comment]
I think the original code is correct. The `execution_interval` represents the number of seconds between each execution of the task. The `timeout_interval` is the number of seconds that the task can run without completion before a timeout error is issued. In the code above, the first parameter to `ScheduledTask.execute` is the `delay` value--the number of seconds after calling `.execute` that the task is to be executed. So the `execution_interval` is the correct value.

I'm out of town attending a conference so I haven't run the code in your branch, I've only looked at the code. There may be a bug elsewhere if you are seeing aberrant behavior.

**Comment by pitr-ch** [comment]
This needs to be fixed, I'll have look. Another related issue reported in #526.
