### ISSUE TITLE
Can not Install

### ISSUE THREAD

**Issue by qx** [ruby-concurrency/concurrent-ruby#531]
Error installing concurrent-ruby:
        invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Users/ok/.rvm/gems/ruby-2.2.3@rails426/cache/concurrent-ruby-1.0.2.gem

**Comment by pitr-ch** [comment]
Did you try to delete the cache and install again? It installs fine for me. What system are you on?

**Comment by qx** [comment]
didn't know why, but it works sometimes.
