### ISSUE TITLE
Questions about Concurrent::Edge::Future

### ISSUE THREAD

**Issue by pathsny** [ruby-concurrency/concurrent-ruby#535]
1. When I create futures that are on a threadpool that results in them being queued up, is there a way to query the future to distinguish between futures that are started vs futures that have not been scheduled?
2. Following from #1, is there a way to cancel a future or remove it from the pool?
3. The documentation claims that Edge Futures are a combination of "Future, Promise, IVar, Event, dataflow, Delay, and TimerTask". However, I'm unable to figure out how to use a Future as a Periodic TimerTask.

**Comment by pitr-ch** [comment]
Was answered in https://gitter.im/ruby-concurrency/concurrent-ruby?at=575765dfc2a6e42f7e995477
