### ISSUE TITLE
Concurrent version of Array

### ISSUE THREAD

**Issue by bk322** [ruby-concurrency/concurrent-ruby#537]
I read that `concurrent-ruby` has made Array thread-safe. I wanted to give it a try with the code from [this blog post](http://deployingjruby.blogspot.ru/2013/07/why-jruby-arrays-are-not-threadsafe.html):

```ruby
#!/usr/bin/env jruby

require 'concurrent'

data = []
threads = []
100.times do |m|
  threads << Thread.new do
    100.times do |n|
      data << m * n
    end
  end
end

threads.map(&:join)
puts "size => #{data.size}"
```

This creates 100 threads each of which writes to a single array in a loop.

If all is thread-safe here one should obtain `10000` as a result. However I get lower results instead:

```
$ ./threads.rb 
size => 9945
$ ./threads.rb 
size => 9998
$ ./threads.rb 
size => 9998
```

Does it mean that concurrent-ruby patched Array is not thread-safe? Or it is thread safe because in none of my tests I get corrupted data, where as "my" code thread-safety is not something a language can guarantee?

(I've used java 1.8, jruby-9.1.1.0, and latest concurrent-ruby)

**Comment by jdantonio** [comment]
Your code does not use our thread-safe array. You are still using the standard library array. As a rule we [never monkey patch Ruby](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/CONTRIBUTING.md#follow-the-guidelines), we create new classes for everything. Please update your code to use [Concurrent::Array](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Array.html) and you should see the expected results.

```
require 'concurrent'

data = Concurrent::Array.new
threads = Concurrent::Array.new
100.times do |m|
  threads << Thread.new do
    100.times do |n|
      data << m * n
    end
  end
end

threads.map(&:join)
puts "size => #{data.size}"
```
