### ISSUE TITLE
Concurrent and Thread

### ISSUE THREAD

**Issue by majioa** [ruby-concurrency/concurrent-ruby#538]
The main question is that:

Still we required to use `Thread` classes inside, for example, the `Concurrent::FixedThreadPool` pool

    pool = Concurrent::FixedThreadPool.new(pool_count)
    r = Concurrent::Future.new(executor: pool) { 
      Thread.new #???
    }.execute

or not?

**Comment by pitr-ch** [comment]
Could you elaborate the example? The example above will work but is strange and not recommended. It'll just post a task to a pool to create a new thread, neither is doing any useful work so it's hard to tell why would you need to combine concurrent with threads.

**Comment by majioa** [comment]
My current sample is without the `Thread` and is like:

    pool = Concurrent::FixedThreadPool.new(pool_count)
    r = Concurrent::Future.new(executor: pool) { 
      # list enum with ftp download a single file in list
    }.execute

**Comment by pitr-ch** [comment]
That seems fine.

**Comment by majioa** [comment]
thanx

**Comment by majioa** [comment]
@pitr-ch one yet question. In the example above, will the single future be separated to threads count specified by `pool_count`, or should we fill the pool block with many futures to support many tasks?

**Comment by pitr-ch** [comment]
If I understand correctly your question. It should look like:
```ruby
files_to_download = [#...
]
pool = Concurrent::FixedThreadPool.new(pool_count)
futures = files_to_download.map do |file| 
  Concurrent::Future.new(executor: pool) { download file }.execute
end
```

**Comment by jdantonio** [comment]
Creating a thread pool manually is unnecessary. The default global thread pool will grow as necessary to support the tasks it's given. Don't give an "executor" option and the futures will post to the global thread pool. The recommended approach is to not create custom thread pools. After all, this is Ruby, not Java. :-)
