### ISSUE TITLE
2.0 Guiding Principles

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#541]
While designing and working on concurrent-ruby 2.0 we will endeavor, as much as possible, to follow these guidelines. They are not hard rules, however. Compromises will be made when necessary, but only after discussion and deliberation. These guidelines do not replace the existing [contribution guidelines](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/CONTRIBUTING.md#follow-the-guidelines). They are extensions and clarifications of those guidelines specific to 2.0 development.
- **User experience first:** A library is only of value if programmers use it. To be successful we must [value our user's above all else](http://www.riotgames.com/riot-manifesto#1). Ruby is designed to [make programmers happy](http://www.artima.com/intv/rubyP.html) so Concurrent Ruby will be designed to make programmers happy.
- **Simplicity:** Concurrency is complex. Our job is to make it as simple as possible. Our APIs will be as simple as we can make them, providing reasonable defaults. We will name things with simple terms so that they can be easily understood. Advanced features needed only by a small number of users will be provided as options, if at all.
- **Consistency:** Our users will be more productive more quickly if we minimize the number of things they need to learn. We will define a core API and nomenclature that we will use across the library as much as possible. We will stray from this core only when absolutely necessary.
- **Idiomatic:** Concurrent Ruby is Ruby, not Java, C#, C++, Clojure, Scala, Erlang, etc. We will draw inspiration from other languages but we will remain a Ruby library written for Rubyists by Rubyists. Whenever possible we will adhere to the conventions and idioms of the Ruby standard library and to the reasonable expectations of our users.
- **Reasonably performant:** We will endeavor to make concurrent-ruby as performant as possible, but _not_ at the expense of our other principles. Ruby is a dynamic, interpreted language. It will always be slower than many other languages. The most common use for concurrent-ruby is to unblock I/O. In many cases a few lost processor cycles won't make a difference. We will benchmark our code and do whatever is reasonable to improve performance when possible, not we will happily sacrifice a little bit of performance if it provides a better, simpler, idiomatic, and more consistent developer experience.

**Comment by pitr-ch** [comment]
* **User experience first:** 👍 💯
* **Simplicity:** 👍 I completely agree except the last part. Regarding: "Advanced features needed only by a small number of users will be provided as options, if at all." I've been several times in a situation when I wanted to do something in a programming language or with a library and I couldn't because authors thought that it's too complicated, unsafe or other reason for their users. I would rather not do that to our users. If some feature/method/option is identified as advanced I propose different approach to removing it, it can be marked as advanced and possibly hidden from the main documentation. That keeps the simplicity but does not take away any power features.
* **Consistency:** 👍 💯 Do you have any examples in mind?
* **Idiomatic:** 👍 💯 (Note: I see Simplicity and Consistency as more important, than idiomatic. Following idiomatic too strongly may result in copying past mistakes.)
* **Reasonably performant:** 👍 In general I agree, just few comments. "Ruby is a dynamic, interpreted language. It will always be slower than many other languages." Not necessarily true, JRuby+Truffle has potential to meet the performance of V8 and other compiled languages, see https://github.com/smarr/are-we-fast-yet/blob/master/docs/performance.md. JRuby(+Truffle) can be used for CPU heavy tasks, we should think about that too not just I/O.

These are really good points, thanks for putting it together Jerry.

I would maybe add **Documentation** here as well, see #542. 
When done, it would be good to have it in README.

**Comment by pitr-ch** [comment]
We should also discuss aliasing as a part of **Simplicity**:
1. do aliasing, anybody can use familiar name
2. do aliasing, but have them only to make the function more familiar with naming from other language/library (these hinting alias could be deprecated from beginning but never removed)
3. keep just one name

I am inclined to 2. possibly 3.

**Comment by jdantonio** [comment]
Good point on aliasing. I'm working on responses and updates which I will post later.

**Comment by jdantonio** [comment]
I will post more as the week progresses but I am on vacation with my family this week. My posts yesterday were made from my phone during the 5-hour car ride. My posts today were written while in the car yesterday. For the remainder of the week my top priority will be spending time with my family. I will post here as I have time.

Additional clarification to this post:

* **Simplicity:** If an advanced feature becomes unwieldy we will decided on a case-by-case basis. Removal will be the final choice if and only if it's absolutely necessary, but removal will be a possibility. We will not allow the library to be ruled by edge cases.
* **Consistency:** The `Obligation` modules is a good example. By having all "future" abstractions include that module we were able to provide a consistent API. The current discussion about a common API for the atomic classes is another example. We don't have to enforce this consistency through modules like `Obligation`, however. We can enforce it through shared specs and documentation. (I'll discuss removal of `Obligation` in the other thread.) I am working on several more posts to discuss various consistent APIs that I want us to work toward. I will post each as I complete them.
* **Idiomatic:** All of these guidelines are of equal importance. Should situations arise where these guidelines are in conflict with one another we will make decisions on a case-by-case basis.
* **Reasonably performant:** The potential of JRuby+Truffle isn't in question, but it isn't relevant.
  1. It hasn't reached that level of performance yet.
  2. V8 is still less performant than compiled languages like C++.
  3. The _vast_ majority of Rubyists use MRI, not JRuby.
  4. Rubyists choose Ruby because of developer happiness and productivity. Rubyists have always been willing to sacrifice performance for productivity and happiness.
  5. We should _always_ think about performance, but we should _never_ let performance override our other priorities, principles, and values. (C++ has been dong that since its inception and it's a horrible mess of a language that is painful to work with.)

**Comment by iNecas** [comment]
* **Reasonable performant** - from the very beginning, what I liked about concurrent Ruby was it tried to use the potential of the platform it was currently running on and hiding it behind the abstraction. It's easier to sacrifice performance if you know that there is a way to run faster just by changing platform, not the language. This leads to another idea:

* **Extendability** - making it easier to provide a custom implementation to a given abstration: the JRuby and others would be one example of custom implementation of abstraction. I realize however, that trying to achieve has it's downsides that I'm not sure c-r team wants to get in. Still worth asking IMO.

**Comment by jdantonio** [comment]
@inecas Good point. "Optimized for each platform when possible" has always been one of our goals. I'll add something about that.

**Comment by pitr-ch** [comment]
> * **Simplicity:** If an advanced feature becomes unwieldy we will decided on a case-by-case basis. Removal will be the final choice if and only if it's absolutely necessary, but removal will be a possibility. We will not allow the library to be ruled by edge cases.

Unwieldy as a reason sounds good. Sorry I've got a wrong the impression that we will be removing things just for simplicity's sake. 

> * **Consistency:** The `Obligation` modules is a good example. By having all "future" abstractions include that module we were able to provide a consistent API. The current discussion about a common API for the atomic classes is another example. We don't have to enforce this consistency through modules like `Obligation`, however. We can enforce it through shared specs and documentation. (I'll discuss removal of `Obligation` in the other thread.) I am working on several more posts to discuss various consistent APIs that I want us to work toward. I will post each as I complete them.

Thanks, sounds good. Having also modules on top of tests when possible is good, it allows asking about it `AnInterface === object`.

**Comment by chrisseaton** [comment]
A lot of time's passed. We'll re-evaluate what we want from 2.0 in the future.
