### ISSUE TITLE
2.0 Promise API

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#543]
## 2.0 Promise API

The original `Concurrent::Promise` implementation was one of the first abstractions created in this library. It was intended to be a faithful implementation of the Promises/A and Promises/A+ specifications. Because the JavaScript runtime is very different than Ruby's, there were obvious differences. But overall the implementation worked. People used it and it became a guiding influence on `Concurrent::IVar`, `Concurrent::Future`, and `Concurrent::ScheduledTask`.

In the intervening years the use of promises in JavaScript has become mainstream. The use of JavaScript continues to grow at an amazing pace and it has started to influence other languages. Many languages now include promises or promise-like abstractions. Recently ES6 formally adopted a promise specification, finally uniting the JavaScript community.

Since most Ruby developers are also JavaScript developers we've seen that our users have a strong understanding of promises. This has also lead to reasonable expectations regarding terminology and behavior.

_The Ruby runtime is very different from the JavaScript runtime. Promises in Concurrent Ruby will never behave exactly like JavaScript promises._

That being said, it is reasonable for us to use JavaScript as our primary influence whenever possible. This is better for our users who already understand promises, but it is also consistent with our 1.0 version and the history of our implementation.

The ESC standard for promises defines three possible states for a promise. Quoting the documentation:

> A Promise is in one of these states:
> - pending: initial state, not fulfilled or rejected.
> - fulfilled: meaning that the operation completed successfully.
> - rejected: meaning that the operation failed.

These three states comprise the full lifecycle of a promise in both JavaScript and Concurrent Ruby. They are also the three states of our original promise implementation. We have added additional states since then, but these states have all been variants of these three.

In Concurrent Ruby 2.0 we will return to these three states.
- Every promise or promise-like abstraction (Promise, Future, IVar, and ScheduledTask at a minimum) will support this API.
- The primary method for querying state will be a set of predicate methods matching these states (`#pending?`, `#fulfilled?`, `#rejected?`). One of these methods will _always_ return true, and the other two will _always_ return false.
- Additional states may be added when necessary, but these states will each be a refinement of one of the other states. For example, if a cancel operation is added to an abstraction we may need to add a "cancelled" state and predicate. The cancelled state will be a refinement to rejected. When the operation is cancelled it will also be rejected. Similarly, unscheduled would be a refinement to pending.

The API will also support methods for changing the state of a pending future. The same method names will be used for factory methods which create promises in states other than pending.
- The `#reject` method will be used to reject a promise.
- Strangely, JavaScript chose to have a `#resolve` method for fulfilling a promise, rather than a `#fulfill` method. This grammatical inconsistency in unfortunate, but it's in the specification. Subsequently this library will support `#resolve`. A `fulfill` alias will be considered.

When an abstraction in this library supports chained evaluation, the JavaScript standard will be followed for both successful and unsuccessful evaluation.
- JavaScript promises have a `#then` method for chaining. Promises in this library have always had a `#then` method as well. A `#then` will be used on all abstractions that support chained evaluation.
- JavaScript promises have a `#catch` method for error handling. Promises in this library have always had a `#rescue` method for this purpose. This was a mistake. The word `rescue` was chosen because it was consistent with Ruby's error handling. But this has caused confusion instead. Promises in this library have always had a `#catch` alias for `#rescue`. The `#rescue` method will be deprecated and the `#catch` alias will become the error handling function.

JavaScript promises do not have an intrinsic value, they only support callbacks. Ruby's runtime easily supports promises which have a value on completion. And often this is the preferred use. The existing API will be retained.
- The `#value` method will return the value of a fulfilled promise. Nil is a valid value for a fulfilled promise. When a promise is pending or rejected the `#value` method will return nil.
- The `#reason` method will return an Error object when a promise has been rejected. It will return nil when the promise if pending or fulfilled.

The promises in this library have always supported optional timeout values for `#value` and `#reason` as well as a generic `#wait`. It is likely that these methods and their `!` counterparts will remain unchanged. Some thought is needed. These methods should be consistent with similar methods on other abstractions.

See also:
- [MDN > Mozilla > JavaScript code modules >Promise.jsm > Promise](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise)
- [MDN >Web technology for developers > JavaScript > JavaScript reference > Standard built-in objects > Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

**Comment by pitr-ch** [comment]
> The original `Concurrent::Promise` implementation was one of the first abstractions created in this library. It was intended to be a faithful implementation of the Promises/A and Promises/A+ specifications. Because the JavaScript runtime is very different than Ruby's, there were obvious differences. But overall the implementation worked. People used it and it became a guiding influence on `Concurrent::IVar`, `Concurrent::Future`, and `Concurrent::ScheduledTask`.

> In the intervening years the use of promises in JavaScript has become mainstream. The use of JavaScript continues to grow at an amazing pace and it has started to influence other languages. Many languages now include promises or promise-like abstractions. Recently ES6 formally adopted a promise specification, finally uniting the JavaScript community.

> Since most Ruby developers are also JavaScript developers we've seen that our users have a strong understanding of promises. This has also lead to reasonable expectations regarding terminology and behavior.

> *The Ruby runtime is very different from the JavaScript runtime. Promises in Concurrent Ruby will never behave exactly like JavaScript promises.*

> That being said, it is reasonable for us to use JavaScript as our primary influence whenever possible. This is better for our users who already understand promises, but it is also consistent with our 1.0 version and the history of our implementation.

In contrast to that the new Promises were developed independently taking inspirations from many different similar libraries and adding new ideas. I do not want to shape it based on any particular implementation and I want to keep freedom to make best decisions for the abstraction and its users. This implementation is not js promises. However renaming few methods to pursue familiarity makes sense as long it does not make the API worse or ambiguous. 

> The ESC standard for promises defines three possible states for a promise. Quoting the documentation:

> >A Promise is in one of these states:
> >
> > * pending: initial state, not fulfilled or rejected.
> > * fulfilled: meaning that the operation completed successfully.
> > * rejected: meaning that the operation failed.

> These three states comprise the full lifecycle of a promise in both JavaScript and Concurrent Ruby. They are also the three states of our original promise implementation. We have added additional states since then, but these states have all been variants of these three.

Yeah we agreed on these names.

> In Concurrent Ruby 2.0 we will return to these three states.

> * Every promise or promise-like abstraction (Promise, Future, IVar, and ScheduledTask at a minimum) will support this API.

If the new promises are accepted as replacement, the all listed above are replaced, there is just Future and Event. 

> * The primary method for querying state will be a set of predicate methods matching these states (`#pending?`, `#fulfilled?`, `#rejected?`). One of these methods will _always_ return true, and the other two will _always_ return false.

Current new promises also have completed? which is success? || failed?. Event has only completed? since it does not have any value or reason. Completed will be named resolved.

> * Additional states may be added when necessary, but these states will each be a refinement of one of the other states. For example, if a cancel operation is added to an abstraction we may need to add a "cancelled" state and predicate. The cancelled state will be a refinement to rejected. When the operation is cancelled it will also be rejected. Similarly, unscheduled would be a refinement to pending.

It is better not to complicate the abstraction further with extra states. Cancellation is better implemented orthogonal to promises, see the prototype in the promises branch. The cooperative cancellation works with any abstraction. Unscheduled can be also implemented externally, simplest implementation would be the task flipping a boolean flag before it begins.

> The API will also support methods for changing the state of a pending future. The same method names will be used for factory methods which create promises in states other than pending.

yes, see the Promises::FactoryMethods (just translate old names to new ones).

> * The `#reject` method will be used to reject a promise.
> * Strangely, JavaScript chose to have a `#resolve` method for fulfilling a promise, rather than a `#fulfill` method. This grammatical inconsistency in unfortunate, but it's in the specification. Subsequently this library will support `#resolve`. A `fulfill` alias will be considered.

The `resolve` has more general name then just fulfill because it behaves differently based on the argument. It can reject the newly constructed promise if the argument is promise (or then-able). The new promises are more explicit It roughly maps to: `Promises.fulfilled_future(value)`, `Promises.resolved_future(is_fullfilled, value, reason)`, `promise.then {|p| p}`. It points out missing API in the new implementation. I'll add a general factory method `create` which will behave based on it's argument type, keeping the explicit factory methods as well. Let's discuss details over the actual implementation after I rename the states and derived method names.

> When an abstraction in this library supports chained evaluation, the JavaScript standard will be followed for both successful and unsuccessful evaluation.

> * JavaScript promises have a `#then` method for chaining. Promises in this library have always had a `#then` method as well. A `#then` will be used on all abstractions that support chained evaluation.

Rather then implementing then on other abstractions is better use composition if possible and use existing class Future/Event. Currently there are following chaining methods: chain, then, rescue.

> * JavaScript promises have a `#catch` method for error handling. Promises in this library have always had a `#rescue` method for this purpose. This was a mistake. The word `rescue` was chosen because it was consistent with Ruby's error handling. But this has caused confusion instead. Promises in this library have always had a `#catch` alias for `#rescue`. The `#rescue` method will be deprecated and the `#catch` alias will become the error handling function.

Catch collides with Ruby's catch, I think it's better to stick with rescue because it matches Ruby's rescue keyword. (possibly catch as deprecated alias, but it's better to keep one name).

> JavaScript promises do not have an intrinsic value, they only support callbacks. Ruby's runtime easily supports promises which have a value on completion. And often this is the preferred use. The existing API will be retained.

Yes, however chaining is preferred and the documentation warns about that.

> * The `#value` method will return the value of a fulfilled promise. Nil is a valid value for a fulfilled promise. When a promise is pending or rejected the `#value` method will return nil.
> * The `#reason` method will return an Error object when a promise has been rejected. It will return nil when the promise if pending or fulfilled.

Yes, current api is the same. There is also result method which returns a triplet of `success?, value, reason` and it blocks as rest of the methods reading value or reason.

> The promises in this library have always supported optional timeout values for `#value` and `#reason` as well as a generic `#wait`. It is likely that these methods and their `!` counterparts will remain unchanged. Some thought is needed. These methods should be consistent with similar methods on other abstractions.

Yes, current api is the same.

> See also:

> * [MDN > Mozilla > JavaScript code modules >Promise.jsm > Promise](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise)
> * [MDN >Web technology for developers > JavaScript > JavaScript reference > Standard built-in objects > Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

**Comment by jdantonio** [comment]
> I do not want to shape it based on any particular implementation and I want to keep freedom to make best decisions for the abstraction and its users. 

I agree, but "best decisions" is very subjective. There is value in familiarity. There is value in having abstractions behave the way [users expect](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). We can discuss "best decision" on a case-by-case basis.

> It is better not to complicate the abstraction further with extra states.

I agree. Better to have fewer states. If a new state is needed for any reason we should know in advance how to handle that. Hopefully new states won't be needed.

> Cancellation is better implemented orthogonal to promises

I agree.

> Catch collides with Ruby's catch, I think it's better to stick with rescue because it matches Ruby's rescue keyword.

I'm OK with this.

**Comment by pitr-ch** [comment]
Great, I think we've reached agreement. Please have look at https://github.com/ruby-concurrency/concurrent-ruby/pull/522, I would like to merge it after next patch release (1.0.3) in edge for people to try out. The API should be finalised before going out in edge so just minor changes are done if needed when it goes to core.
