### ISSUE TITLE
2.0 Async Operations API

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#544]
This is the area where we need far greater consistency. Various abstractions in this library use methods such as `#post`, `#ask`, `#tell`, `#send`, `#await`, and `#wait`. Additionally we have `!`, `?`, `_on`, and `_off` variants. As much as possible a common set of methods should be defined. Abstractions should then implement the relevant subset of these methods. When an abstraction needs a method not defined by the common spec the spec should be updated to describe that method. This way all abstractions always support a subset, none support a superset.

The `#post` method has been in this library longer than any of the others. We should give special consideration to this method.

For all methods, the following consistent rules should be followed:
- All async methods will support an `:executor` option for dependency injection.
- There will be no `_on` or `_off` variants. These exist to post to an alternate global thread pool. Since we are moving to a single global thread pool these variants no longer have meaning. The `:executor` option solves this problem.
- A `!` variant should exist. This variant will raise an exception. This will allow the programmer to engage Ruby's exception handling features.
- A variant method which returns a `Concurrent::Maybe` should exist. Ruby's idiom of returning nil for failure is a bad practice. Because it's an idiomatic and widespread practice it will continue to be supported by us, but we can also do better. Returning a `Concurrent::Maybe` is becoming a common practice in other languages so we will support it, too. One possibility is that the `?` variant method will return a `Concurrent::Maybe`. However this would go against the normal Ruby idiom of `?` predicate methods so we should give this some thought.

**Comment by pitr-ch** [comment]
> This is the area where we need far greater consistency. Various abstractions in this library use methods such as `#post`, `#ask`, `#tell`, `#send`, `#await`, and `#wait`. Additionally we have `!`, `?`, `_on`, and `_off` variants. As much as possible a common set of methods should be defined. Abstractions should then implement the relevant subset of these methods. When an abstraction needs a method not defined by the common spec the spec should be updated to describe that method. This way all abstractions always support a subset, none support a superset.

> The `#post` method has been in this library longer than any of the others. We should give special consideration to this method.

This is tricky, there are 2 competing points of view, both good. One is unification across the library, second is naming conventions and consistency within the abstraction. E.g. `ask` and `tell` are very good pair of names for actors, post and ask is not that good. Agent is a direct port of clojure agent and its names `send`, `send_off` and `await` are based on its naming.

I would put the internal abstraction conventions/consistency above unification across concurrent-ruby, which is a toolbox like gem even though we started trying to integrate things together.

> For all methods, the following consistent rules should be followed:

> * All async methods will support an `:executor` option for dependency injection.
> * There will be no `_on` or `_off` variants. These exist to post to an alternate global thread pool. Since we are moving to a single global thread pool these variants no longer have meaning. The `:executor` option solves this problem.

This depends on the discussion about global executors.

I've considered :executor option but I've settled for the `_on` (and `_using`) methods to perfectly disambiguate the executor option from arguments for the tasks. There is not way how to distinguish :executor key in last option hash between option for the task or for the method creating the task. For that reason I think we should keep `_on` suffix.

From implementation's point of view we are still 1.9 compatible so looking for a Hash with options in the end of args would be awkward.  

`_off` is agent specific I guess it depends on other things if it will be kept closer to clojure original or unified. If unified then `post` and `post_on` would be good choices.

> * A variant method which returns a `Concurrent::Maybe` should exist. Ruby's idiom of returning nil for failure is a bad practice. Because it's an idiomatic and widespread practice it will continue to be supported by us, but we can also do better. Returning a `Concurrent::Maybe` is becoming a common practice in other languages so we will support it, too. One possibility is that the `?` variant method will return a `Concurrent::Maybe`. However this would go against the normal Ruby idiom of `?` predicate methods so we should give this some thought.

I would look for other ways then '?' methods. Event though I like the concept it's quite out of scope of this gem. It should start in edge. Alternative to introducing Maybe, which is foreign in Ruby, options for value holding classes could be considered. The option would forbid nil values. But that also has nothing to do with Ruby concurrency. Maybe a gem extension?

**Comment by jdantonio** [comment]
> I would put the internal abstraction conventions/consistency above unification across concurrent-ruby

I agree. We should be consistent only when it makes sense.

> E.g. ask and tell are very good pair of names for actors, post and ask is not that good

Fair enough. What about 2 sets of baseline names? One ask/tell set and another set based on post? Each abstraction could then start with whichever baseline set matches best. We would still have consistency.

> Agent is a direct port of clojure

Certainly, but our implementation is still unique to concurrent-ruby. This is similar to the Promise discussion. We want our promises to behave in ways that are intuitive to JavaScript users but we are willing to make concessions/changes so that our Promises fit Ruby and this library. The same goes for agent and atom. They should behave in ways that are intuitive to Clojure programmers (NOTE: there are _far_, _far_ fewer Clojure programmers than JavaScript programmers) but, ultimately, those abstractions must fit Ruby and this library.

> though I like the concept it's quite out of scope of this gem

I disagree. There is nothing out of scope about this. Disambiguating between `nil` and a valid return value and `nil` because there was an error is a HUGE part of this gem. Providing a consistent and unambiguous way to do this is a definitely something we need to do. It's something we are already doing.

> I would look for other ways then '?' methods

I agree that `?` is not the best choice. I'm open to suggestions.

**Comment by pitr-ch** [comment]
> Fair enough. What about 2 sets of baseline names? One ask/tell set and another set based on post? Each abstraction could then start with whichever baseline set matches best. We would still have consistency.

Yeah lets try, sounds good, we'll se how it goes.

> ... agents naming ...

I think both clojure-based names or ruby-based names make sense. Please use what you think is best.

> I disagree. There is nothing out of scope about this. Disambiguating between nil and a valid return value and nil because there was an error is a HUGE part of this gem. Providing a consistent and unambiguous way to do this is a definitely something we need to do. It's something we are already doing.

I 100% agree that we should provide tools to disambiguate nil from errors always. And I think we do. (The new Promises API has explicit warnings in the documentation when the nil can be ambiguous). However the Maybe concept is foreign to Ruby which goes against goal of this gem to be Ruby idiomatic. That's the part I see as out-of-scope for core. It can only be an optional addition to the normal API not the main API. Therefore I am suggesting introduction through edge or other gem or through `require "concurrent/edge/maybe_apis"`.

> I agree that ? is not the best choice. I'm open to suggestions.

A prefix `maybe_` could be added to methods where it would make sense to duplicate them with maybe return value.

**Comment by chrisseaton** [comment]
A lot of time's passed. We'll re-evaluate what we want from 2.0 in the future.
