### ISSUE TITLE
100% CPU when blocked writing to a channel

### ISSUE THREAD

**Issue by bibstha** [ruby-concurrency/concurrent-ruby#563]
The code to test is available in this [gist](https://gist.github.com/bibstha/d24acbd892a892fd24ba5dc1a9aca4a2).
Basically if you write to a channel and that is blocked, it has a 100% cpu usage.

However, if I use `x = Concurrent::Channel.new(capacity: 1)`, it doesn't have the 100% cpu usage.

**Comment by jdantonio** [comment]
@bibstha Thank you very much for letting us know about this. I especially appreciate the gist with the sample code. Unfortunately I have to close this issue as unresolved. The current implementation of channels is strictly experimental and no where near production ready. It's being completely replaced by an entirely new implementation (PR #519). The new implementation has vastly different internals and should not have this problem. I have to focus my efforts on planning the 2.0 release and a few bugs in Core.
