### ISSUE TITLE
Unexpected warnings from MRI 2.3.x

### ISSUE THREAD

**Issue by jrochkind** [ruby-concurrency/concurrent-ruby#566]
I just started noticing a whole bunch of warnings in output from concurrent-ruby. 

I wondered if it was a new version of concurrent-ruby, but was able to reproduce down to 1.0.0. Did I just not notice before?  Or is it MRI version?

Not sure but, it seems bad. I have a whole bunch of warnings from several different source lines, but here's one I was able to make a relatively simple repro for. 

MRI 2.3.1, concurrent-ruby 1.0.2

~~~ruby
    reference = Concurrent::AtomicReference.new
    delay = Concurrent::Delay.new { 1 }
    reference.set delay

    d = reference.value
    value = d.value
    if d.reason
      raise d.reason
    end
    value
~~~

produces:

~~~
/Users/jrochkind/.gem/ruby/2.3.1/gems/concurrent-ruby-1.0.2/lib/concurrent/concern/obligation.rb:120: warning: instance variable @reason not initialized
~~~

That seems like a perfectly reasonable thing to do, I don't think I'm doing anything wrong, I think it's something in concurrent-ruby sourcecode that may not actually have a bug but does trigger a warning from MRI?

Another warning my test suite produces, which I haven't yet been able to isolate into a repro, include:

~~~
/Users/jrochkind/.gem/ruby/2.3.1/gems/concurrent-ruby-1.0.2/lib/concurrent/delay.rb:94: warning: instance variable @value not initialized
~~~

Both these warnings are of course produced many multiple times by my test suite.

**Comment by matthewd** [comment]
Another one:

```
Concurrent::Future.execute { oops }.value!
```

```
/Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/concern/dereferenceable.rb:22: warning: instance variable @value not initialized
NameError: undefined local variable or method `oops' for main:Object
```

**Comment by pitr-ch** [comment]
Thanks, I have a look to get this fixed for the upcoming patch release. (Including some automated tests for this, we did fix warnings before).

**Comment by pitr-ch** [comment]
the test enhancement is tracked separately https://github.com/ruby-concurrency/concurrent-ruby/issues/588
