### ISSUE TITLE
Stepping down as maintainer

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#580]
I've decided to step down as maintainer of Concurrent Ruby. I've asked @pitr-ch to take over that role and he has graciously agreed.

As this project has grown my passion has increasingly shifted toward evangelism: speaking at conferences, participating in online discussions, and generally promoting Ruby and this project in every way I can. Meanwhile, Petr has become increasingly active in working on the next release, improving the project's internals, and communicating with the MRI and JRuby core teams. I believe this project will be best served if we each focus on the areas where we can make the biggest impact. I first spoke to Petr about this several weeks ago but decided to wait until after my RubyConf Brazil keynote. I wanted to focus on my message at that conference rather than field questions about this decision.

To be clear, I'm not leaving the project. Not at all. I will still be an active participant. I'm just passing the reins to Petr so that I can invest my energies in the things I do best: telling the world how awesome Ruby is and helping to shape the conversation about Ruby's concurrent future. I'm especially excited about the proposed concurrency features of Ruby 3. I'm looking forward to the work we'll do upgrading concurrent-ruby to work with guilds. And most importantly, I hope to lend my voice to the conversation, providing feedback on the evolution of Ruby 3.

**Comment by pitr-ch** [comment]
I am happy to accept the role and responsibility. The gem will continue in the same direction. If there are changes or improvements, there will be a public issue or pull-request opened to discuss as it was before. I am looking forward to more of your talks and I wish you safe travel without delays. Indeed, Thank you for all your work. And I am looking forward to cooperate with you in future.

Best regards,
Petr

**Comment by ianks** [comment]
Thanks @jdantonio for your top-notch maintainer work! concurrent-ruby has really been exemplary in the Ruby space. I am confident things will keep progressing in the same way now that @pitr-ch takes the wheel.
