### ISSUE TITLE
Documentation enhance: Is it possible to upgrade a reentrant rw-lock from read to write?

### ISSUE THREAD

**Issue by kalsan** [ruby-concurrency/concurrent-ruby#582]
Hi!
On the page http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/ReentrantReadWriteLock.html there is no information about up- or downgrading locks. The parent index page gives some info, but not a lot.
IMHO it would be helpful to have a brief sentence whether or not it is possible to up- and / or downgrade a lock, as done in https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html -> "Lock Downgrading"

**Comment by pitr-ch** [comment]
Thanks, for letting us know. Makes sense to add it. Would you open a PR with the update please?

**Comment by kalsan** [comment]
I'd love to, but I can't write documentation about something I don't know (that's why I asked the question here).

**Comment by pitr-ch** [comment]
Ah sorry, I've misunderstood. The ReentrantReadWrite supports both downgrade and upgrade.

**Comment by pitr-ch** [comment]
Examples can be found in specs: https://github.com/ruby-concurrency/concurrent-ruby/blob/master/spec/concurrent/atomic/reentrant_read_write_lock_spec.rb

**Comment by pitr-ch** [comment]
done in 476f59383e6bb357d41416f7e1693ede6350e7bb
