### ISSUE TITLE
Java-based Semaphore does not allow new with 0 passes

### ISSUE THREAD

**Issue by headius** [ruby-concurrency/concurrent-ruby#592]
Here's the simple reproduction.

``` ruby
require 'concurrent'

p Concurrent::Semaphore.new(0)
```

On MRI, this runs fine. On JRuby, we get:

```
$ jruby -e "require 'concurrent'; p Concurrent::Semaphore.new(0)"
ArgumentError: count must be in integer greater than zero
  initialize at com/concurrent_ruby/ext/JavaSemaphoreLibrary.java:43
      <main> at -e:1
```

Of course a Semaphore with zero available permits is perfectly valid, and indeed, `java.util.concurrent.Semaphore` even allows _negative_ permits.

This leads to a number of errors in Rails's actioncable tests: https://gist.github.com/headius/a137448dbc6c6b845128c6deb6d5d227

**Comment by pitr-ch** [comment]
Thanks! I have a look and I'll fix it with next release. Should be simple.

**Comment by pitr-ch** [comment]
@headius which version did you try?

**Comment by headius** [comment]
Looks like Rails has a dependency on 1.0.2 right now, so that's what I would have been using.

**Comment by pitr-ch** [comment]
There were couple other methods not matching java behaviour.
