### ISSUE TITLE
Promise.all? behavior

### ISSUE THREAD

**Issue by gtan66** [ruby-concurrency/concurrent-ruby#602]
Hi guys!

I noticed that the implementation of `Promise.all?` differs from that of JavaScript's Promise.all. It seems like `Promise.all?` executes the promises in the argument consecutively, whereas JS's Promise.all executes them concurrently, and then resolves when all of them have completed. 

Really simple examples to illustrate:
 
JS example: http://jsbin.com/?html,css,js,console 

Ruby example:

```ruby
def pr10
  Concurrent::Promise.new{
    puts "hi"
    sleep 10
    puts "bye"
  }
end

Concurrent::Promise.all?(pr10,pr10).execute
```

Output: 
<img width="349" alt="screen shot 2016-11-07 at 7 22 10 pm" src="https://cloud.githubusercontent.com/assets/9708700/20082009/0fab21e8-a521-11e6-8562-406e2e9170e8.png">

Is there a reason for implementing it this way? I see that we are calling `Promise.wait` in the implementation [here](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/promise.rb#L476). Thanks :)

**Comment by pitr-ch** [comment]
Hi @gtan66, thank you for submitting an issue. However, we are now working on getting new implementation of Premisses into edge and then into core. The new implementation does not have the issue so unless somebody contributes the enhancement for the old implementation we'll focus on getting the new implementation in. Related to https://github.com/ruby-concurrency/concurrent-ruby/pull/577.
