### ISSUE TITLE
Using future - Do I still need to use mutex?

### ISSUE THREAD

**Issue by abhisheksarka** [ruby-concurrency/concurrent-ruby#604]
I am using `Concurrent::Future` to run some async tasks that changes a couple of datasources(NoSql DB and SQS queue). I was wondering if I should synchronise access to these sources. I know I should but, does `concurrent-ruby` has any libraries that I can make use of? Any help will be much appreciated. For reference I have added a snippet below.

```ruby
def safe_thread(pool, ctx_hash, synchronized=false)
  Concurrent::Future.execute(executor: pool) do
    begin
      yield
    rescue StandardError => ex
      log(ex.message, {ctx: ctx_hash, backtrace: ex.backtrace})
    end
  end
end
```

**Comment by pitr-ch** [comment]
It depends on the driver of a particular database. If the driver is thread-safe and uses locks internally (or other tools) (which they ideally should) you can just use it from the future without any additional synchronisation. However If the driver is not thread-safe then one solution would be to create a thread-safe pool of connections and borrowing one connection to the future when they need it. Quick and simple implementation could be made with a queue.

```ruby
POOL = Queue.new
10.times { POOL.push AConnection.new }

def with_connection(&block)
  connection = POOL.pop # blocks until connection is available
  block.call connection
ensure
  POOL.push connection
end

Future.execute { with_connection { |connection| do_stuff } }
```
