### ISSUE TITLE
Depracation on ruby 2.4.0

### ISSUE THREAD

**Issue by refaelos** [ruby-concurrency/concurrent-ruby#619]
I'm getting this warning after installing ruby v2.4.0:
```
warning: constant ::Fixnum is deprecated
```

Is it a problem or can I ignore?

******
-   Operating system: linux
-   `concurrent-ruby` version: 1.0.2
-   `concurrent-ruby-ext` installed: no
-   `concurrent-ruby-edge` used: no

**Comment by pitr-ch** [comment]
@refaelos could you try 1.0.3? it should be fixed.

**Comment by refaelos** [comment]
@pitr-ch fixed. Thanks!
