### ISSUE TITLE
Is there a hook for FixedThreadPool when a thread dies?

### ISSUE THREAD

**Issue by phstc** [ruby-concurrency/concurrent-ruby#638]
Hey

Is there a way/hook to know when a thread dies in a `FixedThreadPool`? 

******
-   Operating system: linux / mac / win
-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-ext` installed: no
-   `concurrent-ruby-edge` used: no

**Comment by phstc** [comment]
Giving more context to that question, I have code like this:

```ruby
Concurrent::TimerTask.new(...) { dispatch }

def dispatch
  return unless dispatching.make_true

  work_load = make_a_request(max_result: thread_pool.ready_capacity)

  post_work(work_load, thread_pool)
ensure
  dispatching.make_false
end
```

But I would love to stop doing a request at time `return unless dispatching.make_true` and in order to do that, I need to control the ready capacity on my side:

```ruby
thread_pool.thread_completed = :thread_completed
thread_pool.thread_died = :thread_died

def thread_completed
  ready.increment
end

def thread_died
  ready.increment
end

def dispatch
  work_load = make_a_request(max_result: ready.value)

  work_load.each { ready.decrement }

  post_work(work_load, thread_pool)
end
```

Does that make? Any idea on how to implement that using concurrent-ruby? I don't want to use `ready_capacity` because I can only have a valid `ready_capacity` after `posting` work, and for that, I need fetch (make a request) first.

**Comment by phstc** [comment]
Closed by https://github.com/ruby-concurrency/concurrent-ruby/issues/616#issuecomment-268839855

I will probably stick with 

```ruby
Concurrent::Promise.execute {  ...  }.on_success { ... }.on_error { .. }
```

**Comment by pitr-ch** [comment]
@phstc sorry I did not respond in time, I would have recommended a higher-level abstraction like promises as well.

**Comment by phstc** [comment]
@pitr-ch no worries, thanks for checking that 🍻 

As I have you in here (hehe), may I ask you something else? I'm using `Concurrent::SingleThreadExecutor` for an endless loop, like:

```ruby
@exec = Concurrent::SingleThreadExecutor.new

dispatch

def dispatch
  do_something
ensure
  @exec.post { dispatch }
end

# See https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb#L71
```

Any thoughts on that? I mean, does it feel like a proper usage?

**Comment by pitr-ch** [comment]
It's little strange, but works. It blocks a thread which might be an issue, depending on you application and how many dispatches are there running concurrently.

You might be interested in http://ruby-concurrency.github.io/concurrent-ruby/file.promises.out.html#Run__simulated_process_ http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Promises/Future.html#run-instance_method then :) Promises are getting merged from edge to core in 1.1 which will be out soon.

**Comment by phstc** [comment]
@pitr-ch so in that case I only one dispatcher at time, I want to guarantee it dispatches one at time.

I tried to use a `TimeTask` before, but it "leaking" threads, as @waynerobinson pointed out [here](https://github.com/ruby-concurrency/concurrent-ruby/pull/526#issuecomment-287992834).

> Promises are getting merged from edge to core in 1.1 which will be out soon.

Cool, I'm looking forward to it.

**Comment by pitr-ch** [comment]
yeah `#run` would work for that use-case. Yeah the leak is a serious issue I have to have a look at it.

**Comment by phstc** [comment]
Hi @pitr-ch 

Could you help me with a possible impl with `#run`, basically I need something like this:

```ruby
def dispatcher_loop
  # outside the main thread
  while true
    break if @done.true?

    dispatch # locks 
  end
end
```

I would like to run that outside the main thread, and do something that make sure if for some reason the thread dies, it restarts it.

Just to give you more context, [Shoryuken](https://github.com/phstc/shoryuken) is a process that runs in background continuously polling messages from [AWS SQS](https://aws.amazon.com/pt/sqs/), and it limits the number of polled messages based on the concurrency configured in Shoryuken. For example: if a Shoryuken process is configured with concurrency 25, it will have 25 threads available, so it can only process 25 messages at time, this `dispatcher_loop` is responsible for polling messages whenever a thread is available.
