### ISSUE TITLE
Concurrent::Map#each behaves differently in MRI and JRuby

### ISSUE THREAD

**Issue by ivoanjo** [ruby-concurrency/concurrent-ruby#643]
-   Operating system: linux
-   `concurrent-ruby` version: 1.0.5 and master (tried both)
-   `concurrent-ruby-ext` installed: no
-   `concurrent-ruby-edge` used: no

### Description:

`Concurrent::Map#each` when called without a block returns an enumerator on MRI but `self` on JRuby.

### Testcase:

```ruby
require 'concurrent'
puts "#{RUBY_ENGINE}: #{Concurrent::Map.new.each.inspect}"
```

Output in MRI 2.4.1:
```
ruby: #<Enumerator: #<Concurrent::Map:0x0055dd74e2dcc0 entries=0 default_proc=nil>:each_pair>
```

Output in JRuby 9.1.8.0:
```
jruby: #<Concurrent::Map:0x00000000000fa0 entries=0 default_proc=nil>
```

**Comment by pitr-ch** [comment]
@ivoanjo Thanks for reporting! It should indeed behave the same. Would you have time to contribute a PR with a fix?

**Comment by ivoanjo** [comment]
Yes, I think I can take a stab at it today :)

**Comment by pitr-ch** [comment]
Great!
