### ISSUE TITLE
Can not get value for async/future, even if it present in instance variable

### ISSUE THREAD

**Issue by stereobooster** [ruby-concurrency/concurrent-ruby#650]
-   Operating system: linux
-   `concurrent-ruby` version: latest
-   `concurrent-ruby-ext` installed: no
-   `concurrent-ruby-edge` used: no

[Code with example of problem](https://github.com/stereobooster/raygun4ruby/commit/9d997d28a277453c13a70c42221ee91a9e0ebdc7)

```ruby
response = Client.new.async.track_exception(exception_instance, env, user)
response.wait!
response.value # nil
response.instance_variable_get("@value") # has value (HTTP response)
```

What I'm doing wrong?

**Comment by pitr-ch** [comment]
Sorry that your issue went unanswered for long time. The link does no longer work, I cannot help without more information about `Client.new.async.track_exception`. Could you fix the link or provide more information here?

**Comment by stereobooster** [comment]
Thanks. Code was done other way by authors of the gem, not relevant anymore
