### ISSUE TITLE
expose the prune operation from thread pools

### ISSUE THREAD

**Issue by doudou** [ruby-concurrency/concurrent-ruby#652]
I'm specifically interested in the `CachedThreadPool` on MRI, but I assume that other thread pools/implementations probably have the same issue.

`RubyCachedThreadPool` prunes itself only on execute. I'm having an execution flow that creates a lot of threads in a short period of time and then stops using the thread pool altogether for a long period. This leads to having a few 100s of threads alive that are unused, and breaks the pruning functionality altogether.

I'm currently periodically calling `ns_prune_pool` from an event loop. However, this is private API, and would prefer having it exposed as public API. Would you consider a PR that does that ? I guess that implementation which take care of the pruning (e.g. Java) would simply expose a no-op.

******
-   Operating system: linux
-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-ext` installed: yes
-   `concurrent-ruby-edge` used: no

**Comment by pitr-ch** [comment]
Thanks, this is a good functionality to have. Would you have time to look at it? It needs to work on JRuby (which uses Java thread pool) as well. Java thread pool may already solved it so we might just need to take inspiration there and port it to Ruby implementation.

**Comment by doudou** [comment]
> Would you have time to look at it?

I believe so, I'll check it out. I'm guessing I'll add a `#prune_pool` public method for that.

**Comment by pitr-ch** [comment]
Thanks!

**Comment by pitr-ch** [comment]
@doudou would you be still interested in looking into this?

**Comment by doudou** [comment]
Hum ... completely forgot about this. I'll add it to my todo list ... Sorry for that.

**Comment by pitr-ch** [comment]
@doudou thanks. No problem 😃

**Comment by doudou** [comment]
Finally ... #761

**Comment by chrisseaton** [comment]
Replaced with #938.
