### ISSUE TITLE
Task not Posted to Custom Executor

### ISSUE THREAD

**Issue by gogo52cn** [ruby-concurrency/concurrent-ruby#656]
-   Operating system: mac 
-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-ext` installed: no
-   `concurrent-ruby-edge` used: no

I am using Concurrent::Async

by default when using .async.method_name, the task gets posted to the "global_io_executor". Which is fine.

Then when I tried to supply a custom executor to the instance, I expected it to post the task to this custom executor. However the task still gets posted to global_io_executor.

My customer executor in a Class instance variable.
`
Class TreeNode
    @thread_pool_executor = Concurrent::ThreadPoolExecutor.new(
      :min_threads => [2, Concurrent.processor_count].max,
      :max_threads => 20,
      :max_queue   => 100,
      :fallback_policy => :caller_runs
    )
  class << self
    attr_accessor :thread_pool_executor
  end
end
`

In the class which includes Concurrent::Async, I added the following

`
#lot of code omitted....

def initialize
  super
  executor = TreeNode.thread_pool_executor
end

`

**Comment by pitr-ch** [comment]
There is no API for setting a custom executor as far as I can tell. I would gladly accept a PR which would add it.

**Comment by jdantonio** [comment]
A very early version had a the ability to set a custom executor but I later removed that for simplicity. Async is intended to be used for simple purposes, with applications using our other abstractions once they become more complex. That being said, if people find Async useful and would find value in the ability to change executor then I'm all for it. My once concern is that we ensure that the executor can only be set during object initialization and not after. Changing the executor with incomplete tasks enqueued will cause problems with the serialization guarantees and thread safety of the object. If there is a need to change the executor after object initialization I believe that Async is the wrong abstraction.

**Comment by gogo52cn** [comment]
Thank you for your reply.

Given this limitation, now I am using Future instead of Async.

Could the documentation be updated? I am asking, because in the documentation for Async, there is still a reference to “executor=“ instance method.

**Comment by pitr-ch** [comment]
@gogo52cn could you contribute a PR fixing the documentation? Thanks.

**Comment by pitr-ch** [comment]
I cannot find the reference.
