### ISSUE TITLE
Question about MRILockableObject#ns_wait

### ISSUE THREAD

**Issue by ianks** [ruby-concurrency/concurrent-ruby#657]
When using pthread_cond_wait, it is advised to always spin on the condition variable to prevent spurious wake ups. I noticed in MRILockableObject#ns_wait that we do not spin. 

### Some questions I have

1. Does MRI have some strong guarantees around spurious wake ups? 
2. Does ruby use pthread_cond_wait?
3. If so, does it hand spurious wake ups?

Code in question:

```ruby 
def ns_wait(timeout = nil)
  @__condition__.wait @__lock__, timeout
  self
end
```

**Comment by ianks** [comment]
Update: It looks like if `ConditionVariable#wait` is called, it ends up calling the aptly named [rb_thread_sleep_deadly_allow_spurious_wakeup](https://github.com/ruby/ruby/blob/ea1ce47fd7f2bc9023e9a1391dbadcfaf9e892ce/thread_sync.c#L422)

So unless I am mistaken, we are subject to spurious wakeups in any code that uses MRILockableObject#ns_wait without a timeout.

**Comment by pitr-ch** [comment]
Thanks for reporting. This looks like a serious problem.

**Comment by pitr-ch** [comment]
Ah I think it's actually fine, ns_wait is documented to allow spurious wake-ups, and ns_wait_until checks it in a loop. Where do you think it could cause problems?

**Comment by pitr-ch** [comment]
@ianks ping
