### ISSUE TITLE
Move #create from Promises::FactoryMethods

### ISSUE THREAD

**Issue by IronSavior** [ruby-concurrency/concurrent-ruby#658]
I've been using the new edge Promises API with great success--fantastic work!

I'd like to propose a minor change and I'm happy to submit a PR for it myself if you agree. There is a module `Concurrent::Promises::FactoryMethods` that contains a number of methods for working with this API like `zip_futures`, `fulfilled_future`, etc. 

My impression is that the purpose of this module is so that a class can include it so instances of that class can use these methods more conveniently so that code like this:

```ruby
class MyThing
  def promised_action
    kill_switch = Concurrent::Promises.resolvable_future
    
    promises = stuff.map do |item|
      Concurrent::Promises.future(item, &:do_something).rescue{ |e| kill_switch.reject e }
    end

    kill_switch | Concurrent::Promises.zip_futures(*promises)
  end
end
```

can be made more concise like this:
```ruby
class MyThing
  include Concurrent::Promises::FactoryMethods
  
  def promised_action
    kill_switch = resolvable_future
    
    promises = stuff.map do |item| 
      future(item, &:do_something).rescue{ |e| kill_switch.reject e } 
    end
    
    kill_switch | zip_futures(*promises)
  end
end
```

If this is the intended purpose of the `Concurrent::Promises::FactoryMethods` module, then I propose that the `#create` method be moved to be a singleton method on the `Concurrent::Promises` module itself.

My reasoning behind this is that although `#create` is correctly described as a factory method, this specific method isn't very useful to the including class because "create" is a pretty vague name for a mixin method. This is in contrast to other methods in this module like `#future` and `#zip_futures` which have really good names for mixin behaviors.

Thoughts?

******
-   Operating system: linux
-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-ext` installed: yes
-   `concurrent-ruby-edge` used: yes

**Comment by pitr-ch** [comment]
Thanks, this is good point. The create could indeed collide. I would rather just rename the method to something else to avoid collisions. Having just this method on Promises as singleton could be surprising to users so I'd rather keep it in the `FactoryMethods` module with rest of the factory methods. Name suggestions: `create_future`, `as_future`, `to_future` what would you choose or add?

**Comment by IronSavior** [comment]
Since the behavior of `#create` varies depending on the argument as opposed to `self`, `#as_future` or `#to_future` may be confusing because they suggest a type conversion/wrap operation for the receiver. `#create_future` is better in this respect, but I fear it's not distinguished well enough from `#future`.

In this case, I would suggest something like `#make_future`. It's a common convention in many languages to name a combined constructor and initializer function `make_x`. I find this convention is less common in ruby. This is probably because ruby code typically doesn't need to provide no-throw guarantees during object construction where it would be advantageous in other languages to provide a no-throw constructor alongside a `make_x` initializer.

It's more common in ruby for this sort of behavior to belong to `#initialize` directly, but borrowing the `make_x` convention seems appropriate for a mixin module like `FactoryMethods` in a library that is already borrowing so heavily from other languages.

**Comment by pitr-ch** [comment]
`#make_future` sounds good. Could you make a PR?

**Comment by IronSavior** [comment]
I can do that.

**Comment by pitr-ch** [comment]
I've done it on my branch and it will go in with other promises changes. Thanks for the suggestion.
