### ISSUE TITLE
require 'concurrent/scheduled_task' does not make the example to work

### ISSUE THREAD

**Issue by mkristian** [ruby-concurrency/concurrent-ruby#674]
just took me a while to debug things but
```
require 'concurrent/scheduled_task'
task = Concurrent::ScheduledTask.new(2){ 'What does the fox say?' }
p task.state         #=> :unscheduled
task.execute
p task.state         #=> pending

# wait for it...
sleep(3)

p task.unscheduled? #=> false
p task.pending?     #=> false
p task.fulfilled?   #=> true
p task.rejected?    #=> false
```

does not work on any ruby I tried (mri-2.2, mri-2.3, jruby-9.1.7) then I read in the documentation that I need to use `require 'concurrent'`.

sorry - wrong habit to just require things I really need. is this a bug or feature ?

-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-edge` used: no

**Comment by pitr-ch** [comment]
Hi, I am bit confused. What's the problem with `ScheduledTask`? 

Officially we only support require 'concurrent', although requiring just parts mostly works. In the future we would like to make sure that all sub-requires like `require 'concurrent/scheduled_task'` works, and allow users to use it.
