### ISSUE TITLE
Promise.zip doesn't quite do what the docs say it does

### ISSUE THREAD

**Issue by chriskite** [ruby-concurrency/concurrent-ruby#675]
The docs for Promise.zip say it creates a Promise that "fails if any of them fails". This is potentially misleading, because in fact it only fails once all of the promises complete if any promise failed.

For example, the following will not fail:
`Promise.zip(Promise.new { sleep 1000000 }, Promise.new { raise StandardError.new })`

However, the following *will* fail, because promises are checked in order:
`Promise.zip(Promise.new { raise StandardError.new }, Promise.new { sleep 1000000 })`

******
-   Operating system: linux
-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-ext` installed: no
-   `concurrent-ruby-edge` used:  no

**Comment by chriskite** [comment]
In case it helps, my motivation was that I was trying to find a way to create a Promise that would either complete successfully or fail after a time out. In Scala, Akka Futures have the `firstCompletedOf` method which allows the creation of a Future with a timeout, and I need something similar in Ruby.

**Comment by pitr-ch** [comment]
This is an implementation deficiency shortcoming of Promise, it will however work as expected in the new Promises implementation from edge gem:
```
[5] pry(Concurrent):1> Promises.any Promises.future { sleep }, Promises.future {raise}
=> #<Concurrent::Promises::Future:0x00007fc3b2c28300 pending>
[6] pry(Concurrent):1> _
=> #<Concurrent::Promises::Future:0x00007fc3b2c28300 rejected>
```
