### ISSUE TITLE
Agent not dispatching action with no apparent errors

### ISSUE THREAD

**Issue by mikedalpee** [ruby-concurrency/concurrent-ruby#690]
I have an odd problem where some code I wrote base on Concurrent::Agent works fine when I run it on my local computer but fails when I run in in a docker container.  The snippet that is failing is:

```ruby
def create_job_if_not_already_running(site,product)
    Rails.logger.debug "In create_job_if_not_already_running"
    key = Key.new(site,product)
    is_added = [false]
    self.send do |hash|
      Rails.logger.debug "In create_job_if_not_already_running Agent"
      if !hash.key?(key)
        hash[key] = [0]
        Rails.logger "Key added"
        is_added[0] = true
      end
      hash
    end
    Rails.logger.debug "Waiting for Agent - failed?: #{self.failed?}, error: #{self.error}"
    self.await
    Rails.logger.debug "is_added[0] = #{is_added[0]}"
    is_added[0]
end

```
What is happening in the container (which does not happen on my local computer) is once the call gets to self.await, the Agent never executes the action I initiated via send, so the wait never proceeds.   Here is the output from the logs when I run it on the container:

In create_job_if_not_already_running
Waiting for Agent - failed?: false, error:

I have no idea how to troubleshoot this, so any insight you can give me about how to figure out why this odd behavior is happening would be appreciated.  Thanks.

******
-   Operating system: linux
-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-ext` installed: yes
-   `concurrent-ruby-edge` used: yes

**Comment by pitr-ch** [comment]
Sorry I have no insight at the moment. What Ruby do you use? Do you extend the `Agent` class directly? If so, I would recommend to use composition instead to eliminate any accidental interference with the agent implementation. Could whole class?

**Comment by chrisseaton** [comment]
No response in four years.
