### ISSUE TITLE
Shutting down TimerTask is stopping already executing tasks

### ISSUE THREAD

**Issue by stravid** [ruby-concurrency/concurrent-ruby#691]
Shutting down a timer task is not waiting for already executing tasks to finish. I talked to @headius and he encouraged me to open an issue since it is not clear if this is a feature or bug.

Example code:
~~~ruby
require "rubygems"
require "bundler/setup"
require "concurrent"

tasks = 10.times.map do |s|
  Concurrent::TimerTask.new(execution_interval: 1) do
    sleep s
    puts "s: #{s}\n"
  end
end

begin
  tasks.each { |t| t.execute }
  sleep
rescue Interrupt
  puts "Received INT"
  puts "Shutting down tasks"
  tasks.each { |t| t.shutdown }
ensure
  puts "Releasing resources"
end
~~~

**Comment by headius** [comment]
It seems like a bug if shutting down a TimerTask kills a timed execution that has already started. Seems like it should wait for completion, or there should be another way to say "shutdown_after_current_task_has_completed".

**Comment by pitr-ch** [comment]
Thank you, I'll have a look.

**Comment by jamesarosen** [comment]
I would have expected `Concurrent.global_timer_set.wait_for_termination` to be the implementation of "wait around long enough," but it resolves as soon as the `stopped_event` is synchronized across the threads. That's because `TimerTask#ns_shutdown_execution` only blocks on synchronizing the `@running` variable. `#execute_task` doesn't record the current state in any way, so `#ns_shutdown_execution` can't watch for it.

**Comment by jamesarosen** [comment]
This is my current workaround:
```rb
class LastRunObserver
  def self.wait_for_tasks_to_finish(tasks, timeout)
    stop_at = Time.now

    observers = tasks.map do |t|
      t.add_observer(self.new)
    end

    timeout.times do
      break if observers.all? { |o| o.run_since?(stop_at) }
      sleep 1
    end
  end

  def initialize
    @last_run = Time.now
  end

  def update(time, *args)
    @last_run = time
  end

  def run_since?(time)
    @last_run.to_i > time.to_i
  end
end

tasks.each(&:execute)

begin
  sleep
rescue Interrupt
  LastRunObserver.wait_for_tasks_to_finish(tasks, 20)
  Concurrent.global_timer_set.shutdown
ensure
  puts "Shut down all tasks"
end
```

That will give the tasks up to 20 seconds to finish their current run.

**Comment by jamesarosen** [comment]
A related problem is that `task.running?` does not change during a task iteration:
```rb
task = Concurrent::TimerTask.new(execution_interval: 1) do |task|
  5.times do
    puts "#{i} task.running? #{task.running?}"
    sleep 1
  end
end
task.execute
task.shutdown
sleep 6
```
emits
```
1 task.running? true
2 task.running? true
3 task.running? true
4 task.running? true
5 task.running? true
```
Even changing it to `task.send(:sychronize) { task.running? }` doesn't help.

**Comment by bensheldon** [comment]
TimerTask executes the task as a `ScheduledTask` on the default global executor (`Concurrent.global_io_executor`):

https://github.com/ruby-concurrency/concurrent-ruby/blob/9f40827be9a8a192a6993a8d157bd3ed0662ada0/lib/concurrent-ruby/concurrent/timer_task.rb#L292-L292

I'm not sure if that's a mistake when it [was introduced](https://github.com/ruby-concurrency/concurrent-ruby/pull/344) and instead it should have the argument `executor: self`; though going back farther in git history I don't see a TimerTask ever making use of itself inheritting from RubyExecutorService.

So as it is today, to safely shutdown, you'll want to shutdown and wait on `Concurrent.global_io_executor` when an interrupt signal is trapped.

I think this could also imply:

- A fix to make the ScheduledTask have set `executor: self` 
- Allow passing in an explicit `executor:` when TimerTask is initialized so someone can set their own Executor.

**Comment by bensheldon** [comment]
I'm planning to make a PR. There are maintainers, but fairly quiet.

**Comment by headius** [comment]
I'll be watching and will help get maintenance going on this project again.

**Comment by bensheldon** [comment]
Not to get too offtopic, but I think this project is incredibly important and I'm personally invested in contributing because of GoodJob (and I'm interested in becoming a formal maintainer too). My colleague `@matthewd` is a current maintainer, so I don't think we'll be blocked on necessary/important work. But forming consensus/decisions will probably need some pushing on 👍🏻

**Comment by eregon** [comment]
> I'm not sure who is maintaining this currently

It's documented in the README: https://github.com/ruby-concurrency/concurrent-ruby/blob/master/README.md#maintainers
It's also a pretty big project, so it's maintained more on a need basis I'd say.

**Comment by bensheldon** [comment]
Setting `executor: self` is a bit spicier than I realized. While the TimerTask _is_ `RubyExecutorService` it create any kind of execution pool. So I think simply providing an argument for `executor: Concurrent.global_io_executor` on initialize will be the path I plan to take.

**Comment by eregon** [comment]
> I'll be watching and will help get maintenance going on this project again.

@headius Would you like to help maintain this project and e.g. reviews PRs? I would happily add you to the list of active maintainers at https://github.com/ruby-concurrency/concurrent-ruby/blob/master/README.md#maintainers (or you can do it yourself if you like). You already have the rights anyway. I should have asked you earlier when we were searching new maintainers, I missed it somehow, sorry about that.

**Comment by eregon** [comment]
> Not to get too offtopic, but I think this project is incredibly important and I'm personally invested in contributing because of GoodJob (and I'm interested in becoming a formal maintainer too).

Given your many PRs and interested I would be delighted to add you as maintainer, I'll send the GitHub invite now.
