### ISSUE TITLE
Concurrent::Map.inspect triggers infinite loop with did_you_mean gem

### ISSUE THREAD

**Issue by kikonen** [ruby-concurrency/concurrent-ruby#693]
It seems that if "no method found" error occurs within rails template rendering, then infinite loop is triggered via "Concurrent::Map.inspect", and only way to resolve situation is to restart rails web server.

Following HACK seems to workaround issue
```
#
# HACK KI concurrent map cause infinite loop via "did_you_mean" with NoMethodError within rails template
#
class Concurrent::Map
  def inspect
    id_str = (object_id << 1).to_s(16).rjust(DEFAULT_OBJ_ID_STR_WIDTH, '0')
    "#<#{Map}:0x#{id_str} entries=#{size}>"
  end
end
```

As you can guess this makes development/test cycle rather inconvenient in Rails

Versions:
- rails 5.1.x
- ruby 2.4.x or ruby 2.5.x
- concurrent-ruby (1.0.5)

**Comment by pitr-ch** [comment]
Hi @kikonen, thanks for reporting! Could you elaborate how does it enter the loop in the `@default_proc.inspect`, perhaps a backtrace? Is `self.class.name` unrelated fix, or does it play a role in the problem?

**Comment by pitr-ch** [comment]
@kikonen could you provide a small reproducer so it can be fixed? Thanks.

**Comment by chrisseaton** [comment]
Is anyone able to supply a reproducer? I can't reproduce.
