### ISSUE TITLE
Concurrent::Promise.execute does not close the spawned thread 

### ISSUE THREAD

**Issue by monterey01** [ruby-concurrency/concurrent-ruby#701]
******
-   Operating system: l mac 
-   `concurrent-ruby` version:concurrent-ruby (1.0.5 java)
-   `concurrent-ruby-ext` installed:  no
-   `concurrent-ruby-edge` used:  no
- ruby versions tested - =* jruby-9.1.2.0 [ x86_64 ]( Our team uses this in production)
   ruby-2.2.5 [ x86_64 ](Same issue with native ruby)

```ruby
require 'sinatra'
require 'concurrent'
configure { set :server, :puma }

$count=0

class Ticker
  def get_year_end_closing

    puts 'method 1 start'
    p Time.new.inspect
    sleep 10

    puts 'method 1 then'
    p Time.new.inspect
  end

  $ticker=Ticker.new

  def get_year_end_closing2

    puts 'method 2'
  end
end

get '/' do
  promise=Concurrent::Promise.execute{ $ticker.get_year_end_closing}
  return 'success'
end
```

I am having an issue with above code where  Concurrent::Promise.execute does not close the spawned thread after get_year_end_closing is successfully executed.

I can't shutdown sinatra gracefully without killing the java process. Please let me know how to fix. Same issue is noticed if i use future. I want to chain based on the output of get_year_end_closing.

Please let me know how to fix.

**Comment by pitr-ch** [comment]
That is strange, the global pool is set to auto-terminate on JRuby. It should shutdown gracefully, I'll investigate further.

**Comment by pitr-ch** [comment]
For the next release I've rolled back all the Java implementations which were blocking, #717. That should help. You can test master or 1.0.6 when it's released. If it's not fixed please reopen.
