### ISSUE TITLE
Coveralls Repo Token Exposed

### ISSUE THREAD

**Issue by brompwnie** [ruby-concurrency/concurrent-ruby#705]
Hello,

It appears that your Coveralls repo token is publicly accessible here, https://github.com/ruby-concurrency/concurrent-ruby/blob/master/.coveralls.yml#L1.
If this token is valid, someone could submit submit Coverage data with this token, perhaps it should be implemented as an environment variable if it is being used?

**Comment by pitr-ch** [comment]
Thank you. Do you know if the token can also be used for something else then submitting the coverage data?
