### ISSUE TITLE
ThreadPoolExecutor block/wait fallback policy

### ISSUE THREAD

**Issue by jbodah** [ruby-concurrency/concurrent-ruby#711]
I was curious how others felt about a feature for blocking when the ThreadPoolExecutor pool is busy and the queue is full. This might already be implemented but it's unclear to me based on the documentation

I often find myself writing scripts where the main thread generates data quickly and I want a worker pool for doing concurrent IO. I don't want to overload my receivers so pooling is important, and I don't want an unbounded queue as my process may run out of memory by buffering too much data in the queue. The `:caller_runs` fallback policy gives me the impression that the rest of the pool can run out of work to do if the queue gets emptied while the caller is busy (e.g. if the caller is taking an unusually long time)

Perhaps such a feature isn't worth the complexity given `:caller_runs` exists (or maybe I'm misunderstanding how the existing fallback policies work), but I figured I'd open up a discussion around it anyways

**Comment by pitr-ch** [comment]
This is not implemented at the moment. There is an issue to support this #493. Having a blocking policy is a good idea not sure if doable though. Adding note to the issue.

**Comment by jbodah** [comment]
Not the most elegant, but here's a simple implementation using `SizedQueue` as a blocking buffer:

```rb
require 'concurrent'

pool = Concurrent::FixedThreadPool.new(5, max_queue: 0)
sized_queue = SizedQueue.new(1)

20.times do |n|
  sized_queue.push(n)
  pool.post do
    n2 = sized_queue.pop
    puts "running #{n2}"
    sleep 2
  end
end

pool.shutdown
pool.wait_for_termination
```

**Comment by pitr-ch** [comment]
Yeah that is a reasonable solution in the meantime.
