### ISSUE TITLE
Unclear how to set logger

### ISSUE THREAD

**Issue by vemv** [ruby-concurrency/concurrent-ruby#712]
Hi!

I'm having trouble with my usage of `Concurrent::TimerTask`, and logging might help debug it.

I have the feeling that exceptions are being swallowed (which is good - allows retries) without being visibly logged to `Rails.logger`.

I had a look at `Concurrent::Configuration`, `Concurrent::Logging` etc but still I don't see where to set the global logger to `Rails.logger`.

Thanks - Victor

**Comment by pitr-ch** [comment]
You can use `Concurrent.global_logger=`. the value has to be something callable e.g. `lambda do |severity, progname, message = nil, &block|` so you may need to wrap the Rails.logger in it.

**Comment by vemv** [comment]
Thank you @pitr-ch!
