### ISSUE TITLE
Add TruffleRuby to CI

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#720]

**Comment by eregon** [comment]
@pitr-ch Please coordinate with me ;)

https://github.com/ruby/mspec/blob/297309c05b89e1a964595d6b8d67a01fd62966e0/.travis.yml#L23-L29
shows one way to run TruffleRuby in CI.
Starting from the upcoming 1.0.0-rc3 release, running the post-install should not be needed on Travis CI.

https://github.com/travis-ci/travis-ci/issues/9803 tracks support for `rvm: truffleruby` to just work, but I don't know when that will be supported.

**Comment by eregon** [comment]
https://github.com/oracle/truffleruby/blob/master/doc/user/standalone-distribution.md now documents how to test TruffleRuby in TravisCI
