### ISSUE TITLE
is Map set not documented?

### ISSUE THREAD

**Issue by jjb** [ruby-concurrency/concurrent-ruby#723]
How does one set a value for Map?

http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Map.html

Thanks!

**Comment by jjb** [comment]
Okay, I think the assumption is it has the same API as `Hash`: `h[:foo]` and `h[:foo]=5`

**Comment by jayjlawrence** [comment]
Actually there's a whole bunch of really good documentation in [AtomicReferenceMapBackend|https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/collection/map/atomic_reference_map_backend.rb]

I was attempting to use `.has_key?(item)` on a Map with no success. I say to myself "well that's not the same as Hash, what gives?"

The AtomicReferenceMapBackend is an implementation of the Map interface and happens to hold the documentation. The variation you will receive is based on your ruby platform.

This code is really interesting and features postponed execution through the compute_* method. I haven't tried them yet but - this is good stuff that hasn't had the exposure it deserves! The code is based on Java's [ConcurrentHashMapV8|https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html] using the [source from this OSS implementation of JSR166|http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/jsr166e/ConcurrentHashMapV8.java].

At some point I'm going to try the compute method out and if not too late will circle back at least with some example code to contribute.

**Comment by pitr-ch** [comment]
Thanks @jayjlawrence for the info. This is actually a bug then (created #764) the documentation should be on Map and the AtomicReferenceMapBackend should not be exposed. We'll appreciate the examples.
