### ISSUE TITLE
Feature Request: AtomicInteger

### ISSUE THREAD

**Issue by herwinw** [ruby-concurrency/concurrent-ruby#736]
Ruby has deprecated the Fixnum class in favour of a more generic Integer class ([example blog post](https://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html)). The class `Concurrent::AtomicFixnum` still uses the Fixnum limits. This means the maximum value of this class depends on the architecture of the system.

At least when using MRI this doesn't make much sense anymore (not sure about C extensions, JRuby or Rubinius). It looks pretty trivial to create a `AtomicInteger` object, just remove the call to `NativeInteger.ensure_integer_and_bounds`. It could get `min` and `max` keyword arguments to specify new limits (which would make it possible to create a n`AtomicFixnum` based on `AtomicInteger` with the current boundaries and remove the code duplication)

I think it's pretty simple trivial to implement, so if the team agrees to this I'm willing to create the pull request for it

**Comment by pitr-ch** [comment]
yeah sounds like a good idea, and I appreciate your offer to help!

Few thoughts:
* Could you add constants to `AtomicFixnum` clearly stating what its max and min value, just taking numbers from `NativeInteger`
* Has to be backward compatible (which you already have in mind).
* I would not add max and min option. Let's keep the API simple.

**Comment by eregon** [comment]
To be efficient, an "atomic integer" has to be able to use compare-and-swap, and that's only available as an assembly instruction for the platform's bitwidth (sometimes for the double of it too, but that's not portable).
Also integers which don't fit in Fixnum are basically slow for any operation in Ruby, no matter what.

So Fixnum is actually the correct requirements for an efficient implementation of an "atomic integer".

If one needs an "atomic integer" with larger values than Fixnum allows, then they can use AtomicReference.

The name may be weird, but aliasing `AtomicFixnum` to `AtomicInteger` seems misleading about the limits. So I'm thinking it's good as it is.
