### ISSUE TITLE
Looking for maintainer of Rubinius support

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#739]
We currently do not have capacity to maintain Rubinius support. If anybody is interested please respond.

**Comment by olleolleolle** [comment]
The Rubinius matrix element in Travis CI is not even installing.

Perhaps that should be let go?

```
16.07s$ rvm use rbx-3.107 --install --binary --fuzzy
curl: (22) The requested URL returned error: 404 Not Found
Required rbx-3.107 is not installed - installing.
curl: (22) The requested URL returned error: 404 Not Found
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm rbx-3.107 do rvm gemset create ' first, or append '--create'.
The command "rvm use rbx-3.107 --install --binary --fuzzy" failed and exited with 2 during .
```

**Comment by chrisseaton** [comment]
The Rubinius repository and discussion rooms have been dead for a year now. Might be time to remove support. I think GitLab are maintaining an internal copy is the only thing? But we can't test against that, and we can't test against that.
