### ISSUE TITLE
JRuby 9.2 fix: New gem version pushed to rubygems soon?

### ISSUE THREAD

**Issue by greghuc** [ruby-concurrency/concurrent-ruby#746]
Hi @pitr-ch 

Is there any chance of a new version of concurrent-ruby being pushed to rubygems soon?

I've just hit this [JRuby 9.2 / concurrent-ruby bug](https://github.com/ruby-concurrency/concurrent-ruby/pull/733) which was fixed about a week ago. I tried using concurrent-ruby head from github, but this errors with `On JRuby but Java extensions failed to load. no such file to load -- concurrent_ruby_ext`. This error message is mentioned in [this 20 June 2016 comment](https://github.com/ruby-concurrency/concurrent-ruby/issues/539#issuecomment-227214225), and resolution involved a new gem versions being pushed to rubygems.

Thanks for your work on concurrent-ruby. I'm actually using suckerpunch, which depends on concurrency-ruby.

Greg

**Comment by pitr-ch** [comment]
Thanks for contacting us. I hope no later then next week there will be a RC of 1.1.0 pushed. I've also created #747 to allow to install from master.

**Comment by greghuc** [comment]
@pitr-ch great thanks!
