### ISSUE TITLE
TimerSet: cancel/reset task

### ISSUE THREAD

**Issue by schmurfy** [ruby-concurrency/concurrent-ruby#76]
In my use case I wanted to use a timer to act as a buffer:
- i queue data
- I create or reset a timer so that after X seconds an action is performed
- if the queue reach or exceed a specific size an action is done and the timer is canceled

After looking at the code TimerSet might be my friend using the Concurrent::timer() api passing my actor as an executor instead of using the global pool but what I am missing is a way to cancel/reset (as in restart its countdown).

PS: Looking through the source code is like wandering in a big fair with interesting things everywhere ;)

**Comment by jdantonio** [comment]
Being addressed in #299

**Comment by schmurfy** [comment]
nice ! Any rough idea on when it might land into a release ?

**Comment by jdantonio** [comment]
It will be in the next release, v0.9.0. I hope to finish the PR today.

**Comment by jdantonio** [comment]
PR #299, which implements these features, is now ready to be merged. The PR grew in scope and now included significant refactoring to `TimerSet` and `ScheduledTask`. It also include small enhancements to `Future` and `Concurrent.timer`.

**Comment by jdantonio** [comment]
Merged in #299. Will be released in v0.9.0.
