### ISSUE TITLE
Documentation of AtomicReferenceMapBackend should be on Map class

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#764]
and the AtomicReferenceMapBackend should not be exposed.

**Comment by jayjlawrence** [comment]
I can't promise - but I'll try and do this in the near future.

**Comment by pitr-ch** [comment]
@jayjlawrence thanks for the offer! I've send you an invitation to become a collaborator, please accept and I'll assign this issue to you.

**Comment by pitr-ch** [comment]
I've fixed this in #767
