### ISSUE TITLE
Cannot fetch v 1.1.0 from rubygems

### ISSUE THREAD

**Issue by alishersadikov** [ruby-concurrency/concurrent-ruby#770]
We upgraded to 1.1.0 and when bundling, we are getting: 
```
Fetching gem metadata from https://rubygems.org/...........
Could not find concurrent-ruby-1.1.0 in any of the sources
```
in our CI. I assume uploading to rubygems is in progress. How soon can we expect that to complete?

Thanks!

**Comment by pitr-ch** [comment]
please se https://github.com/ruby-concurrency/concurrent-ruby/issues/768, 1.1.1 should be uploaded today.

**Comment by alishersadikov** [comment]
Thanks!
