### ISSUE TITLE
Drop Ruby 1.9.3 and JRuby 1.7 support

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#772]
- [ ] communicate with authors of depending gems
- [ ] think out and describe here how it will be dropped

**Comment by pitr-ch** [comment]
@jeremyevans thanks for letting me know. However I've fixed that problem, I run into it as well. Maybe just part of concurrent-ruby is required which then misses the `utility/1.9.3` file. I'll release 1.1.2 which will be more defensive today. You can then remove the [restriction](https://github.com/jeremyevans/sequel/compare/42145d14203d...fbadf8f11d6c).

**Comment by pitr-ch** [comment]
@jeremyevans 1.1.2 is pushed, please let me know if it works for you.

**Comment by jeremyevans** [comment]
@pitr-ch Yep, looks good here, thank you for the quick fix: https://travis-ci.org/jeremyevans/sequel/jobs/451424245

**Comment by chrisseaton** [comment]
Nobody serious is using 1.9 at the moment. We only support JRuby latest at the moment. We'll re-evaluate support Ruby versions in the future.

**Comment by jeremyevans** [comment]
@chrisseaton If you are going to close this, can you please update the gemspec: https://github.com/ruby-concurrency/concurrent-ruby/blob/master/concurrent-ruby.gemspec#L30
