### ISSUE TITLE
NoMethodError: undefined method `post' for nil:NilClass

### ISSUE THREAD

**Issue by kamaradclimber** [ruby-concurrency/concurrent-ruby#775]
```
* Operating system:                linux
* Ruby implementation:             Ruby
* `concurrent-ruby` version:       1.1.2
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used:     no
```

When using concurrent-ruby (1.1.2), the following code:
```
 task = Concurrent::TimerTask.new(run_now: true, execution_interval: 2) do
  sleep 5
end
task.execute
```

throws:
```
NoMethodError: undefined method `post' for nil:NilClass
from /home/g_seux/.gem/ruby/2.5.0/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/timer_set.rb:101:in `ns_post_task'
```

This did not happen with 1.0.5

**Comment by delner** [comment]
Having this same issue. From what I can see `Concurrent.global_io_executor` now returns `nil`, so if you were depending on getting an executor from that, it will raise this error.

That `Concurrent.global_io_executor` is equivalent to `Concurrent::Delay.new { Concurrent.new_io_executor(auto_terminate: true) }.value` which also returns `nil`.

**Comment by pitr-ch** [comment]
From the fix I deduce that you are requiring just part of the concurrent-ruby not the whole gem. Is that correct? That's not officially supported at the moment (only `require 'concurrent'` is) so even if we try to make it work sometimes problems get through, see #714. I'll release 1.1.3 with a fix, thanks for investigating.

**Comment by pitr-ch** [comment]
1.1.3 is out, please reopen if it did not fix the issue.

**Comment by delner** [comment]
@pitr-ch I can't speak for @kamaradclimber but this is the case on my end; we were only including `Future`.

**Comment by pitr-ch** [comment]
Thanks for confirming. This type of issues should not happen again after #714 is implemented.
