### ISSUE TITLE
Proposal: Allow specification of thread name for executors

### ISSUE THREAD

**Issue by dgolombek** [ruby-concurrency/concurrent-ruby#785]
Modern loggers ([SemanticLogger](https://github.com/rocketjob/semantic_logger), [Logging](https://github.com/TwP/logging)) support including thread name in log messages. However, it's currently challenging to set the thread names used with executors. With the addition of Thread#name= in Ruby 2.3, we can now support this in a multi-platform way:

- Thread#name= in MRI/Rubinius
- Using a ThreadFactory in JRuby

I'd propose adding a thread_name option for executors. If ruby version is less than 2.3 or the thread name isn't set, it does nothing. Otherwise, use that thread_name (with -%d based on AtomicFixnum/AtomicInteger for uniqueness) when building new threads.

I'm happy to implement, just wanted to get feedback first.

Thanks
Dave

**Comment by dgolombek** [comment]
In the course of implementing this, I discovered that JRuby doesn't work as I expected it to, and this is hard to implement there currently. I've submitted jruby/jruby#5543 to get this fixed in JRuby, but it'll be  a while before that's available in enough JRuby versions to make this widely supported there.

**Comment by pitr-ch** [comment]
Thanks, this would be a great addition. `name-%d` sounds good, could you also include proc based name generation e.g.`-> i { "name-#{i.to_s(36)}" }`? I've assigned the issue to you. It think this would be valuable even if it works only in MRI for now.
