### ISSUE TITLE
typo in readme file

### ISSUE THREAD

**Issue by 2017kamb** [ruby-concurrency/concurrent-ruby#795]
typo mistake in readme file in the following line:
Concurrent Ruby makes one of the strongest thread safety guarantees of any Ruby concurrency library, providing consistent behavior and guarantees on all **three** of the main Ruby interpreters (MRI/CRuby, JRuby, Rubinius, TruffleRuby).

In the above line **three** should be **four**

**Comment by pitr-ch** [comment]
Thanks fixed
