### ISSUE TITLE
Concurrent::Set is not thread-safe in CRuby

### ISSUE THREAD

**Issue by fxn** [ruby-concurrency/concurrent-ruby#796]
`Concurrent::Set` returns `Set` in CRuby with this argument:

```ruby
# Because MRI never runs code in parallel, the existing
# non-thread-safe structures should usually work fine.
::Set
```

As discussed in #793, that is not enough for thread-safety, you also need the interface to be atomic somehow. For `Hash` and `Array` this holds because they are written in C, but `Set` is [partially written in Ruby](https://github.com/ruby/ruby/blob/trunk/lib/set.rb).

To demonstrate `Concurrent::Set` is not thread-safe I have created this artificial example:

```ruby
require "concurrent-ruby"

class MySet < Concurrent::Set
  # Note include? is written in Ruby in Set, like delete?
  def include?(o)
    puts "include? call issued, 1 belongs to self, but there is a context switch"
    sleep 2
    super
  end
end

set = MySet[1]

t = Thread.new do
  sleep 1
  puts "clearing the set in a different thread"
  set.clear
end

p set.delete?(1) # should be self, but it is nil

t.join

```

By the time `delete?` is invoked, the set has the element 1, therefore, that method should return `self` (the set). However, it returns `nil` because `clear` was called during a context switch in the middle of the method execution.

**Comment by fxn** [comment]
I have revised the example to have the context switch happen in the middle of the execution of `delete?`.

**Comment by thedarkone** [comment]
Hi @fxn,

you are right, the comment should be dropped (it is incorrect). https://github.com/ruby-concurrency/concurrent-ruby/blob/b20a56296e6ef6dd85d9eb07100271f369787509/lib/concurrent/set.rb#L26-L27

---

Furthermore, currently it looks like Set is not safe to use beyond basic `add`/`remove`/`include?` methods. I knew Set was written in Ruby, and I skimmed through the methods while reviewing #666, it looked fine to me 😞 .

**Comment by pitr-ch** [comment]
@fxn thanks for filing the issue!
@haridutt12 would you be interested in taking a stab at fixing it?

**Comment by anuragshopify** [comment]
I'd like to work on this. What would the fix entail though? Changing the implementation in mri ruby or providing a thread safe interface here?

**Comment by pitr-ch** [comment]
@anuragshopify thank you! I would recommend to inherit from the MRI's Set in concurrent-ruby and fixing the methods in the new class here. Then you could try to contribute it back to MRI.

**Comment by fzakaria** [comment]
@fxn is my stab at the fix: https://github.com/ruby-concurrency/concurrent-ruby/pull/847/files

**Comment by pitr-ch** [comment]
@fxn thank you for the PR! I have a proper look in few days. I've run out of time today.

**Comment by fxn** [comment]
🎉
