### ISSUE TITLE
Is the documentation for Concurrent::Map#put_if_absent inverted?

### ISSUE THREAD

**Issue by nerdrew** [ruby-concurrency/concurrent-ruby#798]
The documentation looks like it says that it will return the new value if the key was not present and return nil if the new value was not inserted because the key *was* present.

It looks like the implementation is the opposite.

```
% pry -rconcurrent
[1] pry(main)> m = Concurrent::Map.new
=> #<Concurrent::Map:0x007f80e98124c0 entries=0 default_proc=nil>
[2] pry(main)> m.put_if_absent("a", 1)
=> nil
[3] pry(main)> m.put_if_absent("a", 2)
=> 1
[4] pry(main)> 
```

**Comment by nerdrew** [comment]
Documentation: http://ruby-concurrency.github.io/concurrent-ruby/1.1.x/Concurrent/Map.html#put_if_absent-instance_method

**Comment by pitr-ch** [comment]
Thanks @nerdrew! You are right. Could you contribute a fix please?

**Comment by edzhelyov** [comment]
Hey, is this still open? I can take a stab at fixing it. The code needs to change in accordance with the documentation, right?

**Comment by pitr-ch** [comment]
@edzhelyov thank you! Please do. The behaviour is correct, it has to match https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#putIfAbsent-K-V- so the documentation needs a fix.
