### ISSUE TITLE
Why does ScheduledTask accept an executor?

### ISSUE THREAD

**Issue by FooBarWidget** [ruby-concurrency/concurrent-ruby#815]
`@executor` isn't used anywhere in the ScheduledTask source code. Why does ScheduledTask accept an executor as option? Maybe it shouldn't? It appears as if ScheduledTask is supposed to be executed by a TimerSet, not by a normal executor.

**Comment by jdantonio** [comment]
As far as I can tell that's a mistake on my part made in commit e20922d9ae4f0cf2fd8a6a2eae4c0533a12ee4c8 "TimerSet now creates ScheduledTasks." That was a long time ago so I can't remember specifics. I'm guessing based on what I see in the code.

Prior to that commit the `TimerSet` object would create a private `Task` object and run that task on the provided executor. In that commit I refactored the `Task` object away and replaced it with `ScheduledTask`, removing redundant code. In that commit the executor is being passed to the `ScheduledTask`, presumably so the task can be run on that executor. It appears that I didn't update `ScheduledTask` at that time to honor the executor.

This seems like it's a bug that should be fixed. The original intent seems to have been for the `ScheduledTask` object to run the task on the provided executor, to retain the behavior we had prior to the linked refactor, and the update failed to meet that requirement.

**Comment by FooBarWidget** [comment]
So from what I understand, TimerSet is an evented reactor, and so it only has one thread no matter how many ScheduledTasks, which makes it very efficient even when a large number of ScheduledTasks are scheduled, correct?

And because TimerSet if evented, you don't want to run potentially blocking code on there, and so when a ScheduledTask is activated, TimerSet should pass the task to an executor, which is what the parameter was intended for. Is this also correct?

**Comment by jdantonio** [comment]
Correct on all counts.
