### ISSUE TITLE
What is the difference between ScheduledTask and Promises.schedule?

### ISSUE THREAD

**Issue by FooBarWidget** [ruby-concurrency/concurrent-ruby#816]
ScheduledTask and Promises.schedule seem to do the same thing, although Promises.schedule also accepts a Time object. But otherwise, what's the difference between these two?

**Comment by jdantonio** [comment]
Old versus new. ScheduledTask was the original abstraction, first written in the early days of this library. @pitr-ch, the current maintainer, has been working to move as many features as reasonable into the Promises abstraction. Over time, the various different abstractions began to increasingly share the same internals. Things that were perceived to be different evolved into functionality-specific wrappers around a small number of internal components. The other reason, which follows from the first, is that one abstraction with a bunch of options may be easier for programmers to learn that a large number of abstractions that are all variations on one theme.

I do not know the timeline for further refactoring and deprecations. We'll have to ask @pitr-ch for that.

**Comment by pitr-ch** [comment]
What @jdantonio said. Promises is new more integrated replacement. I would recomend using schedule. It can be easily integrated with other abstractions since result is a common chain-able Promises::Future. The ScheduledTask is isolated. Over time ScheduledTask will be deprecated.
