### ISSUE TITLE
Dup and Clone with (Mutable)Structs

### ISSUE THREAD

**Issue by kaikuchn** [ruby-concurrency/concurrent-ruby#836]
```
* Ruby implementation:             Ruby
* `concurrent-ruby` version:       1.1.5
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used:     no
```

Hey folks,

I've started using this awesome gem in an effort to make one of my employer's apps thread-safe. Thank you for all your hard work, this makes my life so much easier! :)

While I'd preferably not even use the `MutableStruct` I have to do so for now. And in doing so I noticed that `dup` and `clone` do not behave as they do with Ruby's normal `Struct`. I.e., since values are stored in an array and dup/clone are not overwritten  this happens:

```ruby
greeting = Concurrent::MutableStruct.new(:text).new("Hello, World!")
# => #<concurrent/mutable_struct {:text=>"Hello, World!"}>
greeting.dup.text = "Goodbye, World!"
# => "Goodbye, World!"
greeting.text
# => "Goodbye, World!"
```

While in a normal Ruby `Struct` a call to dup also duplicates the value table:

```ruby
greeting = Struct.new(:text).new("Hello, World!")
# => #<struct text="Hello, World!">
greeting.dup.text = "Goodbye, World!"
# => "Goodbye, World!"
greeting.text
# => "Hello, World!"
```

I don't know if this is something you'd deem a bug, I guess it depends on how much of a drop-in replacement mutable struct is supposed to be. However, it is something that surprised me, luckily in my test suite only.

Best regards,
Kai

**Comment by kaikuchn** [comment]
By the way, if you consider this a bug, I'm more than happy to craft a PR in an attempt to fix it.

**Comment by pitr-ch** [comment]
Thanks for the report @kaikuchn, PR would be highly appreciated, Thanks! From a brief look it looks like we do not implement dup and clone at all which is probably the problem.
