### ISSUE TITLE
Find scheduled_task by args and remove it

### ISSUE THREAD

**Issue by AlexLarra** [ruby-concurrency/concurrent-ruby#846]
I'm using [sucker_punch](https://github.com/brandonhilkert/sucker_punch) based in concurrent-ruby.
But I need to find a scheduled task by the passed args in another request to kill it if necessary.

```
* Operating system: linux
* Ruby implementation: Ruby
* `concurrent-ruby` version: 1.1.5
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used: no
```

**Comment by pitr-ch** [comment]
Could you be more concrete what are you looking for? A code snippet would help.

**Comment by AlexLarra** [comment]
Something like:

```
Concurrent::Scheduled.all.select { |task| task.args[0] == "Turkey" }
```

**Comment by pitr-ch** [comment]
I thought about it. I would recommend to ask for this API in the `sucker_punch` gem. For each scheduled job it could expose the ScheduledTask object. Then it would be possible to cancel it. 

I'd like to keep this gem and its API low-level. Having a global store of all the schedule tasks would slow it down and complicate things for mostly unused API.
