### ISSUE TITLE
segfault on ruby 2.5.1 (on travis-ci)

### ISSUE THREAD

**Issue by DavidS** [ruby-concurrency/concurrent-ruby#849]
```
* Operating system:                linux
* Ruby implementation:             Ruby 2.5.1
* `concurrent-ruby` version:       1.1.6
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used:   no
```

Running https://github.com/puppetlabs/puppet_litmus/pull/241/commits/1fd29fecad3d83d6a4ee0f1afaab204016d64d2a on travis consistently gives the attached ruby segfault: [log.txt](https://github.com/ruby-concurrency/concurrent-ruby/files/4191054/log.txt)

```$ BUNDLE_GEMFILE=./Gemfile bundle exec rake litmus:acceptance:parallel
Running against 1 targets.
..../home/travis/build/puppetlabs/puppet_litmus/puppetlabs-motd/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:113: [BUG] Segmentation fault at 0x00000000371bb696
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
[...]
```

The same code works fine on ruby 2.5.7.

**Comment by pitr-ch** [comment]
Thanks for the report. Few notes:
* There was similar error https://github.com/ruby-concurrency/concurrent-ruby/issues/808 
* This is a bug in MRI no Ruby code should be able to segfault Ruby.
* The original version working on 2.5.1 was breaking on 2.6.3.

Further investigation is needed.

**Comment by pitr-ch** [comment]
@fzakaria would you be interested to take a look at this?
So far I know that Thread creation, Mutex, Queue cause problems and at the moment I do not have more ideas how to get around this.

**Comment by fzakaria** [comment]
Sure thing.
I'll build 2.51 from source & run the tests and see what I can uncover.

**Comment by fzakaria** [comment]
Few notes from looking into it:
1. @pitr-ch added some changes to address https://bugs.ruby-lang.org/issues/16288 as part of https://github.com/ruby-concurrency/concurrent-ruby/pull/821

> The change basically removed creating new threads in the finalizers since the finalizers may be called during shutdown & threads cannot be started.

2. This bug involves changes post (1) where the segfault is occurring within `Queue#push`
To me that means either the `Queue` or the `@index` have been garbage collected already.

**Comment by pitr-ch** [comment]
Thanks for looking into this. I got an idea how to deal with it, please have a look https://github.com/ruby-concurrency/concurrent-ruby/pull/856

**Comment by pitr-ch** [comment]
@DavidS could you try the PR if it works for you?

**Comment by DavidS** [comment]
Apologies for the delay - I've been on vacation the last week. I'll see if I can run that PR through our CI systems, we've had quite a high hit-rate on the segfault.

**Comment by pitr-ch** [comment]
@DavidS No problem, thank you for giving it a try.

**Comment by schuylr** [comment]
Just want to confirm I'm also seeing this on Ruby 2.5.3 with Version 1.1.6 of the gem.
