### ISSUE TITLE
v1.1.6 LoadError: cannot load such file -- etc (LoadError)

### ISSUE THREAD

**Issue by Justin-W** [ruby-concurrency/concurrent-ruby#851]
v1.1.6 seems to have introduced a [new code usage of the `etc` gem](https://github.com/ruby-concurrency/concurrent-ruby/blob/v1.1.6/lib/concurrent-ruby/concurrent/utility/processor_counter.rb#L1), but does not properly register it as a gem dependency, resulting in a runtime LoadError while attempting to install v1.1.6 via `bundler`.

FYI: Our gem depends on concurrent-ruby indirectly.

### Error trace:

```
	14: from /usr/lib/ruby/gems/2.5.0/gems/azure_mgmt_network-0.17.4/lib/azure_mgmt_network.rb:5:in `<top (required)>'
	13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	11: from /usr/lib/ruby/gems/2.5.0/gems/azure_mgmt_network-0.17.4/lib/2018-08-01/generated/azure_mgmt_network.rb:17:in `<top (required)>'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent.rb:4:in `<top (required)>'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/configuration.rb:9:in `<top (required)>'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/utility/processor_counter.rb:1:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'  
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- etc (LoadError)
```

### Env info

* Operating system: linux
* Ruby implementation: ruby 2.5.1p57 (2018-03-29 revision 63029)
* `concurrent-ruby` version: 1.1.6 (1.1.5 was fine)
* `concurrent-ruby-ext` installed: unknown
* `concurrent-ruby-edge` used: unknown

`cat /etc/os-release`:
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.1
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"

**Comment by pitr-ch** [comment]
As far as I know `etc` is part of the stdlib https://ruby-doc.org/stdlib-2.5.1/libdoc/etc/rdoc/index.html as a default gem. Could it be an issue with your environment?

**Comment by Justin-W** [comment]
> As far as I know `etc` is part of the stdlib https://ruby-doc.org/stdlib-2.5.1/libdoc/etc/rdoc/index.html as a default gem. Could it be an issue with your environment?

After further investigation, it seems that the root cause of this issue is [alpine linux issue #9216](https://gitlab.alpinelinux.org/alpine/aports/issues/9216), where the ruby-etc package was excluded from the alpine linux v3.8 image despite the fact that etc has been a standard gem since ruby v2.5.0. Apparently, this issue caused problems for multiple ruby-based systems when built on top of alpine v3.8.

References:

- [Standard Gems: etc](https://stdgems.org/etc/)
- [[v3.8][edge] ruby-bundler missing dependency on ruby-etc (#9216) · Issues · alpine / aports · GitLab](https://gitlab.alpinelinux.org/alpine/aports/issues/9216)
- [Alpine 3.8.1 released | Alpine Linux](https://alpinelinux.org/posts/Alpine-3.8.1-released.html)
- [alpine-3.8 breaks grpc gem installation · Issue #424 · gliderlabs/docker-alpine](https://github.com/gliderlabs/docker-alpine/issues/424)
- [fpm is broken on Alpine 3.8 · Issue #1534 · jordansissel/fpm](https://github.com/jordansissel/fpm/issues/1534)

My apologies for initially misattributing the issue as a ruby-concurrency issue. 😃

**Comment by pitr-ch** [comment]
No problem. Thanks for the detailed followup.
