### ISSUE TITLE
Outdated documentation about Concurrent::Async and constructors?

### ISSUE THREAD

**Issue by markiz** [ruby-concurrency/concurrent-ruby#863]
https://github.com/ruby-concurrency/concurrent-ruby/blob/7dc6eb04142f008ffa79a59c125669c6fcbb85a8/lib/concurrent-ruby/concurrent/async.rb#L61-L79

I don't think that is necessary anymore, since everything related to initialization now lives in `.new`?

**Comment by pitr-ch** [comment]
You are right, Thanks! Could you open a PR removing it?

**Comment by markiz** [comment]
@pitr-ch Sure, #878
