### ISSUE TITLE
Concurrent::ThreadPoolExecutor does not increase thread count

### ISSUE THREAD

**Issue by metaphalon** [ruby-concurrency/concurrent-ruby#864]
When running the code [1] I can see that the tasks are done one after the other.
When I start this with min_threads > 1 the tasks are executed in parallel.
Looks to me the thread count is not automatically increasing.
It seems only to happen with jRuby (9.2.11.1), using MRI ruby seemed fine.

```
* Operating system:                linux
* Ruby implementation:             JRuby  (9.2.11.1)
* `concurrent-ruby` version:       1.5.5
```

[1]
```
executor = Concurrent::ThreadPoolExecutor.new(
  min_threads: 0,
  max_threads: 3,
  max_queue: 0
)

20.times do |j|
  executor.post do
    10.times do 
      puts("Sleep 1 x#{j}")
      sleep 1
    end
  end
end

```

**Comment by pitr-ch** [comment]
I do not have time to explore this problem at the moment. I'll get to it eventually but if somebody contributes by investigating and potentially opening a PR it would be a big help.

**Comment by metaphalon** [comment]
I had another look at it and it seems its related to the java version.

The described problem exists for me in java 1.8.0 [1].
When running the code with java11.0.8  [2], the problem does not appear.

So this is probably a java issue and not a problem of this gem, so I will close the ticket.

[1]
OpenJDK Runtime Environment (build 1.8.0_232-b09)

[2]
OpenJDK Runtime Environment 18.9 (build 11.0.8+10)

**Comment by pitr-ch** [comment]
@metaphalon thanks for the follow up!
