### ISSUE TITLE
Question: What is the purpose of `ThreadLocalVar#bind`?

### ISSUE THREAD

**Issue by emilyst** [ruby-concurrency/concurrent-ruby#888]
What is the purpose of `ThreadLocalVar#bind` and what is the difference between that and `ThreadLocalVar#set`?

The documentation says it's available, but it's unclear why I would use it or what value I would pass it.

**Comment by pitr-ch** [comment]
Does this help http://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/ThreadLocalVar.html#bind-instance_method ?

**Comment by emilyst** [comment]
> Does this help http://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/ThreadLocalVar.html#bind-instance_method ?

Hi, thanks for responding.

It does not help. It says,

> Bind the given value to thread local storage during execution of the given block.

This is unfortunately circular. It says that what `#bind` does is "bind." Additionally, I could not find this method used in any tests (it's odd that it should exist as a public and documented method but be entirely untested). I searched extensively on GitHub for usages of it, but I could not find any practical examples.

The documentation also does not state what the value should be, what the block should do, under what circumstances the block may be called (just at call-time or as a callback later?), what parameters the block may receive, nor what the method returns.

**Comment by pitr-ch** [comment]
Ah, the "bind" in the documentation has a "stores" meaning, it does not refer to the method.
Instead of trying to describe it, let me past the source of the method here, I think is most clear and self-explanatory. 
```ruby
    def bind(value, &block)
      if block_given?
        old_value = self.value
        begin
          self.value = value
          yield
        ensure
          self.value = old_value
        end
      end
    end
```
Please reopen if needed.

**Comment by emilyst** [comment]
I did see the source, but I wasn't sure what the purpose of this was. I'll try to summarize what I believe I'm seeing.

You can use `#bind` when you want to execute some code as if the value of the variable is something other than what it actually is?

**Comment by pitr-ch** [comment]
yes. I've included one more example of common usage. 

```ruby
require "concurrent"

tl_var = Concurrent::ThreadLocalVar.new :default_value

thread = Thread.new do
  p tl_var.value
  # change the value only for the duration of the block,
  # makes sure that the change is always reverted
  tl_var.bind 42 do
    p tl_var.value
    raise # even though there is an exception the value is reverted back to default
  end
ensure
  p tl_var.value # the value was reverted outside of the block
end

thread.value

__END__ Output is:
:default_value
42
:default_value

and the exception
```

**Comment by emilyst** [comment]
Thanks.
