### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by jots** [ruby-concurrency/concurrent-ruby#9]
I get the following error when trying to install.  Any ideas what is causing it?

% ruby --version
ruby 1.9.3p484 (2013-11-22) [x86_64-linux] Brightbox

% bundle install --path vendor
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

/usr/bin/ruby1.9.1 extconf.rb 
creating Makefile

make
compiling futures.c
In file included from futures.c:10:0:
/usr/include/ruby-1.9.1/ruby/backward/rubysig.h:14:2: warning: #warning rubysig.h is obsolete [-Wcpp]
 #warning rubysig.h is obsolete
  ^
futures.c:11:20: fatal error: intern.h: No such file or directory
 #include "intern.h"
                    ^
compilation terminated.
make: **\* [futures.o] Error 1
An error occurred while installing concurrent (0.2.2), and Bundler cannot
continue

**Comment by mmzoo** [comment]
Didn't help me haha. But thanks to this thread I could figure it out.
