### ISSUE TITLE
How do you set defaults for thread pools globally?

### ISSUE THREAD

**Issue by jcavalieri** [ruby-concurrency/concurrent-ruby#903]
```
* Operating system:                linux
* Ruby implementation:             Ruby
* `concurrent-ruby` version:       ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used:    no
```

Hi concurrent-ruby Maintainers and Community,

I'm getting an error of `fatal: No live threads left. Deadlock?` when using a handful `Promises::future` calls.

Digging into it, I found that no only is my project's code kicking off threads using futures,  but semantic-logger, the project's logger, is also kicking off threads with concurrent-ruby. So it looks like my futures + logging from semantic logger is causing this error of "fatal: No live threads left. Deadlock?".

I'd like to handle this globally as opposed to creating a customized executor each time I used futures. And I suspect if I can increase max threads and the queue it would solve this problem.

However, I can't find a way to do this globally. I.e. is there a way to set max threads and queue globally?

Thanks,
-John

**Comment by jcavalieri** [comment]
I did this monkey patch for now.

```
# frozen_string_literal: true

require 'concurrent'

module Concurrent
  module Promises
    # Monkey patch to remove threading from concurrent-ruby
    module FactoryMethods
      def default_executor
        :immediate
      end
    end
  end
end
```


It would be nice to be able to do something like this:

```
concurrent_ruby.configure do |config|
  config.default_executor = ....
end
```

**Comment by pitr-ch** [comment]
Do you know any details about the bed interaction that leads to the deadlock?

It is better if projects set up their own pools, to avoid these interactions. It was rather a mistake to provide the global pools in the ConcurrentRuby, driven by making it convenient. The configuration of the global pools is lacking to avoid situations when a project would change the global pool configuration breaking them for other projects using the pools. For that reason the pools have sensible defaults (I hope) and projects should create their own pool if the global pool does not meet the need or if there are conflicts.

I recommend to include FactoryMethods into objects where you need promises to be created and redefine the default_executor there. You could also create your own factory singleton like this that will have your own pool defined with the default_executor method.

**Comment by jcavalieri** [comment]
I believe it is because a promise is essentially calling a block that has many calls to semantic logger. I'm assuming that when a call to the logger is requesting a thread it can't get it, and then promises can't be fulfilled.

So a factory approach sounds interesting. If I'm understanding correctly it is like this example in the documentation?

```
mod = Module.new do
  extend Concurrent::Promises::FactoryMethods
  def self.default_executor
    :fast
  end
end #
mod.future { 1 }.default_executor
Concurrent::Promises.future { 1 }.default_executor
```

And if this is the case, if a project and a dependent gem declare the same default_executor will they be separate thread pools? E.g. if a parent project and a child gem both set their default_executor to `:io` will they still be using the same thread pool?

Thanks,
John

**Comment by jcavalieri** [comment]
Thanks for the suggestion. I went with this, since I don't need threading:

```
module Tasks
  extend Concurrent::Promises::FactoryMethods
  def self.default_executor
    :immediate
  end
end
```

and

`Tasks.future { ... }`

This does appear to work and keep isolation from semantic logger's use of the thread pool.

**Comment by pitr-ch** [comment]
```ruby
  def self.default_executor
    :fast
  end
```
would direct to the global pool. 
To have a separate pool it should create its own, e.g. using the factory method for the already included global fast thread pool (which is intended only for non-blocking tasks). 
```ruby
module Tasks
  extend Concurrent::Promises::FactoryMethods
  EXECUTOR = Concurrent.new_fast_executor
  def self.default_executor
    EXECUTOR
  end
end
```
Using :io global pool could also solve the problem.
