### ISSUE TITLE
NameError: uninitialized constant Concurrent::RubyThreadLocalVar

### ISSUE THREAD

**Issue by wimkorevaar** [ruby-concurrency/concurrent-ruby#987]
The last update broke my pipeline.
I get the following Error:

```
bundle exec rake syntax
rake aborted!
NameError: uninitialized constant Concurrent::RubyThreadLocalVar
Did you mean?  Concurrent::RubyThreadPoolExecutor
```

I now hardcoded it tot version 1.1.10 and it works again.
So in one of the merges this variable disappeared, but can't really see this change in any of the PR's

...
* Operating system:                     linux
* Ruby implementation:               Ruby 
* `concurrent-ruby` version:         1.1.20
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used:   no
```

**Comment by eregon** [comment]
Duplicate of https://github.com/ruby-concurrency/concurrent-ruby/issues/986, use `Concurrent::ThreadLocalVar` and not `Concurrent::RubyThreadLocalVar`.
